### ISSUE TITLE
繁體中文翻譯

### ISSUE THREAD

**Issue by nczz** [terrylinooo/githuber-md#1]
Hi,

你好，我是阿竣。

謝謝你的分享，我將目前語言的 POT 檔案翻譯了一份 zh_TW 的版本。（看起來應該還有一些字串還沒有抽出來）

- PO : [Link](https://www.mxp.tw/wp-content/themes/ex-astris/languages/wp-githuber-md-zh_TW.po)
- MO: [Link](https://www.mxp.tw/wp-content/themes/ex-astris/languages/wp-githuber-md-zh_TW.mo)

外掛真的很棒！也歡迎加入 [WordPress Taiwan 的 Facebook 社團](https://www.facebook.com/groups/wordpresstw/) 或是 [社群的 Slack](https://wp-meetups.com/wordpress-taiwan-slack/)

**Comment by terrylinooo** [comment]
謝謝。這兩天會整理好。謝謝您的鼓勵

**Comment by alexclassroom** [comment]
群策群力，等我一下，我用阿竣的前一版結果加上最新版字串，修改完給你一版，你再從這一版開始修正。

**Comment by alexclassroom** [comment]
WP Githuber MD 的台灣繁體中文語系檔下載連結如下：
點擊[這裡](https://app.box.com/s/iskmm0bkc2tzwj2byfucciipxbxirty7)下載

這個連結內包含重新翻譯的 Githuber 佈景主題的台灣繁體中文語系檔。

**Comment by terrylinooo** [comment]
謝謝。今天會處理好。

**Comment by terrylinooo** [comment]
我覺得，翻的意思居然比我想要表達的意思還清楚，不虧是專業的。
想請問一下 credit link 要指到什麼網址呢。有參與的都可以放。

- GitHub ID / GitHub user profile
- WordPress(dot)org ID / WordPress user profile
- 網路匿稱 / 個人網站網址

再請兩位給我資訊囉! 我要測試一些不同版本找 bug 晚上再一起更新上去。

**Comment by alexclassroom** [comment]
阿力獅/https://www.alexclassroom.com

**Comment by terrylinooo** [comment]
謝謝大家幫忙。

先關閉囉。
