### ISSUE TITLE
Markdown in comments only

### ISSUE THREAD

**Issue by Trevor-** [terrylinooo/githuber-md#100]
**Any issue will be ignored if you don't provide the following detailed information.**

**Describe the bug**
When only comments is ticked no MD editor appears for the user when they make comments
I only want MD available inside the comments on all posts pages etc. but not on the actual pages or post themselves.
**To reproduce**

1. Go to settings
2. Untick Posts, Pages, Templates, Portfolio
3. Tick Comments
4. Click Save

**Expected behavior**

The editor to appear for the commenters just not for editing the main pages etc. 

**Screenshots**

**Server environment**

 - WordPress version WordPress 5.2.2 running X – Child Theme theme.
 - WP Githuber MD plugin version *1.11.6*
 - PHP version 7.something :-|

**User environment**

 - OS: Mac
 - Browser alll

**Additional context**

**Comment by terrylinooo** [comment]
Markdown for comments is not working for now. Thanks for your feedback.
I will make it work, perhaps  in version 1.12.0

**Comment by MuTsunTsai** [comment]
Any news on this issue? We've been waiting to see this feature.
