### ISSUE TITLE
关于语法高亮

### ISSUE THREAD

**Issue by only-love-yiqiu** [terrylinooo/githuber-md#101]
需要配合语法高亮插件使用才能实现html显示高亮吗,之前使用WP Editor 预览高亮正常，但是实际显示出来的高亮是有问题的，这个插件预览也是没有高亮的，是我还没有搞明白还是需要其他插件

**Comment by terrylinooo** [comment]
你的設定是什麼?

**Comment by only-love-yiqiu** [comment]
我使用的是默认设置,但是我没有使用高亮插件 ,markdown预览的部分 ``` ``` 代码块高亮, 但是实际显示文章没有高亮, `` 反引号代码预览没有高亮，显示也没有高亮




------------------ 原始邮件 ------------------
发件人: "Terry L."<notifications@github.com>; 
发送时间: 2019年7月24日(星期三) 晚上9:12
收件人: "terrylinooo/githuber-md"<githuber-md@noreply.github.com>; 
抄送: "梦幻男孩"<az460024285@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [terrylinooo/githuber-md] 关于语法高亮 (#101)




你的設定是什麼?

**Comment by terrylinooo** [comment]
你必須要開啟模組。在有使用語法高亮的頁面再儲存一次文章 解析出該頁面需要載入該模組。
因為 Githuber MD 不是以開什麼模組，前端就載入相對應的 script，這樣會載入一堆用不到的東西拖慢你的網站載入速度。

Githuber MD 只會載入該頁面有需要的東西。
例如你有開始 KaTeX，也在文章用了 KaTeX 語法，就只有該頁面會載入 KaTeX 的 JavaScript。

範例已經寫的很清楚，如果還沒辦法的話，我也無能為力了。

**Comment by du5** [comment]
感谢开源，不过我也遇到了同样的问题
