### ISSUE TITLE
编辑器语言显示繁体，如何切换为显示简中或者英文？

### ISSUE THREAD

**Issue by BryanXu77** [terrylinooo/githuber-md#103]
**問題或臭蟲**

编辑器界面语言为繁中，如何显示为简中或者英文？

**如何重現**

启用Githu MD插件后，编辑器界面的一些图标，鼠标放上去，显示为繁体中文，不知道可否切换为显示简中。

**預期的行為或結果**
希望能切换语言显示

**畫面截圖**

![image](https://user-images.githubusercontent.com/53372746/61995042-93fe5a80-b0b5-11e9-9d24-adb8e1971e6f.png)

**伺服器環境**

 - WordPress 版本 5.2.2
 - WP Githuber MD 版本 1.11.7
 - PHP 版本 7.3

**用戶端環境**

 - 作業系統 CentOS 7.6
 - 瀏覽器 Chrome

**其它說明**
N/A

**Comment by BryanXu77** [comment]
这个我自己解决了：
1. 在 ./assets/vendor/editor.md/languages/目录下，将zh-tw.js复制为zh-cn.js
2. 编辑里面的文字为简中；
3. 修改 ./wp-githuber-md/src/Controllers/Markdown.php 文件，将zh-tw.js 改为 zh-cn.js

**Comment by terrylinooo** [comment]
1.14.0 支援。
