### ISSUE TITLE
无序列表无法正常显示

### ISSUE THREAD

**Issue by BryanXu77** [terrylinooo/githuber-md#104]
**如果沒有提供以下詳細資訊，您開立的問題回報會被無視。**

**問題或臭蟲**

无序列表无法正常显示

**如何重現**

设置无序列表，实时预览与WordPress预览，都无法显示，参见截图
![image](https://user-images.githubusercontent.com/53372746/61995501-0e31dd80-b0bc-11e9-9eb4-a3bd23a12834.png)

**預期的行為或結果**

需要有圆点状标记

**畫面截圖**

![image](https://user-images.githubusercontent.com/53372746/61995510-2275da80-b0bc-11e9-8ac0-1c0c491b149f.png)

**伺服器環境**

 - WordPress 版本 5.2.2
 - WP Githuber MD 版本 1.11.7
 - PHP 版本 7.3

**用戶端環境**

 - 作業系統 CentOS 7.6
 - 瀏覽器 Chrome

**其它說明**

N/A

**Comment by terrylinooo** [comment]
CSS 的預覽問題，我會在 1.11.8 修復。

**Comment by BryanXu77** [comment]
我刚刚升级了1.11.8，看起来还是有问题啊，依旧不能显示。
css文件已经更新了：
```shell
[root@kb css]# pwd
/var/www/html/wp-content/plugins/wp-githuber-md/assets/vendor/editor.md/css
[root@kb css]# ll
total 164
-rw-r--r-- 1 xpy xpy 85119 Aug 28 09:25 editormd.css
-rw-r--r-- 1 xpy xpy 64496 Aug 28 09:25 editormd.min.css
-rw-r--r-- 1 xpy xpy 14920 Aug 28 09:25 markdown-theme-github.css
```

**Comment by terrylinooo** [comment]
清除你的瀏覽器 cache

**Comment by BryanXu77** [comment]
嗯，可以了，非常感谢。
