### ISSUE TITLE
只使用Katex inline时，Katex script无法被加载（#96 again）

### ISSUE THREAD

**Issue by Zars19** [terrylinooo/githuber-md#106]
**如果沒有提供以下詳細資訊，您開立的問題回報會被無視。**

**問題或臭蟲**

版本已更新，但出现了同#96完全相同的问题

> 如果一篇文章中只有`$$ this is a LaTex inline code $$` 这样的 inline latex，而从未使用
> 
>     ``` katex
>     this is a Latex paragraphy
>     ```
> 
> 的时候，会无法加载 katex 的 script
> 
> 在文章中加入
> 
>     ``` katex
>     this is a Latex paragraphy
>     ```
> 
> 就会正常加载katex script

**如何重現**

請告知重現此問題的步驟回何：

> 文章中只使用 inline katex
> 发布文章后无法正常加载 katex script

**預期的行為或結果**

清楚的說明您預期什麼樣的結果才是正常
![L(3JKXK{D877%KK{{W`8B84](https://user-images.githubusercontent.com/27544957/62603502-9d46bd00-b928-11e9-8fae-ebeb9aef31e8.png)

**畫面截圖**

不使用Code-Block Katex时
![D_QFLXJKJE443HP$%VH9@O](https://user-images.githubusercontent.com/27544957/62603519-a8015200-b928-11e9-9b48-2dd03f55fb92.png)
被显示为
![8PR}RZG62NI`3J7`UBBCJTE](https://user-images.githubusercontent.com/27544957/62603598-d7b05a00-b928-11e9-8de2-955aa84efb0b.png)
而加入
![D$SGR6NR_Q8A5K8696)9R_P](https://user-images.githubusercontent.com/27544957/62603612-dda63b00-b928-11e9-8354-510699ba5ddb.png)
后，可如预期显示
![L(3JKXK{D877%KK{{W`8B84](https://user-images.githubusercontent.com/27544957/62603626-e26aef00-b928-11e9-9d2a-0ac8e72fc928.png)

伺服器環境

    WordPress 版本 5.2.2
    WP Githuber MD 版本 1.11.7
    PHP 版本 5.6

用戶端環境

    作業系統 Windows 10
    瀏覽器 Firefox

**其它說明**

无

**Comment by qiujiangkun** [comment]
你好，经过我的查证，可能是这里出现了问题。检测不到语言导致不加载katex模块。
src/Controller/Markdown.php
function detect_code_languages
```php

		if ( preg_match_all( '/<code class="language-([a-z\-0-9]+)"/', $post_content, $matches ) > 0 && ! empty( $matches[1] ) ) {

			foreach ( $matches[1] as $match ) {
				if ( ! empty( $prism_codes[ $match ] ) ) {
					$prism_meta_array[ $match ] = $match;
				}

				// Check if this componets requires the parent components or not.
				if ( ! empty( $prism_component_parent[ $match ] ) ) {
					foreach ( $prism_component_parent[ $match ] as $parent ) {

						// If it need a parent componet, add it to the $paris_meta_array.
						if ( empty( $prism_meta_array[ $parent ] ) ) {
							$prism_meta_array[ $parent ] = $parent;
						}
					}
				}

				if ( 'seq' === $match || 'sequence' === $match ) {
					$is_sequence = true;
				}

				if ( 'flow' === $match || 'flowchart' === $match ) {
					$is_flowchart = true;
				}

				if ( 'mermaid' === $match ) {
					$is_mermaid = true;
				}

				if ( 'katex' === $match ) {
					$is_katex = true;
				}
			}
		} elseif ( preg_match( '/<code class="language-([a-z\-0-9]+)\s([a-z\-0-9]+)-inline"/', $post_content, $matches ) > 0 && ! empty( $matches[1] ) ) {
			if ('katex' === $matches[1] && 'katex' === $matches[2]) {
				$is_katex = true;
			}
		}
```
修改后如下
```php

		if ( preg_match_all( '/language-([a-z\-0-9]+)/', $post_content, $matches ) > 0 && ! empty( $matches[1] ) ) {

			foreach ( $matches[1] as $match ) {
				if ( ! empty( $prism_codes[ $match ] ) ) {
					$prism_meta_array[ $match ] = $match;
				}

				// Check if this componets requires the parent components or not.
				if ( ! empty( $prism_component_parent[ $match ] ) ) {
					foreach ( $prism_component_parent[ $match ] as $parent ) {

						// If it need a parent componet, add it to the $paris_meta_array.
						if ( empty( $prism_meta_array[ $parent ] ) ) {
							$prism_meta_array[ $parent ] = $parent;
						}
					}
				}

				if ( 'seq' === $match || 'sequence' === $match ) {
					$is_sequence = true;
				}

				if ( 'flow' === $match || 'flowchart' === $match ) {
					$is_flowchart = true;
				}

				if ( 'mermaid' === $match ) {
					$is_mermaid = true;
				}

				if ( 'katex' === $match ) {
					$is_katex = true;
				}
			}
		}
```

**Comment by Zars19** [comment]
问题已解决，非常感谢

**Comment by Zars19** [comment]
问题已解决，非常感谢
