### ISSUE TITLE
KaTex对公式的支持不足

### ISSUE THREAD

**Issue by qiujiangkun** [terrylinooo/githuber-md#107]
## 存在问题
不支持独立公式（参考https://katex.org/ 上面的\sum公式），在标题，表格等地方无法渲染公式
![jeekrs com_wp-admin_post-new php](https://user-images.githubusercontent.com/33482468/62729486-99ae5580-ba50-11e9-885a-3dda2a1d1649.png)
## 测试文本
```markdown
- what is this $$\sum^{n}_{x=1}{x}$$
# what is this $$\sum^{n}_{x=1}{x}$$
1.  what is this $$\sum^{n}_{x=1}{x}$$

$$\sum^{n}_{x=1}{x}$$

Only support inline LaTeX Math formula
```

**Comment by terrylinooo** [comment]
由於 Githuber MD 是很多知名 javascript 功能庫的實現，有遇到問題我會再檢查是否需要更新該庫的版本。我會在下一次更新時，更新 KaTaX 的 javascript library 到最新版看看是否有無解決此問題。

**Comment by qiujiangkun** [comment]
> 由於 Githuber MD 是很多知名 javascript 功能庫的實現，有遇到問題我會再檢查是否需要更新該庫的版本。我會在下一次更新時，更新 KaTaX 的 javascript library 到最新版看看是否有無解決此問題。

我认真研究了一下源码,发现预览时的bug出在marked和editor.md上面,属于逻辑考虑不周到,而且无法简单消除.我放弃了

**Comment by qiujiangkun** [comment]
我做到了前端页面的渲染,但对后端的预览无能为力

**Comment by qiujiangkun** [comment]
我重新实现了编辑器预览模块，采用restAPI调用后台的渲染结果，避开了marked混乱的逻辑
