### ISSUE TITLE
建议支持自定义CSS，并提供一些配置好的CSS

### ISSUE THREAD

**Issue by qiujiangkun** [terrylinooo/githuber-md#108]
如题，当前的默认样式太丑了，而且自己加CSS比较麻烦

**Comment by terrylinooo** [comment]
指預覽?

**Comment by qiujiangkun** [comment]
指前端和预览，也许可以做到支持分开配置。

**Comment by terrylinooo** [comment]
前端是你自己用的 theme 自己的事。

預覽的話目前是使用 GitHub 的樣式，開放自定義你使用了用了一堆亂七八糟亂下!important 的  CSS 反會破壞其它功能的預覽。你覺得醜我也沒辦法。

我不打算支持這個功能。如果你自己有加上這個功能我會 approve your commit 。

**Comment by terrylinooo** [comment]
在這次的更新我會加上一個選項讓用戶自行選用預覽畫面渲染用的 CSS 路徑。有更新時我會關閉此 issue 來通知您。
