### ISSUE TITLE
Ignore Block

### ISSUE THREAD

**Issue by jeffgnpc** [terrylinooo/githuber-md#11]
Is there away to have markdown parser ignore a block of text?

I wanting to use https://github.com/Kotlin/kotlin-playground-wp-plugin.  I can place a [kotlin][\kotlin] to have that chunk of text run as Kotlin code.  It works great, except <p> tags get inserted into the code.

Possible solution: do a regex replace "\[kotlin\].*\[\\kotlin\]" with some random GUID, and then reinsert after the markdown parsing completes.  To make generic, maybe the start and end tags could be configured.

I'm a developer, but not a WP developer.  I would be willing to write the code if you can help point me in the correct direction.

**Comment by terrylinooo** [comment]
This is the same issue with #19  and it will be added in 1.7.0

However, you can highlight your code with Code Highlight module, which supports kotin.
https://github.com/terrylinooo/githuber-md/wiki/HTML-Code-Language-for-Syntax-Highlighting
