### ISSUE TITLE
Markdown does not work in comment section ?

### ISSUE THREAD

**Issue by pbenefice** [terrylinooo/githuber-md#110]
**Describe the bug**

Markdown does not seems to work in comment section.

**To reproduce**

1. Go to WP Githuber MD settings
2. Go to the Markdown tab in the settings
3. Tick `Comments` to Enable Markdown for comments.
4. Edit a comment with some markdown (for example `**comment**`)
5. See the raw markdown in frontend.

**Expected behavior**

I would have expected the markdown to work in comment section. Instead I see the raw comment. (in my example, I see `**comment**`instead of **comment**)

**Screenshots**

<img width="415" alt="Capture d’écran 2019-08-13 à 16 03 19" src="https://user-images.githubusercontent.com/14271393/62948277-594e2f00-bde4-11e9-818d-9d981d06e41d.png">

**Server environment**

 - WordPress version 5.2.2
 - WP Githuber MD plugin version 1.11.7
 - PHP version 
PHP 7.1.30 (cli) (built: Jul 13 2019 00:28:52) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.30, Copyright (c) 1999-2018, by Zend Technologies

**User environment**

 - OS: Docker (https://hub.docker.com/_/wordpress)
 - Browser: firefox & chrome
 - I'm using the GeneratePress wordpress theme

**Comment by pbenefice** [comment]
I just saw this [comment](https://github.com/terrylinooo/githuber-md/issues/100#issuecomment-512877477) in another issue. I guess this answer my question 😅 

> Markdown for comments is not working for now. Thanks for your feedback.
I will make it work, perhaps in version 1.12.0

Do you have any idea when v1.12.0 might be available ?

In any case thanks for the work.

**Comment by dertuxmalwieder** [comment]
It's still not there.

**Comment by MuTsunTsai** [comment]
Really want to have Markdown for comments feature.

**Comment by biguenique** [comment]
We're now at version 1.16.0. Anyone aware whether Markdown support for comments has been implemented yet?

**Comment by dertuxmalwieder** [comment]
This is the most useless bot on GitHub.
