### ISSUE TITLE
makes string literal into <a> link when using RDP WIki Embed plugin

### ISSUE THREAD

**Issue by andrwj** [terrylinooo/githuber-md#111]
**Describe the bug**

This plugin converts literal string value into A tag.

eg.  
```
[rdp-wiki-embed url='https://en.wikipedia.org/wiki/JavaScript'] 
    ↳ [rdp-wiki-embed url='<a href="https://en.wikipedia.org/wiki/JavaScript">https://en.wikipedia.org/wiki/JavaScript</a>] 
```

**To reproduce**

1. Install & Activate RDP WIki Embed plugin and write a post that contains any page of Wikipedia
2. Save. 
3. Look for post_content field value in wp_posts table.
4. This plugin converted url formed string into A link.

**Expected behavior**

It should not touch any value in other plugin's property value.

**Screenshots**

**Server environment**

 - WordPress version 5.2.2
 - WP Githuber MD plugin version 1.11.7
 - PHP version 7.2

**User environment**

 - OS: macOS
 - Browser: Chrome

**Additional context**

**Comment by terrylinooo** [comment]
Hi...

After checking the RDP WIKI plugin's source code, I notice that it is rendered the page by JavaScript.
Therefore you can use the following the to make it work.

```
<div>
[rdp-wiki-embed url='https://en.wikipedia.org/wiki/JavaScript']
</div>
```
Because Githuber MD won't render any text that is inside HTML tags.
