### ISSUE TITLE
Markdown not working in attachment descriptions

### ISSUE THREAD

**Issue by morgannunan** [terrylinooo/githuber-md#112]
I see that when I install Githuber, I have a dropdown in my attachment edit screen that says 'HTML' and 'Markdown'. However, if I choose 'Markdown' and view it on the front end, it doesn't render the markdown into HTML.

Is there a filter I can apply in my template that will force markdown rendering?

It would also be great if Advanced Custom Fields took markdown, but maybe I could also apply a filter in the theme.

**Comment by terrylinooo** [comment]
Sorry, Githuber MD doesn't support attachment now.
I don't use it, so I won't make it complicated.
