### ISSUE TITLE
Set a post to be "sticky"

### ISSUE THREAD

**Issue by medmin** [terrylinooo/githuber-md#113]
**Any issue will be ignored if you don't provide the following detailed information.**

**Describe the bug**

**Is it possible to set a post to be "sticky" ? Just like the Gutenberg editor , we can easily click the checkbox "Stick to the top of the blog" in status and visibility .**

Thanks

**To reproduce**

**Expected behavior**

**Screenshots**

**Server environment**

 - WordPress version [ e.g. 5.0.1 ]
 - WP Githuber MD plugin version [ e.g. 1.9.0 ]
 - PHP version [ e.g. 5.3.6 ]

**User environment**

 - OS: [ e.g. Windows ]
 - Browser [ e.g. Chrome, Safari, Firebox ]

**Additional context**

**Comment by terrylinooo** [comment]
Hello. You might take a look at other plugins because your question is not related to Markdown.
