### ISSUE TITLE
代码块中的双引号在实际显示中被转义

### ISSUE THREAD

**Issue by sanjusss** [terrylinooo/githuber-md#114]
**問題**

代码块中的双引号在实际显示中被转义为`&quot;`

**如何重現**
代码中输入双引号
![image](https://user-images.githubusercontent.com/8220722/64218005-6c8b8080-cef2-11e9-989b-49383f51880f.png)

**預期的行為或結果**
在右侧预览窗口显示正常。  
![image](https://user-images.githubusercontent.com/8220722/64218020-8036e700-cef2-11e9-9c0e-fc5ef5ee1817.png)

**畫面截圖**
发布或点预览按钮，代码中的双引号被转义。原文中的双引号正常。  
![image](https://user-images.githubusercontent.com/8220722/64218039-9349b700-cef2-11e9-918e-9bbd22d242ed.png)

**伺服器環境**

 - WordPress 版本 5.2.2–zh_CN
 - WP Githuber MD 版本 1.11.8
 - PHP 版本 7.2.16
 - 其他使用插件一览
![image](https://user-images.githubusercontent.com/8220722/64218175-297ddd00-cef3-11e9-8e5c-3c812dd7d089.png)
![image](https://user-images.githubusercontent.com/8220722/64218184-339fdb80-cef3-11e9-89eb-8f3c170a89b4.png)

**用戶端環境**

 - 作業系統 Windows 10 企业版 1903
 - 瀏覽器 Chrome 76.0.3809.132

**Comment by terrylinooo** [comment]
試試這個

![image](https://user-images.githubusercontent.com/11989371/64219037-76af7e00-cef6-11e9-8bf5-3f1b486c6df4.png)

**Comment by sanjusss** [comment]
谢谢，已成功显示

**Comment by terrylinooo** [comment]
#89
