### ISSUE TITLE
Feature Request: Add option to select CPT for MarkDown

### ISSUE THREAD

**Issue by jpSimkins** [terrylinooo/githuber-md#12]
So far, I really like what I see here. 

One feature that is missing is an ability to use this on CPTs. Ideally, an option in the settings to select any of the CPTs that are available or even a hook/filter.

I am posting this before I go through the code but this is a pretty important feature that I think would help drastically with this plugin.

**Comment by terrylinooo** [comment]
Thanks for your commit.

I made some changes about your code like this:

![image](https://user-images.githubusercontent.com/11989371/52899781-d9764c00-3228-11e9-82a2-7aeca14de29a.png)

The plugin will be updated tomorrow.

**Comment by terrylinooo** [comment]
![image](https://user-images.githubusercontent.com/11989371/52909267-12fa9600-32c1-11e9-8eb8-5104bef61c20.png)

Supporting custom post types feature is done. It is added in version 1.6.0
