### ISSUE TITLE
vim输入模式

### ISSUE THREAD

**Issue by silverbulletmdc** [terrylinooo/githuber-md#123]
能否在editor中提供vim模式？

**Comment by terrylinooo** [comment]
具體描述一下您想要的情境有助於我判斷此功能可行性。

**Comment by silverbulletmdc** [comment]
就是在编辑markdown时支持使用vim的快捷键，如hjkl等。http://www.codemirror.net/ 是一个现成的js实现的网页编辑器，支持vim模式，很多软件通过codemirror插件实现了网页编辑器中的vim模式。比如 https://github.com/lambdalisue/jupyter-vim-binding

**Comment by terrylinooo** [comment]
ok. 我再看看

**Comment by silverbulletmdc** [comment]
感谢大佬
