### ISSUE TITLE
JavaScript string literals are not supported in code blocks

### ISSUE THREAD

**Issue by ColinKerr** [terrylinooo/githuber-md#124]
**Any issue will be ignored if you don't provide the following detailed information.**

**Describe the bug**
If you create a code block with js string literals the '`'s are not properly formatted in the output.
JS literals: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

Example code block:
```javascript
console.log(`1 and 1 make 2`);
```
Output code block:
console.log(<code>1 and 1 make 2</code>);

**To reproduce**

1. create a new post
2. create a new javascript code block
3. enter the line: console.log(`1 and 1 make 2`);
4. publish 

I have syntax highlighting by Prism.js enabled using coy theme.  I have tried turning on/off various other settings and the bug still happens.

**Expected behavior**

Ideally literal strings would be correctly formatted including special formatting for expressions in the strings (See functionality listed here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)

At minimum literal strings should be treated like regular strings.

**Screenshots**

Expected: 
![image](https://user-images.githubusercontent.com/33028649/66773144-66db7000-ee8c-11e9-839b-5b61962efca4.png)

Actual:
![image](https://user-images.githubusercontent.com/33028649/66773099-401d3980-ee8c-11e9-90ae-3aa08d32d028.png)

**Server environment**

 - WordPress version: 5.2.3
 - WP Githuber MD plugin version: 1.11.8 

**User environment**

 - OS: Windows
 - Browser: Firefox (also tested on Chrome)

**Comment by sanjusss** [comment]
I also encountered the same problem.

**Comment by terrylinooo** [comment]
I will take a look at it. If there is any update, I will mention you here.
