### ISSUE TITLE
Chrome and FireFox inbuilt dictionary and Grammarly feature for githuber-md

### ISSUE THREAD

**Issue by rameshsahoo111** [terrylinooo/githuber-md#125]
**Describe the bug**

It would really great if you include the following valuable features to make githuber-md editor a perfect wordpress editor. 

- Firefox and chrome inbuilt dictionary correction feature in the githuber-md editor
- Grammarly spell-check and correction feature in the githuber-md 

**To reproduce**

=> Install wordpress
=> Install githuber-md plugin and activate

1) Open site using firefox and chrome

2)  Create a new page or post 

3) Type something 

4) Right click on the incorrect work here you'll rowser in-built dictionary correction feature is disabled. 

5) Same applies for grammarly browser plugin 

**Screenshots**
N/A

**Server environment**
 - WordPress version  5.2.4 
 - WP Githuber MD plugin version 1.11.8
 - PHP version 7.3

**User environment**

 - OS:  Linux and wondows
 - Browser Chrome, Safari, Firebox

**Comment by rameshsahoo111** [comment]
Anybody working on this?

**Comment by terrylinooo** [comment]
Chrome spellcheck is not available because the Githuber MD Markdown editor is not pure Textarea elements so that I can not make it work.
Grammarly does not provide public APIs, the alternative is https://www.grammarbot.io/ but I have no time to integrate it.

**Comment by rameshsahoo111** [comment]
Thanks
