### ISSUE TITLE
建议增加新功能

### ISSUE THREAD

**Issue by 52duan** [terrylinooo/githuber-md#130]
**如果沒有提供以下詳細資訊，您開立的問題回報會被無視。**

**問題或臭蟲**

清楚的說明問題發生的情況及結果。

**如何重現**

請告知重現此問題的步驟回何：

1. 增添功能原因：
2. 因为有些文章用markdown，有些文章用默认编辑器
3. 所以增添的功能为：
4. 使用默认编辑器的时候有启用markdown按钮
5. 使用markdown编辑器的时候有关闭markdown按钮  

**預期的行為或結果**

清楚的說明您預期什麼樣的結果才是正常。

**畫面截圖**

1. 請提問題發生時的截圖
2. 例如按 F12，查看 Google Chome 開發人員工具的畫面有無紅色字樣錯誤訊息。

**伺服器環境**

 - WordPress 版本
 - WP Githuber MD 版本
 - PHP 版本

**用戶端環境**

 - 作業系統
 - 瀏覽器

**其它說明**

如果有的話，請提供。

**Comment by skyroam** [comment]
我好像写文章时不能切换到默认编辑器，应该怎么办呢？
