### ISSUE TITLE
Update-20191122 broke dashboard 

### ISSUE THREAD

**Issue by yKRSW** [terrylinooo/githuber-md#131]
**Any issue will be ignored if you don't provide the following detailed information.**

**Describe the bug**

Today I updated this plugin.
Then dashboard shows menu only.
Even if I click any menu, nothing is shown.

Once I remove plugin by FTP, dashboard recovered.

**Screenshots**

![WP-broken-dashboard_01](https://user-images.githubusercontent.com/50257351/69434443-fbd16300-0d80-11ea-95c2-13608390b8ae.png)

**Server environment**

 - WordPress version [ 5.3 ]
 - WP Githuber MD plugin version [ 1.12.0 ]
 - PHP version [ 7.1.28 ]

**User environment**

 - OS: [ Windows ]
 - Browser [ Chrome ]

**Additional context**

**Comment by terrylinooo** [comment]
I have tested on my own sites and they are fine.

Do you any error in Chrome developer console?

**Comment by yKRSW** [comment]
I installed again. Now it is fine. 
So it may be just a update failure.
Sorry to disturb ...

**Comment by terrylinooo** [comment]
I just updated and make a bit modification, could you try again?

**Comment by yKRSW** [comment]
I removed and installed again.
Dashboard is is fine.
Thanks.

![WP-broken-dashboard_02](https://user-images.githubusercontent.com/50257351/69476934-6804a300-0e23-11ea-8e35-0d71628672ac.png)
