### ISSUE TITLE
通过图片随贴上传到文章中的图片如何添加水印

### ISSUE THREAD

**Issue by somta** [terrylinooo/githuber-md#133]
试过很多插件，媒体库中的图片能够正常添加水印，但是直接在编辑器中复制粘贴上传的图片无法添加水印，请问有什么办法或插件可以做到？

**Comment by terrylinooo** [comment]
指定存放至媒體庫應該能透過其它水印 plugin 來添加。不過實際情況要看該 plugin 在那一個階段產生圖片，這方面 WP Githuber MD 不處理第三方做的事。
