### ISSUE TITLE
代码块中的双引号在实际显示中被转义

### ISSUE THREAD

**Issue by playNoA** [terrylinooo/githuber-md#137]
今天新装了这个编辑器，体验很好，但有个地方我发现了异常，我不确定这是哪里导致的；

正常的效果
![image](https://user-images.githubusercontent.com/7344597/71768996-87c8d400-2f56-11ea-8d1a-2f5b89ea00b9.png)

异常的效果
![image](https://user-images.githubusercontent.com/7344597/71769000-931bff80-2f56-11ea-9b3e-ce683e80088f.png)

在点击文章更新按钮后，就变成这个样子，刚刚粘贴进去的时候预览是没问题的；
文章中其他的大括号和中括号显示都没问题
![image](https://user-images.githubusercontent.com/7344597/71769013-c2327100-2f56-11ea-9694-f0c164e2c390.png)

我只能手动添加个转义符来让它不变异
![image](https://user-images.githubusercontent.com/7344597/71769027-d70f0480-2f56-11ea-8968-f9b51a8c87bb.png)

已经开启了Decode Code Blocks按钮；

另外，就是内容纲要并没有使用h1标签来汇总
![image](https://user-images.githubusercontent.com/7344597/71769141-1b4ed480-2f58-11ea-92a5-b99ecf192468.png)

![image](https://user-images.githubusercontent.com/7344597/71769164-6b2d9b80-2f58-11ea-8929-5a340e65a6bd.png)

![image](https://user-images.githubusercontent.com/7344597/71769185-ae880a00-2f58-11ea-9432-ce19ca1249d5.png)

OS：win10
Chrome：
Google Chrome 已是最新版本
版本 79.0.3945.88（正式版本） （64 位）

希望作者抽空搂一眼

**Comment by terrylinooo** [comment]
https://github.com/terrylinooo/githuber-md/issues/114

希望有解決您的問題

**Comment by playNoA** [comment]
@terrylinooo 我在发帖前已经看了这两篇帖子，而且已经开启了Decode Code Blocks按钮的情况下；那么，还有别的路子吗？
