### ISSUE TITLE
Code block syntax highlighting causes page to hang

### ISSUE THREAD

**Issue by JBlack93** [terrylinooo/githuber-md#140]
**Any issue will be ignored if you don't provide the following detailed information.**

**Describe the bug**
Code block markdown causes page which it is rendered on to hang if an unknown [syntax highlighting](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting) is used for the fenced code block.

**To reproduce**

1. Create a code block on any `WordPress` page with a syntax highlighting which is unknown. eg, the typo:

> 
> \``` basxdh
> #!/bin/bash
> foo=bar
> \```
> 

2. Load page on which this markdown is rendered.

**Expected behavior**

Page will hang. It will constantly be "transferring data" to the host.

**Screenshots**

**Server environment**

 - WordPress version [ 5.3.2 ]
 - WP Githuber MD plugin version [ 1.12.1 ]
 - PHP version [ 7.0.33 ]

**User environment**

 - OS: [ Fedora31 ]
 - Browser [ Firefox ]

**Additional context**

**Comment by terrylinooo** [comment]
Thanks for reporting. I will look at this problem and fix it soon.
