### ISSUE TITLE
反引号 ` 被转义成<code></code>

### ISSUE THREAD

**Issue by yqchilde** [terrylinooo/githuber-md#141]
**如果沒有提供以下詳細資訊，您開立的問題回報會被無視。**

**問題或臭蟲**

反引号 ` 被转义成<code></code>

**如何重現**

請告知重現此問題的步驟回何：

1. \`json:"id"\`

**預期的行為或結果**

正确结果是   \`json:"id"\`
目前结果是   \<code>json:"id"\</code>

**畫面截圖**

![image](https://user-images.githubusercontent.com/36953759/74014325-5d40bf80-49c9-11ea-9d4d-804ae656b273.png)

**伺服器環境**

 - WordPress 版本 5.3.2
 - WP Githuber MD 版本 1.12.1
 - PHP 版本 7.3

**用戶端環境**

 - 作業系統 windows
 - 瀏覽器 chrome浏览器

**其它說明**

如果有的話，請提供。

**Comment by terrylinooo** [comment]
該反引号在 Markdown 語法是 code 的意思。必須夾在代碼區塊才不會轉義
