### ISSUE TITLE
无法使用粘贴图片至 sm.ms 图床功能

### ISSUE THREAD

**Issue by BillChen2000** [terrylinooo/githuber-md#143]
**如果沒有提供以下詳細資訊，您開立的問題回報會被無視。**

**問題或臭蟲**

在设置内如果将上传地设置为「默认」，则可以顺利地将图片粘贴进文章；设置成上传到 sm.ms 图床，则无法成功粘贴图片，会一直提示用 `![Uploading file...]()` 代替。

**如何重現**

請告知重現此問題的步驟回何：

1.在设置的 Module 中启用 Image Paste
2.将存储空间设置为 sm.ms
3.在书写界面粘贴图片
4.无法上传

**預期的行為或結果**

等待一小段时间后应该 `![Uploading file...]()` 应该变成上传后的网址。

**畫面截圖**

![image](https://user-images.githubusercontent.com/11037722/75269745-596bc480-5834-11ea-9a9a-7a32d8593c4b.png)

**伺服器環境**

 - WordPress 5.3.2
 - WP Githuber MD 版本 1.12.1
 - PHP 版本 7.2.19

**用戶端環境**

 - 作業系統 macOS 10.15
 - 瀏覽器 Chrome 80.0

**其它說明**

开启或不开启代理软件均会复现。

**Comment by terrylinooo** [comment]
謝謝回報。是否 sm.ms 改變 api 串接規格我再查看看。
