### ISSUE TITLE
content update via the Wordpress API does not appear in the MD editor

### ISSUE THREAD

**Issue by mvanholsteijn** [terrylinooo/githuber-md#146]
**Describe the bug**

When I update the content via the Wordpress API, the changes are not visible in the MD editor.

**To reproduce**

1. create a blog with the MD editor
2. update the blog via the rest api:
```
curl --user <user>:<app pssword> -X PATCH https://<yourwp>/wp-json/wp/v2/posts/<post-id> -d 
'{"content": "<h1>see this update</h1>"}' -H 'content-type: application/json'

3. check the blog via de MD editors -> no change
4. disable the MD editor -> voila!

**Expected behavior**

content updates via the wordpress api are reflected in the post.

**Screenshots**


**Server environment**

 - WordPress version [ e.g. 5.2.2 ]
 - WP Githuber MD plugin version [ e.g. 1.12.1 ]

**User environment**

 - OS:  MacOS
 - Browser: Chrome

**Additional context**
none

**Comment by terrylinooo** [comment]
Currently, Githuber MD does not handle the content changes through WordPress API. I might have time to do some research about this in next week, so please wait for my further replying.

**Comment by sbeaumont** [comment]
Hi Terry,

I'm using the Wordpress API to bulk update a reference site with Markdown pages. However, when I create or update a page your plugin does not seem to be triggered. When I view the page after creating or updating with the API I see raw Markdown, when I then press the update button for that page in the page your plugin gets triggered and everything shows correctly. This seems to be similar to what @mvanholsteijn is seeing.

This would be solved if an API update would trigger your plugin, but I'm fine with triggering your plugin muyself whenever I create or update a page. Is there a way for you to either ensure the plugin gets triggered, or provide a way to trigger it?

**Comment by sbeaumont** [comment]
Here is a Python 3 script that reproduces the issue: it also uses the requests library.

`import requests
from pprint import pprint

BASE_URL = 'https://<your server>.com/wp-json/wp/v2/'
CREDENTIALS = ('username', '(application) password')


class LibraryUpdater(object):
    def __init__(self, base_url, auth):
        self.base_url = base_url
        self.s = requests.Session()
        self.s.auth = auth
        self.s.headers = {'User-agent': 'Mozilla/5.0'}
        self._pages = None

    def cmd(self, command):
        return self.base_url + command

    @property
    def all_pages(self):
        """Lazily retrieves all pages so this script can determine if a page is to be created or updated."""
        if not self._pages:
            self._pages = dict()
            response = self.s.get(self.cmd('pages'), params={'_fields': 'id,title,slug,generated_slug'})
            self._pages.update(
                {p['title']['rendered']: {'id': p['id'], 'slug': p['slug'] if p['slug'] else p['generated_slug']} for p
                 in response.json()})
            total_pages = int(response.headers['X-WP-TotalPages'])
            for i in range(1, total_pages + 1):
                response = self.s.get(self.cmd('pages'), params={'_fields': 'id,title,slug,generated_slug', 'page': str(i)})
                self._pages.update({p['title']['rendered']: {'id': p['id'], 'slug': p['slug'] if p['slug'] else p['generated_slug']} for p in response.json()})
        return self._pages

    def find_page(self, name: str):
        return self.all_pages.get(name, None)

    def load_page(self, name: str):
        page_id = self.all_pages[name]['id']
        response = self.s.get(self.cmd(f'pages/{page_id}'), params={'context': 'edit'})
        return response.json()

    def create_or_update(self, title, contents):
        """Creates a page if the a page with that title does not exist, otherwise updates the contents of the existing page."""
        page = self.find_page(title)
        if page:
            url = self.cmd(f"pages/{page['id']}")
            print("Updating", url)
        else:
            url = self.cmd(f"pages")
            print("Creating page", title)
        response = self.s.post(url, params={
            'title': title,
            'status': 'publish',
            'context': 'edit',
            'content': contents})
        return response.json()


if __name__ == '__main__':
    lu = LibraryUpdater(BASE_URL, CREDENTIALS)
    page_title = 'Test Page'
    page_contents = '# Hello\n[[Other Page|alias]]\n[[Yet Another Page]]'
    lu.create_or_update(page_title, page_contents)

    # Uncommenting and running this after the MD plugin has initially rendered the page results
    # in no change being seen in the MD editor: the filtered_post_content and post_content don't get updated.
    # page_contents = '# Changed the contents'
    # lu.create_or_update(page_title, page_contents)

    print("Loading", page_title)
    pprint(lu.load_page(page_title))
`

**Comment by huangapple** [comment]
Has it not been resolved yet? Can you provide a clear answer, will it still be handled, and how long will it take?
