### ISSUE TITLE
Some editor themes do not load

### ISSUE THREAD

**Issue by alpipego** [terrylinooo/githuber-md#147]
**Describe the bug**

Some editor themes do not load (e.g. Material, Panda Syntax).

**To reproduce**

1. Go to Settings – WP Githuber MD
2. Scroll down to "Markdwon Editor"
3. Choose theme `material` (or `panda syntax`) from the select in "Editing Area"
4. Open a edit post screen with WP Githuber MD enabled

**Expected behavior**

Changed editor color scheme to the above selected. It's a plain white editor.

**Server environment**

 - WordPress version 5.2.3
 - WP Githuber MD plugin version 1.12.1
 - PHP version 7.4.2

**User environment**

 - OS: Linux
 - Browser Firefox 73.0.1

**Comment by terrylinooo** [comment]
Thanks for your feedback. I'll look into this issue.
