### ISSUE TITLE
iframes get escaped

### ISSUE THREAD

**Issue by alpipego** [terrylinooo/githuber-md#148]
**Describe the bug**

Any iframes I paste into the editor get escaped in the output. This is not a problem when WP Githuber MD is not used on a post type (either by disabling it for the post type, or using the Markdown toggle).

**To reproduce**

Paste this content

```
<iframe style="width:100%"; width="560" height="380" src="https://coronavirus.app/map?embed=true" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
```

into the markdown editor, the preview will render fine but the HTML tags are escaped in the output.

**Expected behavior**

I expected HTML elements not to be escaped. I also explicitly added `iframe` to `wp_kses_allowed_html` but that did not have the desired effect.

**Server environment**

 - WordPress version 5.3.2
 - WP Githuber MD plugin version 1.12.2
 - PHP version 7.4.3

**User environment**

 - OS: Arch Linux
 - Browser any

**Comment by DillK** [comment]
@alpipego 

You have a misplaced semi-colon.

`<iframe style="width:100%;"` fixes it.

**Comment by alpipego** [comment]
Oh man. Thanks for that. I copied the code from their website and never bothered to check the markup for errors.
