### ISSUE TITLE
偏好設定：鏈接打開方式，在新窗口打開無效

### ISSUE THREAD

**Issue by lizibin** [terrylinooo/githuber-md#149]
1. 設置偏好設定：鏈接打開方式，在新窗口打開
2. 文章裡面新增鏈接，發佈文章
3. 在文章打開鏈接依然是在同一视窗开启 (默认)

**伺服器環境**

 - WordPress 版本 5.3.2
 - WP Githuber MD 版本 1.12.2
 - PHP 版本   7.6

**用戶端環境**

 - 作業系統  win10
 - 瀏覽器  chrom

**Comment by terrylinooo** [comment]
Fixed in 1.14.0
