### ISSUE TITLE
Need to be able to set width of  code block

### ISSUE THREAD

**Issue by HowardEdidin** [terrylinooo/githuber-md#150]
I write my post in an external editor and use Weblog publishing to create the post on my blog.
The issue is that there are descriptions in the code that can be longer than 100 characters.  They wrap in this editor.
Your editor does not wrap.  I need to be able to set the width of the block.

**Comment by terrylinooo** [comment]
Hello. Adding some customized CSS code in your theme cusoumizer to fit your needs.

**Comment by HowardEdidin** [comment]
Terry,

Could you please give me an example? I am strictly IoT and Big Data.


Thank you,

Howard S. Edidin MCTS, MCP, Author, Trainer
Cloud Solutuion Architect

[A close up of a sign  Description automatically generated][A close up of a sign  Description automatically generated]

Microsoft Data Platform MVP
Microsoft Partner Cloud Solution Architect
Microsoft HL7 FHIR Virtual Team
Microsoft Azure Advisory Group

hedidin@edidingroup.com<mailto:hedidin@edidingroup.com>
224-360-3200

_________________________________________________________________________
Disclaimer: This email and any attachments are sent in strictest confidence for the sole use of the addressee and may contain legally privileged, confidential, and proprietary data. If you are not the intended recipient, please advise the sender by replying promptly to this email and then delete and destroy this email and any attachments without any further use, copying or forwarding.




On 3/24/20, 8:26 PM, "Terry L." <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello. Adding some customized CSS code in your theme cusoumizer to fit your needs.

**Comment by terrylinooo** [comment]
Add this code into your `Theme Customizer -> Additional CSS`.

```css
.post pre {
	white-space: pre-wrap;
	overflow: hidden;
	word-break: break-all;
	word-wrap: break-word;
}
.post pre code {
	white-space: pre-wrap;
}
```

![image](https://user-images.githubusercontent.com/11989371/77502606-45000380-6e96-11ea-9a60-2c19ea1c9bce.png)

**Comment by HowardEdidin** [comment]
Thank you
