### ISSUE TITLE
Is it possible to use markdown in excerpts?

### ISSUE THREAD

**Issue by Ciges** [terrylinooo/githuber-md#151]
**Any issue will be ignored if you don't provide the following detailed information.**

**Describe the bug**

I use excerpts for my posts. Is it possible to use markdown also in excerpts?

Would it be difficult to add it by code?

**Comment by terrylinooo** [comment]
It is possbile to achieve but once you disable plugin, users will only see Markdown text on your website. It is not considered to be a useful feature.

**Comment by Ciges** [comment]
Ummm ..... It's for my blog http://tech.ciges.net, and I will not disable the plugin. Where could I see the code to add?

Thanks!
