### ISSUE TITLE
Syntax highlight: admin area menu outdated

### ISSUE THREAD

**Issue by noraj** [terrylinooo/githuber-md#153]
**Describe the bug**

The highlight lib (prism.js and highlight.js) themes/styles were updated but not the input menu in the admin area.

highlight lib

- Prism.js:
  - https://github.com/terrylinooo/githuber-md/tree/master/assets/vendor/prism/themes
    ![image](https://user-images.githubusercontent.com/16578570/77563387-8063f780-6ec1-11ea-825d-1f14c5995763.png)
  - https://github.com/terrylinooo/githuber-md/blob/master/src/Controllers/Setting.php#L503
    ![image](https://user-images.githubusercontent.com/16578570/77563764-fc5e3f80-6ec1-11ea-8b6f-b2caab48a926.png)
- Highlight.js:
  - https://github.com/terrylinooo/githuber-md/tree/master/assets/vendor/highlight.js/styles
    ![image](https://user-images.githubusercontent.com/16578570/77563441-9376c780-6ec1-11ea-8781-16e6286548f8.png)
  - https://github.com/terrylinooo/githuber-md/blob/master/src/Controllers/Setting.php#L572
    ![image](https://user-images.githubusercontent.com/16578570/77563596-c28d3900-6ec1-11ea-8c32-f2c7fe026bd8.png)

**To reproduce**

N/A

**Expected behavior**

The menu is updated accordingly to the assets.

**Screenshots**

See above.

**Server environment**

 - WordPress version 5.31
 - WP Githuber MD plugin version1.12.2
 - PHP version 7.4

**User environment**

 - OS: openSUSE Leap 15.1
 - Browser FF

**Comment by terrylinooo** [comment]
Will be fixed in 1.14.0
