### ISSUE TITLE
Source code formatting issue

### ISSUE THREAD

**Issue by HowardEdidin** [terrylinooo/githuber-md#154]
**Any issue will be ignored if you don't provide the following detailed information.**

**Describe the bug**
My code is formatted correctly in the editor view
But when seen in the browser, (see attached images) it is cut off

My source code is displayed correctly in the  Editor but is cut off when viewed using Edge and Chrome Browsers 

**To reproduce**

1. Go to 'Editor and paste in code 
2. Click on Use the code formatter on the toolbar
3. Publish post
4. View post in Browser
5. View the code block

**Expected behavior**
I should see the code formatted exactly as shown in the Editor Preview

**Screenshots**
![editor](https://user-images.githubusercontent.com/19954905/77658335-8d75fa80-6f44-11ea-9902-9bb802294ebf.png)
![issue](https://user-images.githubusercontent.com/19954905/77658338-8d75fa80-6f44-11ea-9d1b-c5b3d9c69dff.png)

**Server environment**

 - WordPress version 5.3.2
 - WP Githuber MD plugin version 1.12.2
 - PHP version .2.28-3+ubuntu18.04.1+deb.sury.org+1

**User environment**

 - OS: Mac Catalina
 - Browser Chrome

**Additional context**

**Comment by HowardEdidin** [comment]
I added the CSS you provided but it did not seem to work

**Comment by terrylinooo** [comment]
Please provide the text here so that I can test it on my side.
