### ISSUE TITLE
Line break at each newline

### ISSUE THREAD

**Issue by noraj** [terrylinooo/githuber-md#155]
**Describe the bug**

In markdown adding a newline (\n) should not create a line break (`<br>`) ([original reference syntax](https://daringfireball.net/projects/markdown/syntax#p), in CommonMark [Paragraphs](https://spec.commonmark.org/0.29/#paragraphs), [Blank lines](https://spec.commonmark.org/0.29/#blank-lines), [Hard Line Break](https://spec.commonmark.org/0.29/#hard-line-breaks)).

But some permissive parser like GFM (GitHub Flavored Markdown) introduced new features (eg. tables) and changed some behavior (optionally but by default add a lien break at each new line).

I don't know which Markdown parser WP Githuber MD is using bet teh name of the app let me think it is a GFM parser, so neither enforcing the original syntax or GFM and so is producing hawful breaks everywhere:

![image](https://user-images.githubusercontent.com/16578570/77675590-6abc0400-6f8d-11ea-96c8-589db460a3e6.png)

If it was only me I would switch to a CommonMark compliant parser or adding a adding support for several parser so the user can switch.

But if it is to much work a workaround can be to add an option in the Admin UI to disable this behavior.

**To reproduce**

N.A.

**Expected behavior**

**Screenshots**

See above.

**Server environment**

 - WordPress version 5.31
 - WP Githuber MD plugin version1.12.2
 - PHP version 7.4

**User environment**

 - OS: openSUSE Leap 15.1
 - Browser FF

**Comment by terrylinooo** [comment]
![image](https://user-images.githubusercontent.com/11989371/79347540-62d8f980-7f66-11ea-80b0-b0454b1e8095.png)

I don't see any `<br>` .
![image](https://user-images.githubusercontent.com/11989371/79347382-39b86900-7f66-11ea-87eb-cf8245081a7c.png)

![image](https://user-images.githubusercontent.com/11989371/79347468-4f2d9300-7f66-11ea-8cca-ec122fd7cc2a.png)
