### ISSUE TITLE
Highlight problem

### ISSUE THREAD

**Issue by WangXurun** [terrylinooo/githuber-md#156]
**Describe the bug**

I use prism.js to highlight my code , but it seems that the hightlight function isn't working. I'm sure that I've updated my post. 

**Expected behavior**

I think the highlight should be like this.
![image](https://user-images.githubusercontent.com/44117710/77838624-5738b500-71a8-11ea-9240-b711f081bc6e.png)

but it turns out to be like this 

![image](https://user-images.githubusercontent.com/44117710/77838641-7d5e5500-71a8-11ea-981f-a407e711d384.png)

but when I add a flow chart behiend

![image](https://user-images.githubusercontent.com/44117710/77838696-ce6e4900-71a8-11ea-8ab2-6acc71e7ee4c.png)

the hightlight works well !!!??

![image](https://user-images.githubusercontent.com/44117710/77838715-f3fb5280-71a8-11ea-9520-fbd2cbac580d.png)

but if the flow if empty…

![image](https://user-images.githubusercontent.com/44117710/77838792-9a475800-71a9-11ea-99a1-72c4b703c64d.png)

the post won't show the line number.

![image](https://user-images.githubusercontent.com/44117710/77838803-af23eb80-71a9-11ea-9cd8-4c3b72d57f8e.png)

**Server environment**

 - WordPress version [ 5.3.2 ]
 - WP Githuber MD plugin version [ 1.12.2 ]
 - PHP version [ 7.3.16 ]

**User environment**

 - OS: [ widows ]
 - Browser [ Chrome]

Hope I express myself clearly.

**Comment by StevenFinch** [comment]
same problem

**Comment by StevenFinch** [comment]
I met the same problem like you. 
I opened the button of prism.js like this and it works normally.
![批注 2020-04-02 105205](https://user-images.githubusercontent.com/47233927/78205923-04c10680-74d0-11ea-957b-87886722c4b0.jpg)

**Comment by WangXurun** [comment]
> I met the same problem like you.
> I opened the button of prism.js like this and it works normally.
> ![批注 2020-04-02 105205](https://user-images.githubusercontent.com/47233927/78205923-04c10680-74d0-11ea-957b-87886722c4b0.jpg)

thank you for your reply, but the button was on when I did all those operations...

**Comment by terrylinooo** [comment]
I have tested it again and it works well as expected.

![image](https://user-images.githubusercontent.com/11989371/79343448-fc051180-7f60-11ea-930b-a57077eba435.png)

Make sure you have turned on this option as the following screenshot.
![image](https://user-images.githubusercontent.com/11989371/79343528-1343ff00-7f61-11ea-8b67-1ace89cd4bf1.png)

**Comment by jakeuj** [comment]
我也有一樣的問題，有php這段時正常，拿掉php則整篇不會有語法高亮

```php
function sayHello() {
	return 'Hello! World.';
}

echo sayHello();
```

```csharp
using System.IO.Compression;

namespace MyApplication
{
    [Obsolete("...")]
    class Program : IInterface
    {
        public static List<int> JustDoIt(int count)
        {
            Span<int> numbers = stackalloc int[length];
            Console.WriteLine($"Hello {Name}!");
            return new List<int>(new int[] { 1, 2, 3 })
        }
    }
}
```

是不是有針對特定語言去做處理導致特定(ex:php,flow)語言
才會觸發 Highlight.js

**Comment by jakeuj** [comment]
[Highlight.php](https://github.com/terrylinooo/githuber-md/blob/master/src/Modules/Highlight.php#L58)
Most follow this list, change `C` to lower case `c`.
