### ISSUE TITLE
"Markdown Editor 切换器"失效

### ISSUE THREAD

**Issue by vaecoffee** [terrylinooo/githuber-md#158]
我的wordpress版本是5.4，使用旧的富文本编辑器；
插件中启用“Markdown Editor 切换器”后，发现编辑器中不显示切换按钮，切换不了富文本编辑器。
这是bug吗？
谢谢！

**Comment by terrylinooo** [comment]
該按紐是判斷用戶是否使用區塊編輯器才出現，因為區塊編輯器是 WordPress 5 的主流及預設。您提的問題我再評估一下要不要加入。畢竟用戶基數少，3000 安裝是小眾。您的情況又是更小眾了。

**Comment by vaecoffee** [comment]
好的，谢谢！
