### ISSUE TITLE
圖片隨貼功能啟用後，貼上的圖片資訊並沒有同步到資料庫中。

### ISSUE THREAD

**Issue by dnowba** [terrylinooo/githuber-md#16]
可以貼上，圖片也儲存在預設的目錄中，但是並沒有同步到資料庫。也就是說，在使用媒體庫管理圖片時，不會看到這些用隨貼功能貼上的圖片。

**Comment by terrylinooo** [comment]
隨貼的用意是加快寫作速度的，通常是操作截圖。在這個空間不值錢的時代，時間遠遠比空間珍貴。所以並不處理那些圖片，都是是雜湊值當檔名。真的需要認真管理的圖片再用 WordPress 的媒體庫。

**Comment by terrylinooo** [comment]
下一版預設支持這個功能。
