### ISSUE TITLE
option for katex delimeters

### ISSUE THREAD

**Issue by LadderOperator** [terrylinooo/githuber-md#160]
I really love this awesome plugin, especially for its support for katex. But you know, in most of  famous MD editors (Typora, etc.), the katex (or MathJax) delimeters are usually  `$...$`(inline) and 

```
$$
...
$$
```
(block).

for Typora,

**source:**
![image](https://user-images.githubusercontent.com/34033754/78754297-d51b6e00-79a9-11ea-8f20-a41a93c7a218.png)

**preview:**
![image](https://user-images.githubusercontent.com/34033754/78754374-f1b7a600-79a9-11ea-9618-140fa12e076f.png)

However, in WP Githuber MD they are <code>\`$$......$$\`</code> and

<pre>
```katex
......
```
</pre>

Could the option be added? I think it would be great for immigrating articles written in MD with lots of MathJax equations to wordpress blog if the feature was considered....

**Comment by terrylinooo** [comment]
Hello.

`$..$` is for MathJax.

MathJax will come in 1.7.0 tomorrow.

**Comment by LadderOperator** [comment]
> Hello.
> 
> `$..$` is for MathJax.
> 
> MathJax will come in 1.7.0 tomorrow.

Thanks for your reply. It helps me a lot :+1:

**Comment by xalanq** [comment]
Please support KaTeX too.

**Comment by xalanq** [comment]
If you could support the delimiters (Compatible with typora)

(inline) `$ $`
 
and (block) 

```
$$

$$
```

 instead of

`` `$ $` ``

and 

````
```katex

```
````

It would be very nice !

**Comment by LadderOperator** [comment]
> > Hello.
> > `$..$` is for MathJax.
> > MathJax will come in 1.13.0 tomorrow.
> 
> Thanks for your reply. It helps me a lot 👍

Sadly when I updated the plugin to 1.13.0 I found it didn't work as what I expected...
So I have same thoughts with @xalanq  now.

**Comment by xalanq** [comment]
> > > Hello.
> > > `$..$` is for MathJax.
> > > MathJax will come in 1.13.0 tomorrow.
> > 
> > 
> > Thanks for your reply. It helps me a lot 👍
> 
> Sadly when I updated the plugin to 1.13.0 I found it didn't work as what I expected...
> So I have same thoughts with @xalanq now.

can you reopen this issue?
