### ISSUE TITLE
Is it possible to have the post ONLY in markdown, without preview?

### ISSUE THREAD

**Issue by Ciges** [terrylinooo/githuber-md#162]
**Describe the bug**

Hi. I would like to have the preview off by default. Is it possible?

**Comment by terrylinooo** [comment]
![image](https://user-images.githubusercontent.com/11989371/78974294-43943380-7b44-11ea-8a1e-b8e8d94d1887.png)

**Comment by Ciges** [comment]
Thanks a lot. Sorry for not seeing it, it was clear and easy :-|
