### ISSUE TITLE
"\neq" of katex not displayed correctly

### ISSUE THREAD

**Issue by ruanluyu** [terrylinooo/githuber-md#163]
**Describe the bug**

Everything of the Katex worked perfectly, but `$$ \neq $$` not displayed correctly in my site...
My site: https://world.milai.tech/study/jp-math/gsmsut-h31a-2.html
Where it happens: The last sentence of my article. 

**To reproduce**

Maybe just type the `$$ \neq $$`. 
There would be a symbol like "/=" not "≠"

**Expected behavior**

There should be "≠"

**Screenshots**

![image](https://user-images.githubusercontent.com/17758186/79013449-b7195d80-7ba3-11ea-95d4-ae369106545e.png)

![image](https://user-images.githubusercontent.com/17758186/79013474-cac4c400-7ba3-11ea-8a57-28f334e533ba.png)

**Server environment**

 - WordPress version [ 5.4 ]
 - WP Githuber MD plugin version [ 1.12.2 ]
 - PHP version [ ??? ]

**User environment**

 - OS: [ Windows ]
 - Browser [ Chrome ]

**Additional context**

None

**Comment by terrylinooo** [comment]
It will be fixed in 1.14.0
