### ISSUE TITLE
C#的MD，解析出来的html会删掉泛型标签及其内容

### ISSUE THREAD

**Issue by Boogaloo-XT** [terrylinooo/githuber-md#164]
**Any issue will be ignored if you don't provide the following detailed information.**

**Describe the bug**

**To reproduce**

1.编辑文章中的MD内容时，右侧即时解析的显示的正常，但发布后会删掉其中<string>的内容。下面是文章中的MD内容：
```csharp
public void Intersection()
{
    List<string> list1 = new List<string> { "AA", "BB", "CC", "EE", "GG" };
    List<string> list2 = new List<string> { "BB", "DD", "GG", "MM" };
    List<string> list3 = new List<string>();
    list3 = list1.Intersect(list2).ToList();       
    foreach (var s in list3)      // 各个值
    {
        Console.Write(s);
        Console.WriteLine();
    }
}
```
2.下面是发布后显示的内容，可以看到<string>没了
public void Intersection()
{
    List list1 = new List { "AA", "BB", "CC", "EE", "GG" };
    List list2 = new List { "BB", "DD", "GG", "MM" };
    List list3 = new List();
    list3 = list1.Intersect(list2).ToList();       
    foreach (var s in list3)      // 各个值
    {
        Console.Write(s);
        Console.WriteLine();
    }
}

**Expected behavior**

**Screenshots**

**Server environment**

 - WordPress version [ e.g. 5.3 ]
 - WP Githuber MD plugin version [ 1.12.2 ]
 - PHP version [ 7.3 ]

**User environment**

 - OS: [  Windows 10]
 - Browser [ Chrome ]

**Additional context**

**Comment by terrylinooo** [comment]
測試沒問題

![image](https://user-images.githubusercontent.com/11989371/79331001-0fa67d00-7f4d-11ea-9a5a-ba4faa7efeeb.png)

![image](https://user-images.githubusercontent.com/11989371/79331042-2220b680-7f4d-11ea-8f72-a58cd9be9918.png)

您該不會是沒放在 code block 中?

**Comment by su9257** [comment]
我也遇到了同样的问题，在预览阶段是正常的，但是发布后整个页面都错乱了。
![image](https://user-images.githubusercontent.com/20715825/103398953-cbf6b080-4b79-11eb-9f7e-79fe7abe20a1.png)

![image](https://user-images.githubusercontent.com/20715825/103399094-6656f400-4b7a-11eb-8f6e-8a0b2fcf9b99.png)

这是我的网页地址：https://aihailan.com/3-4%e8%ae%be%e8%ae%a1%e6%a8%a1%e5%bc%8f%e4%b9%8b%e8%bf%ad%e4%bb%a3%e5%99%a8%e6%a8%a1%e5%bc%8f%ef%bc%88iterator%ef%bc%89/

期待你的回复
