### ISSUE TITLE
关于mathjax和katex公式输入的问题

### ISSUE THREAD

**Issue by simplehx** [terrylinooo/githuber-md#168]
WordPress版本： 5.4.1
主题：WordStar
WP Githuber MD版本：1.15.0

# mathjax问题：
* 使用```mathjax```这种代码块，公式显示正常。
* 使用行内公式：
![image](https://user-images.githubusercontent.com/12119381/80910164-38f24600-8d60-11ea-8edb-af68cbf8fe0b.png)
则输出的不是行内公式，出现了换行
![image](https://user-images.githubusercontent.com/12119381/80910175-490a2580-8d60-11ea-98f7-0d10e1db4f9b.png)

# Katex问题：
* 使用```katex```这种代码块，公式显示带有灰色底色。
![image](https://user-images.githubusercontent.com/12119381/80910291-d8173d80-8d60-11ea-8166-b65083f0c7da.png)
* 行内公式正常

### Thanks for your work!

**Comment by AllFunThing** [comment]
I also encountered the some like problem with inline math.

![cap_img_007](https://user-images.githubusercontent.com/50653394/81325670-accf7e00-90d3-11ea-99cd-48096f7a7473.png)

1. katex inline math graphic is drawn in markdown editor page. 
2. text color changed
3. mathjax inline math graphic is not drawn in markdown render page

and, when browsing web page~

![cap_img_008](https://user-images.githubusercontent.com/50653394/81325970-151e5f80-90d4-11ea-8d3d-9a870723d6a4.png)

1. katex inline math graphic is not drawn
2. mathjax inline math graphic is not "inline"

thx!! :)

**Comment by chenjiefeng2001** [comment]
It not support the segmented function format.
