### ISSUE TITLE
代码行数以及复制失败！

### ISSUE THREAD

**Issue by emperinter** [terrylinooo/githuber-md#169]
**如果沒有提供以下詳細資訊，您開立的問題回報會被無視。**

**問題或臭蟲**

自己网站的代码行数以及复制选项都失败！

**如何重現**

請告知重現此問題的步驟回何：

1. 自己更新了wordpress和这个插件为最新版本！
2.刚开始以为是缓存的问题，把缓存清除依旧如此；
3.自己新添加了其它插件（IMGspider以及WebP Express）难道有冲突？

**預期的行為或結果**

更新后以往能实现的上述功能都失效了！

**畫面截圖**

- 自己目前只有平板，不好操作。可以去我博客看：[https://www.emperinter.info/2019/08/28/tensorflow-gpu%e7%89%88%e6%b5%8b%e8%af%95%e4%bb%a3%e7%a0%81minist%e6%89%8b%e5%86%99%e8%af%86%e5%88%ab/](https://www.emperinter.info/2019/08/28/tensorflow-gpu%e7%89%88%e6%b5%8b%e8%af%95%e4%bb%a3%e7%a0%81minist%e6%89%8b%e5%86%99%e8%af%86%e5%88%ab/)

**伺服器環境**

 - WordPress 版
：最新版本！
 - WP Githuber MD版本
：最新版本！
 - PHP 版本
：7.2

**用戶端環境**

 - 作業系統：
iOS，安卓
 - 瀏覽器
：firefox，chrome

**其它說明**

代码高亮是开启的prism.js，布景为：okaidia，文件托管：默认。行号开启！尝试更改选项都失败！

**Comment by terrylinooo** [comment]
Chrome 的 console 是否有紅字錯誤。有的話貼圖上來讓我查看。也有可能是您用的 theme 的問題，可以切換到 WordPress 的預設 theme 看看是否有同樣的問題發生。

**Comment by emperinter** [comment]
> Chrome 的 console 是否有紅字錯誤。有的話貼圖上來讓我查看。也有可能是您用的 theme 的問題，可以切換到 WordPress 的預設 theme 看看是否有同樣的問題發生。

抱歉，现在因为某些原因没有可以用的电脑，目前用的是另一个插件，我明后天有机会切换回去查看一下，到时候发给你吧！主题我好像最近没有任何更改，但安装了一些插件来重新整理了一下文章，图片等等。只记得好像升级最新版本之前没有出现任何问题！才想到提交issues的，具体等我把截图给你再说吧！

**Comment by emperinter** [comment]
> Chrome 的 console 是否有紅字錯誤。有的話貼圖上來讓我查看。也有可能是您用的 theme 的問題，可以切換到 WordPress 的預設 theme 看看是否有同樣的問題發生。

你这么说，有可能是主题问题。我目前插件代码也没有显示行号（选项开启了），但代码风格和复制选项没有问题！

**Comment by emperinter** [comment]
> Chrome 的 console 是否有紅字錯誤。有的話貼圖上來讓我查看。也有可能是您用的 theme 的問題，可以切換到 WordPress 的預設 theme 看看是否有同樣的問題發生。

图片上传不了，默认主题2020试了一下，在page页没有任何问题，但在文章页连主题也没有，只有干巴巴的文字！我也就不测试了，自己家里电脑浏览器打开都卡顿许久，没心情让卡顿折磨自己了！

自己主题console结果如下：
```shell
The resource at “<URL>” was blocked because content blocking is enabled. 3
The resource at “https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js” was blocked because content blocking is enabled.
python-wordpress-xmlrpc
The resource at “https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js” was blocked because content blocking is enabled.
python-wordpress-xmlrpc
The resource at “https://www.google-analytics.com/analytics.js” was blocked because content blocking is enabled.
python-wordpress-xmlrpc
JQMIGRATE: Migrate is installed, version 1.4.1 bd8618a86aa2c7467c175c866efa068d.js:3:552
TypeError: link_href is undefined
bd8618a86aa2c7467c175c866efa068d.js:21:162504
    <anonymous> https://www.emperinter.info/wp-content/cache/min/1/bd8618a86aa2c7467c175c866efa068d.js:21
    jQuery 2
    <anonymous> https://www.emperinter.info/wp-content/cache/min/1/bd8618a86aa2c7467c175c866efa068d.js:21
    jQuery 4
The resource from “https://cdn.jsdelivr.net/npm/prismjs@1.15.0/components/prism-shell.min.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
python-wordpress-xmlrpc
Loading failed for the <script> with source “https://cdn.jsdelivr.net/npm/prismjs@1.15.0/components/prism-shell.min.js”. python-wordpress-xmlrpc:1:1
```

默认主题文章页console如下：
> TypeError: link_href is undefined

​
