### ISSUE TITLE
githuber-md 啟用後，希望能保持「插入媒體」的功能。

### ISSUE THREAD

**Issue by dnowba** [terrylinooo/githuber-md#17]
有時候我們會需要圖片帶燈箱（lightbox）效果，就需要用到 image 上其它的 attribute。那麼就需要自行去寫 html，這時候如果能透過插入媒體的介面來轉入代碼，就會方便許多。因此，希望在打開「Insert Media」後，能夠把東西也放入 Markdown 的 Editor 裡。

**Comment by terrylinooo** [comment]
有支源 Markdown extra。

例如 ## Le Site {.sth} 會產生 <h2 id="le-site" class="sth">Le Site</h2>

即時預覽的 marked.js 要實現這個我再找時間修改。

**Comment by terrylinooo** [comment]
在插入文章的介面，會新增一組選項，讓用戶自行選擇插入 markdown 或 html。這個選項只有在 HTML 解析的設定開啟時才會出現。預計下次更新時支援。
