### ISSUE TITLE
代码区域存在html时，markdown没有处理

### ISSUE THREAD

**Issue by whuanle** [terrylinooo/githuber-md#170]
![image](https://user-images.githubusercontent.com/2189761/81535778-fdc5c780-939c-11ea-87b3-4af0b4e55fb8.png)
然后前端页面会显示成这样：
![image](https://user-images.githubusercontent.com/2189761/81535916-3665a100-939d-11ea-8500-af2005a82fd0.png)

个人认为应该像博客园那样处理代码块的 html 标签比较好

**Comment by terrylinooo** [comment]
![image](https://user-images.githubusercontent.com/11989371/82424846-52adc000-9ab8-11ea-8def-61c20bfdf3bd.png)

這個選項可以切換看看。

**Comment by whuanle** [comment]
已经解决了，十分感谢
