### ISSUE TITLE
你好，这是个很好用的插件，感谢你的创作，可否提供自定义图床来存储粘贴的图片的功能？

### ISSUE THREAD

**Issue by zcxzzz** [terrylinooo/githuber-md#173]
**如果沒有提供以下詳細資訊，您開立的問題回報會被無視。**

**問題或臭蟲**

清楚的說明問題發生的情況及結果。

**如何重現**

請告知重現此問題的步驟回何：

1. 
2. 
3. 
4. 

**預期的行為或結果**

清楚的說明您預期什麼樣的結果才是正常。

**畫面截圖**

1. 請提問題發生時的截圖
2. 例如按 F12，查看 Google Chome 開發人員工具的畫面有無紅色字樣錯誤訊息。

**伺服器環境**

 - WordPress 版本
 - WP Githuber MD 版本
 - PHP 版本

**用戶端環境**

 - 作業系統
 - 瀏覽器

**其它說明**

如果有的話，請提供。
![图片](https://user-images.githubusercontent.com/34907358/82301462-e1540b80-99ea-11ea-8425-c9cd422261fd.png)

**Comment by terrylinooo** [comment]
第三方串接都要經過測試及安全性檢查，無法提供給使用者自訂的功能。如果您有需求可以自行修改  [ImagePaste](https://github.com/terrylinooo/githuber-md/blob/master/src/Controllers/ImagePaste.php) 這支 Controller。例如您的選像選 `sm.ms`，然後自行修改 `upload_to_smms` 這個 method。
