### ISSUE TITLE
希望改进一下，在存入数据库之前不将 markdown 转换成 html。

### ISSUE THREAD

**Issue by uanaoeng** [terrylinooo/githuber-md#174]
这款插件在将文章存入数据库之前，会把 markdown 字符串转换成 html 字符串，而在编辑时，将 html 字符串转换回 markdown 字符串。

虽然目前来说，一切工作得很好，转换的过程中没有出现问题，但是这个转换的过程，终究还是会导致一些数据的丢失，无法最大程度地保留用户输入的最原始的数据。比如说在一行的结尾添加的两个空格，转换成 html 后再转换回 markdown，就丢失了。有些 markdown 解析器依赖这两个空格进行换行。

希望能向 Parsedown Party 这款 markdown 编辑器插件学习一下，将用户输入的 markdown字符串直接存入数据库，而在用户阅读文章时，将 markdown 字符串解析成 html 。

当然了，尽管存在这个问题，但是这款编辑器插件目前来说还是最优秀的， 与之相比，Parsedown Party 存在的问题也不少。

**Comment by uanaoeng** [comment]
抱歉， 是我太粗心了，刚刚发现，用户原始数据并不会有损失，存储与读取中间貌似不存在 markdown 与 html 相互转换的过程。我猜测保存的时候应该是向数据库中写入了两份数据，一份是原始的 markdown 字符串，一份是转换后的 html 字符串。我在 wp_posts 这个表中看到的数据确实是转换后的 html 字符串。

**Comment by terrylinooo** [comment]
謝謝您的建議。因為考慮到效能的關係。假如每次讀文章時才解析 Markdown，線上越多讀者閱讀文章，都必須解析的話，會拖累主機的 CPU，所以比較不考慮這樣的作法喔。
