### ISSUE TITLE
Support SEO Rank Math readability analysis.

### ISSUE THREAD

**Issue by attkri** [terrylinooo/githuber-md#176]
A Rank Math support would be helpful. Currently I'm inserting markdown text, updating, switching to classic view and updating again.

Or is there an exciting trick for that?

I would have a look at it in the code, roughly in which file should I start?

Greetings from Germany

**Comment by terrylinooo** [comment]
Hello. Which plugin are you using on readability analysis?

**Comment by attkri** [comment]
Rank Math https://de.wordpress.org/plugins/seo-by-rank-math/

**Comment by terrylinooo** [comment]
Thanks. I will take a look at it recently.
