### ISSUE TITLE
Missing Dependencies typo-check and spell-check

### ISSUE THREAD

**Issue by manfredsteger** [terrylinooo/githuber-md#178]
Hi, the debug tool **Query Monitor** show me two errors with Githuber MD:

![script-error-md-githuber](https://user-images.githubusercontent.com/8418059/87518188-3d9c7a00-c680-11ea-9e7e-90417a61b723.png)

I have problems with the Githuber MD control panel, sometimes it freezes.

**Server environment**

 - WordPress version [ 5.4.2 ]
 - WP Githuber MD plugin version [ 1.15 ]
 - PHP version [ 7.2.29 ]

**User environment**

 - OS: [ MAC 10.14 ]
 - Browser [ Chrome, Safari, Firebox ]

**Comment by hdevilbiss** [comment]
### Missing Dependencies: editormd (missing)

I have the same 2 **Missing Dependencies** errors on the `wp-admin/options-general.php?page=githuber-md` page. The file with **`editormd` handle** is missing, specifically when I turn on the **Markdown > Writing > Spellcheck** feature.

Here are the angry files in the format **Handle**: `Source`

- **githuber-md-typo-check**: `app/plugins/wp-githuber-md/assets/vendor/editor.md/lib/codemirror/addon/spellcheck/typo.js`
- **githuber-md-spell-check**: `app/plugins/wp-githuber-md/assets/vendor/editor.md/lib/codemirror/addon/spellcheck/spell-checker.js`

**Server environment**

- WordPress version [ 5.7 ]
- WP Githuber MD plugin version [ 1.16.0 ]
- PHP version [ 7.4.10 ]

**User environment**

- Windows 10
- Browser FireFox
