### ISSUE TITLE
Lost added contents when "Enable Markdown" is chanaged from Disable to Enable

### ISSUE THREAD

**Issue by nobukuma** [terrylinooo/githuber-md#18]
The contents added when "Enable Markdown" is Enabled are lost after it is changed to Disable.

Steps to Reproduce
1. Set "Enable Markdown" to Enable, and write a post and save it.
2. Change "Enable Markdown" to Disable
3. Change the post, and save it.
4. Set "Enable Markdown" to Enable.

After step 4, the contents would be the one at step 1.

**Comment by terrylinooo** [comment]
Your content wasn't lost, they were just saved to different fields.
Once you change the option to disable, your post content will be saved to `wp_posts.post_content` field directly, not `wp_posts.post_content_filtered` .
Once you change the option to enable, Markdown editor will load `wp_posts.post_content_filtered`.

The feature is just made for users who don't want to use Markdown in specific posts.
