### ISSUE TITLE
[BUG]输入法栏遮挡输入文字

### ISSUE THREAD

**Issue by Zxilly** [terrylinooo/githuber-md#184]
**問題或臭蟲**

输入法栏遮挡输入文字

**如何重現**

![image](https://user-images.githubusercontent.com/31370133/90306946-bc493900-df04-11ea-9197-b87a4d90796f.png)

**預期的行為或結果**

输入法栏位于输入文字下方
![image](https://user-images.githubusercontent.com/31370133/90306967-e7cc2380-df04-11ea-96b6-3b3dc25395cd.png)

**伺服器環境**

 - WordPress 版本 5.5
 - WP Githuber MD 版本 lastest
 - PHP 版本 7.4

**用戶端環境**

 - 作業系統 Windows 10 2004
 - 瀏覽器 Edge latest
 - 输入法 微软拼音

**Comment by terrylinooo** [comment]
謝謝您的回報。已在即將發佈的 1.15.1 版修正此問題。
