### ISSUE TITLE
pre 块内不应该转义任何字符，包括反引号字符 '`'

### ISSUE THREAD

**Issue by Flaryer** [terrylinooo/githuber-md#185]
**如果沒有提供以下詳細資訊，您開立的問題回報會被無視。**

**問題或臭蟲**

pre 块内不应该转义任何字符，包括反引号字符 '`'

另外问一问为什么不直接调用编辑模式的 md 转 html 程序，很多时候页面内容和编辑模式预览严重不一致。

清楚的說明問題發生的情況及結果。

**如何重現**

請告知重現此問題的步驟回何：

以下 sql 代码，反引号也会被转义。
```sql
CREATE TABLE IF NOT EXISTS `runoob_tbl`(
   `runoob_id` INT UNSIGNED AUTO_INCREMENT,
   `runoob_title` VARCHAR(100) NOT NULL,
   `runoob_author` VARCHAR(40) NOT NULL,
   `submission_date` DATE,
   PRIMARY KEY ( `runoob_id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**預期的行為或結果**

清楚的說明您預期什麼樣的結果才是正常。

**畫面截圖**
![image](https://user-images.githubusercontent.com/30646834/92386192-dfeb5200-f145-11ea-82e5-919f94d1ccb7.png)

1. 請提問題發生時的截圖
2. 例如按 F12，查看 Google Chome 開發人員工具的畫面有無紅色字樣錯誤訊息。

**伺服器環境**

 - WordPress 版本 5.5.1
 - WP Githuber MD 版本 1.15
 - PHP 版本 7.3

**用戶端環境**

 - 作業系統 win10
 - 瀏覽器 chrome

**其它說明**

如果有的話，請提供。

**Comment by terrylinooo** [comment]
https://github.com/terrylinooo/githuber-md/issues/114

**Comment by Flaryer** [comment]
似乎我已经打开这个选项了。

![image](https://user-images.githubusercontent.com/30646834/92387970-0d85ca80-f149-11ea-9715-f21cf8fc65d6.png)

**Comment by Flaryer** [comment]
@terrylinooo 请求修复呜呜呜
