### ISSUE TITLE
Does not properly render file system tree text

### ISSUE THREAD

**Issue by dougreese** [terrylinooo/githuber-md#188]
**Describe the bug**

The output of a file system tree as rendered in a console by the `tree` utility does not display correctly.

Example...

Output of `tree` utility (and what I would hope renders in my post page):

```
treetest/
├── dir1
│   ├── file1.1
│   └── file1.2
└── dir2
    └── file2.1
```

I have tried both prism.js and highlight.js syntax highlight options.

**To reproduce**

1. Run the `tree` utility on a directory hierarchy in a Linux (or maybe Mac) terminal window (install if necessary: `sudo apt install tree`)
2. Copy the output and paste into a post, using the GitHub style code delimiters (see above tree test syntax for this issue)
3. View the post preview

**Expected behavior**

I expect the output to be rendered in a manner similar to how it displays in this issue.

**Screenshots**

As displayed in editor:

![image](https://user-images.githubusercontent.com/51355/93559269-2e61d300-f934-11ea-9af2-e762f0b775d3.png)

As displayed in post preview and published page:

![image](https://user-images.githubusercontent.com/51355/93559299-420d3980-f934-11ea-842c-8d7b868110a3.png)

**Server environment**

 - WordPress version [ e.g. 5.5.1 ]
 - WP Githuber MD plugin version [ e.g. 1.15.0 ]
 - PHP version [ e.g. 7.3 ]

**User environment**

 - OS: Mac, Linux
 - Browser Chrome

**Additional context**

I use this in type of content in GitHub issues and Wiki pages.  I was hoping it would translate directly into WordPress using the Githuber MD plugin. Everything else seems to work excellent!

**Comment by terrylinooo** [comment]
Ok. I'll look into this issue. Fix it in the next update.

**Comment by dougreese** [comment]
I forgot about this issue, until I went to publish another post.  It looks like this is still not fixed.  I am using version 1.16.1 of the plugin.

**Comment by dougreese** [comment]
Is this still an outstanding bug?
