### ISSUE TITLE
粘贴图片不能粘贴gif格式，这个能支持吗

### ISSUE THREAD

**Issue by npmrun** [terrylinooo/githuber-md#189]
**如果沒有提供以下詳細資訊，您開立的問題回報會被無視。**

**問題或臭蟲**

粘贴图片不能粘贴gif格式

**如何重現**
1. 复制gif格式图片
2. 粘贴没反应

**預期的行為或結果**

希望粘贴之后自动上传gif图并插入

**畫面截圖**

无

**伺服器環境**

 - WordPress 版本
v 5.5.1
 - WP Githuber MD 版本
v 1.15.1
 - PHP 版本
v 7.2

**用戶端環境**

 - 作業系統
 - 瀏覽器
新版Edge

**Comment by terrylinooo** [comment]
無法。因為是轉換成 PNG 格式再貼上。
