### ISSUE TITLE
Support Shortcodes in MD

### ISSUE THREAD

**Issue by christophcemper** [terrylinooo/githuber-md#19]
We sometimes need a shortcode to embed something cool "Wordpressish" from other extensions inside the MD

So for example below the "ctabutton" shortcode from the "Shortcoder extension" 
should help avoid placing that large HTML code you see later.

![image](https://user-images.githubusercontent.com/12080594/53686134-b4eb9b00-3d23-11e9-9519-0d68031a59c6.png)

Ref: https://wordpress.org/support/plugin/shortcoder

**Comment by terrylinooo** [comment]
Thanks for your suggesting. I will make it in version 1.7.0. Any update I will mention you here.

**Comment by christophcemper** [comment]
That will be fantastic. thanks so much

**Comment by christophcemper** [comment]
Works like a charm! thanks so much
