### ISSUE TITLE
Youtube url at top of post only shows href a tag

### ISSUE THREAD

**Issue by codercatdev** [terrylinooo/githuber-md#191]
**Any issue will be ignored if you don't provide the following detailed information.**

**Describe the bug**

When putting in https://youtu.be/vM_YoZbLQQ0 I expect to see the YouTube video in post not the lin.

**To reproduce**

1. Add post in md editor and place https://youtu.be/vM_YoZbLQQ0 in text
2. Mark Post type Video
3. View post and you will only see link compiled

**Expected behavior**

1. Add post in plain editor and place https://youtu.be/vM_YoZbLQQ0 in text
2. Mark Post type Video
3. View post and you will see YouTube video

**Screenshots**

![image](https://user-images.githubusercontent.com/3102249/97675952-4f0a6600-1a66-11eb-8570-f57977f2612b.png)
When you then enable MD, it immediately shows up as <a> tag.
![image](https://user-images.githubusercontent.com/3102249/97676223-b4f6ed80-1a66-11eb-8d79-d5c8d33ea93c.png)

**Server environment**

 - WordPress version [ e.g. 5.5.2 ]
- WP Githuber MD | Version 1.15.1 by Terry Lin \| Auto-updates disabled
 - PHP version [ e.g. 5.4 ]

**User environment**

 - OS: Mac
 - Browser Chrome

**Additional context**

**Comment by Li-An** [comment]
Same problem here. All URL pasted in Githuber-MD editor are automatically changed into links, so embedded contents are broken (see https://wordpress.org/support/article/embeds/ for the list of sites). It’s a regression compared to WP default behavior.
