### ISSUE TITLE
can't copy remote images

### ISSUE THREAD

**Issue by oakcdrom** [terrylinooo/githuber-md#194]
My wordpress updated the 5.5.3, when I want ot  copy other include images of news to my wordpress, I found it can't include images, the WP Githuber MD version is 1.15.2.

**Comment by terrylinooo** [comment]
1. Check your cURL works or not.
2. The target webiste may not allow robtos to grab their images.

**Comment by oakcdrom** [comment]
I used  website host not vps.. it allows copy images------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Terry&amp;nbsp;L.&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月6日(星期五) 下午2:05
收件人:&nbsp;&quot;terrylinooo/githuber-md&quot;<githuber-md@noreply.github.com&gt;;
抄送:&nbsp;&quot;oakcdrom&quot;<452300@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [terrylinooo/githuber-md] can&#39;t copy remote images (#194)

**Comment by oakcdrom** [comment]
I conform the curl is working , I only copy the images to markdown, is no problem, if include the news, only display the name of images.
