### ISSUE TITLE
Html 轉 Markdown 錯誤

### ISSUE THREAD

**Issue by cras4202tw** [terrylinooo/githuber-md#2]
## 網站資訊
WordPress 5.0.2
Nginx 1.15.7
PHP 7.2.13
[外掛列表](https://gist.github.com/cras4202tw/76c3f1851bf6c38baa072845772755ca)

### 原始內容
```
<code>$_SERVER['SERVER_PORT'] = 80;</code>
```

### 轉換後
```
$_SERVER[\'SERVER_PORT\'] = 80;
```

### 原始內容
```
<p><script src="https://gist.github.com/cras4202tw/80b2b53f9fa37d3223bde4fadcb873f7.js"></script></p>
```

### 轉換後
```

```

### 原始內容
```
<p><img class="alignnone size-full wp-image-737" src="https://www.4rbj4.com/wp-content/uploads/2018/07/1530844867-a77a37c09dfb4ee38a29a8fa2249936b.png" alt="" width="820" height="187" /></p>
```

### 轉換後
```
![\"\"](\"https://www.4rbj4.com/wp-content/uploads/2018/07/1530844867-a77a37c09dfb4ee38a29a8fa2249936b.png\")
```

### markdown 所見即所得的內容
```
<p><img src="\&quot;https://www.4rbj4.com/wp-content/uploads/2018/07/1530844867-a77a37c09dfb4ee38a29a8fa2249936b.png\&quot;" alt="\&quot;\&quot;" scale="0"></p>
```

### 原本內容
![before](https://www.4rbj4.com/wp-content/uploads/2019/01/1546939713-fb282fe40ca227692bdb840f2a5f11ea.png)

### 轉換後
![after](https://www.4rbj4.com/wp-content/uploads/2019/01/1546939716-90e58b9094cc92dffa58ee10be67bdea.png)

**Comment by terrylinooo** [comment]
謝謝回報。我晚上班來看看

**Comment by terrylinooo** [comment]
已修復。

關於 script 這個 tag 在 Markdown 中並沒有對樣的代碼。針對小工具的設定原先並沒有考慮到其它部分，只想到轉換文章為 Markdown 格式。關於想保留的 HTML 片段要請您多加留意。或者我評估一下在後台加上 tag 的保留選項，再把這個選項放到下一版更新。
