### ISSUE TITLE
Katex 和 MathJax 行内公式显示异常

### ISSUE THREAD

**Issue by SnailDove** [terrylinooo/githuber-md#200]
**問題或臭蟲**

清楚的說明問題發生的情況及結果。

Katex 和 MathJax 行内公式显示异常，会有图片清晰展示场景

**如何重現**

請告知重現此問題的步驟回何：

1. 无论是开启 Katex 还是 MathJax ，行内公式渲染都显示异常：直接不渲染，像行内代码一样，参考图片
2. 在编辑MathJax多行公式时，markdown输入框会自动翻译成html代码，影响继续编辑

**預期的行為或結果**

正常使用书写和渲染数学公式

**畫面截圖**

1. 請提問題發生時的截圖

如果Markdown语法的图片不显示的话，直接打开这个图片链接：https://s3-cn-south-1.qiniucs.com/snaildove-gitblog/mkdown_bug.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=QRnBlzUs_tP4nUgMfpF1l_ZhDCwpJvg1zGcTO_hS%2F20210124%2Fcn-south-1%2Fs3%2Faws4_request&X-Amz-Date=20210124T101637Z&X-Amz-Expires=604800&X-Amz-Signature=3207e10b6b3b9049c77280f8c54bdcfc3fd55f2adaed8888b23d87dcf728dbe2&X-Amz-SignedHeaders=host

![](https://s3-cn-south-1.qiniucs.com/snaildove-gitblog/mkdown_bug.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=QRnBlzUs_tP4nUgMfpF1l_ZhDCwpJvg1zGcTO_hS%2F20210124%2Fcn-south-1%2Fs3%2Faws4_request&X-Amz-Date=20210124T101637Z&X-Amz-Expires=604800&X-Amz-Signature=3207e10b6b3b9049c77280f8c54bdcfc3fd55f2adaed8888b23d87dcf728dbe2&X-Amz-SignedHeaders=host)

2. 例如按 F12，查看 Google Chome 開發人員工具的畫面有無紅色字樣錯誤訊息。

只有警告，没有错误。

**伺服器環境**

 - WordPress 版本 : 5.3.3
 - WP Githuber MD 版本: 1.15.2 下载自 WordPress.org
 - PHP 版本: 7.3.14

**用戶端環境**

 - 作業系統: Unraid 是一种NAS系统，是Linux Slackware，安装的是 docker 版本的 WordPress 5.3.3，仓库源链： https://github.com/docker-library/wordpress
 - 瀏覽器:   微软的Edge、chrome、Safari都不工作， 运行在苹果 Catalina 15.7

**其它說明**

感谢作者提供这么好的插件，我的博客需要时不时书写一些数学公式，感谢开源付出！！！

**Comment by li-han-nu** [comment]
行内公式也要$$ $$吧，不能只有一个

**Comment by qiujiangkun** [comment]
我遇到了同样的问题，编辑端无法预览，但是前端可以正常显示
![image](https://user-images.githubusercontent.com/33482468/108162803-cb65a980-7128-11eb-8c39-a94cddc71496.png)
