### ISSUE TITLE
C# 泛型无法显示并且导致网页适配错乱

### ISSUE THREAD

**Issue by su9257** [terrylinooo/githuber-md#202]
**如果沒有提供以下詳細資訊，您開立的問題回報會被無視。**

**問題或臭蟲**

清楚的說明問題發生的情況及結果。

**如何重現**

請告知重現此問題的步驟回何：

1. C# 创建一个泛型代码块
2. 发布
3. 整个页面错乱，并且泛型<>中的代码丢失

**預期的行為或結果**

页面正常且泛型代码正常

**畫面截圖**

![image](https://user-images.githubusercontent.com/20715825/103400262-67d6eb00-4b7f-11eb-973d-390950a1a3ae.png)

![image](https://user-images.githubusercontent.com/20715825/103400286-8341f600-4b7f-11eb-9cc7-819979f54130.png)

* **对应的网页地址:https://aihailan.com/3-4%e8%ae%be%e8%ae%a1%e6%a8%a1%e5%bc%8f%e4%b9%8b%e8%bf%ad%e4%bb%a3%e5%99%a8%e6%a8%a1%e5%bc%8f%ef%bc%88iterator%ef%bc%89/**

1. 請提問題發生時的截圖
2. 例如按 F12，查看 Google Chome 開發人員工具的畫面有無紅色字樣錯誤訊息。

**伺服器環境**

 - WordPress 版本 5.6
 - WP Githuber MD 版本 1.15.2
 - PHP 版本 7.4

**用戶端環境**

 - 作業系統 Win 10
 - 瀏覽器 Google Chrome

**其它說明**

如果有的話，請提供。

**Comment by terrylinooo** [comment]
這兩天會進行更新。你的問題我再仔細看一下。

**Comment by su9257** [comment]
> 這兩天會進行更新。你的問題我再仔細看一下。

非常感谢，期待你的回复

**Comment by terrylinooo** [comment]
After testing, the code block works good.

![image](https://user-images.githubusercontent.com/11989371/108013200-270b3680-7046-11eb-94d2-c453f6abdae8.png)

Be sure that this option (as below) is turned off.

![image](https://user-images.githubusercontent.com/11989371/108013262-499d4f80-7046-11eb-9ffd-4f68fb2993b4.png)

**Comment by su9257** [comment]
> After testing, the code block works good.
> 
> ![image](https://user-images.githubusercontent.com/11989371/108013200-270b3680-7046-11eb-94d2-c453f6abdae8.png)
> 
> Be sure that this option (as below) is turned off.
> 
> ![image](https://user-images.githubusercontent.com/11989371/108013262-499d4f80-7046-11eb-9ffd-4f68fb2993b4.png)

Thank you very much. That solved my big problem
