### ISSUE TITLE
希望添加：禁止下划线变成斜体的功能

### ISSUE THREAD

**Issue by lanyun1103** [terrylinooo/githuber-md#203]
编辑数学公式必须用到下划线，用来表示下标

但是下划线在markdown中代表斜体，我在typora中可以很好地查看公式，但是换到网站上，公式中的下划线在html变成`<em>`标签，`<em>`标签跨越了数学公式的标志$，导致无法正确识别到公式

希望可以添加一个功能，让下划线无效，或者是转义他，这样发布时就不会有<em>标签

这对经常写数学公式的人来说非常有用，否则我需要写一个脚本在每次上传前转义里面的所有下划线
感谢

**Comment by itcharge** [comment]
同上，希望可以设置 禁止下划线变成斜体。
