### ISSUE TITLE
Inline mathjax is not displayed.

### ISSUE THREAD

**Issue by just-hjkwon** [terrylinooo/githuber-md#210]
**Any issue will be ignored if you don't provide the following detailed information.**

**Describe the bug**

Firstly, I'm sorry for my bad English and not familiar Wordpress framework.

When I write inline math as latex format in the article, ie. \`$f(x)$\`
it is not displayed by MathJax.

The reason is below.

At the publishing step, `MathJax.php` module tries to detect \<code\> \$ ... $  \</code\> used by regex.
Then, it appends **`mathjax-inline`** and **`language-mathjax`** css classes to \<code\> element.

https://github.com/terrylinooo/githuber-md/blob/79eb78ee2ef49d384a87a0e70accdc03fc795a51/src/Modules/MathJax.php#L183

But at the rendering step,

The function `detect_code_languages()` tries to match with \<code class="mathjax-inline"> exactly and it will fail.

https://github.com/terrylinooo/githuber-md/blob/79eb78ee2ef49d384a87a0e70accdc03fc795a51/src/Controllers/Markdown.php#L484

Finally, the variable `$is_mathjax` turns off and the metadata `self::MD_POST_META_MATHJAX` set `false`.

Second problem is that,

In Mathjax configuration script, inline math script should start and end with single \$. But here it is converted with double \$\$ when inline or not inline.

https://github.com/terrylinooo/githuber-md/blob/79eb78ee2ef49d384a87a0e70accdc03fc795a51/src/Modules/MathJax.php#L107

I think these issues are same situation on katex module.

**To reproduce**

Just write a single line with inline mathjax code.

\`$ f(x) $\`

**Expected behavior**

Wordpress shows the math inline.

**Screenshots**

I think no need the screenshot.

**Server environment**

 - WordPress version [ 5.6 ]
 - WP Githuber MD plugin version [ 1.15.2 ]
 - PHP version [ 7.0.33 ]

**User environment**

 - OS: [ Windows ]
 - Browser [ Chrome ]

**Additional context**

**Comment by terrylinooo** [comment]
This issue is confirmed and will be fixed in the next update.
Thanks for reporting this issue and carefully review the code.
