### ISSUE TITLE
关于 自动保存无效

### ISSUE THREAD

**Issue by pphboy** [terrylinooo/githuber-md#211]
**如果沒有提供以下詳細資訊，您開立的問題回報會被無視。**

**問題或臭蟲**

清楚的說明問題發生的情況及結果。

**如何重現**

請告知重現此問題的步驟回何：

1.  就是想开启自动保存，但是关了停用后，还是不生效生动保存

**預期的行為或結果**

清楚的說明您預期什麼樣的結果才是正常。

**畫面截圖**

1. 請提問題發生時的截圖
2. 例如按 F12，查看 Google Chome 開發人員工具的畫面有無紅色字樣錯誤訊息。

**伺服器環境**

 - WordPress 版本 5.6.1
 - WP Githuber MD 版本  1.60
 - PHP 版本 7.3

**用戶端環境**

 - 作業系統 windows 10 
 - 瀏覽器 chrome

**其它說明**

如果有的話，請提供。

**Comment by terrylinooo** [comment]
回復前一次草稿的按紐失效，我再檢查看看。
