### ISSUE TITLE
Highlight 建議先將語法名稱轉小寫之後再映射

### ISSUE THREAD

**Issue by jakeuj** [terrylinooo/githuber-md#212]
**如果沒有提供以下詳細資訊，您開立的問題回報會被無視。**

**問題或臭蟲**

只有小寫 cs 可以正常語法高亮

**如何重現**

請告知重現此問題的步驟**回**何：

1. 程式碼區段使用大寫 ``` CS

```CS
using System.IO.Compression;

namespace MyApplication
{
    [Obsolete("...")]
    class Program : IInterface
    {
        public static List<int> JustDoIt(int count)
        {
            Span<int> numbers = stackalloc int[length];
            Console.WriteLine($"Hello {Name}!");
            return new List<int>(new int[] { 1, 2, 3 })
        }
    }
}
```

**預期的行為或結果**

無論大小寫 CS, CSharp, C# 皆可以正常語法高亮

**畫面截圖**

大寫CS

![2021-02-18_14-46-53](https://user-images.githubusercontent.com/834156/108317297-07683f80-71f9-11eb-8e40-cd6c5a8803df.png)

![2021-02-18_14-54-03](https://user-images.githubusercontent.com/834156/108317421-38487480-71f9-11eb-9f0a-3337e9850108.png)

小寫 cs

![2021-02-18_14-48-47](https://user-images.githubusercontent.com/834156/108316998-a3de1200-71f8-11eb-81d6-549287866af9.png)

**伺服器環境**

 - WordPress 版本 5.6.1
 - WP Githuber MD 版本 1.16.0
 - PHP 版本 7.4 x86

**用戶端環境**

 - 作業系統 Win 10 20H2 19042.804
 - 瀏覽器 Chrome 版本 88.0.4324.182 (正式版本) (64 位元)

**其它說明**

- 語法名稱先將轉小寫之後再映射
- cs 加入 c# 與 csharp 名稱映射
- 參照：[Highlight.php](https://github.com/terrylinooo/githuber-md/blob/master/src/Modules/Highlight.php#L72)

**Comment by su81228** [comment]
python 也無法QQ

**Comment by jakeuj** [comment]
> python 也無法QQ
你是輸入小寫 python 嗎？
'''python
https://github.com/terrylinooo/githuber-md/blob/master/src/Modules/Highlight.php#L172

```python
# src/hello.py
print("Hello world!")
```
