### ISSUE TITLE
Displaying output for HTML entities, single ticks, and triple ticks

### ISSUE THREAD

**Issue by MonteShaffer** [terrylinooo/githuber-md#213]
**Any issue will be ignored if you don't provide the following detailed information.**

<https://ramblings.mshaffer.com/?post=351>
<https://ramblings.mshaffer.com/2021/02/using-r-where-is-the-functional-inverse-of-set-seed-that-is-get-seed/>

**Describe the bug**

When I use a single tick mark, it displays as if I used the three tick marks.  

<img width="547" alt="viewer" src="https://user-images.githubusercontent.com/6663327/108634868-a88d0b00-7430-11eb-950e-8ef2955e4c99.png">

In edit mode, it displays correctly.

<img width="903" alt="editor" src="https://user-images.githubusercontent.com/6663327/108634875-adea5580-7430-11eb-8599-14a03a4fde2c.png">

Similarly, edit mode works fine for HTML entities

<img width="912" alt="include-urls" src="https://user-images.githubusercontent.com/6663327/108634997-93fd4280-7431-11eb-9a96-127e395668d7.png">

But renders them in the final output horribly:

<img width="717" alt="url-rendered" src="https://user-images.githubusercontent.com/6663327/108635004-9e1f4100-7431-11eb-9e64-5b8f6e052fda.png">

**Server environment**

 - WordPress version [ e.g. 5.6.1 ]  Theme "Twenty Seventeen" (updated)
 - WP Githuber MD plugin version [Version 1.16.0 ]
 - PHP version [5.6.40] ... ridiculous question, you think the average user is going to know this?

**User environment**

 - OS: Windows 
 - Browser: Chrome

**Comment by Anthem-whisper** [comment]
Oh! God! that's so terrible! I had the same problem, when I use a code block, '<' or '>' is often translate to '&lt;' or '&gt;'
http://wh1sper.com/hgame-2021-writeup/
