### ISSUE TITLE
MathJax出现无限递归$符号的问题

### ISSUE THREAD

**Issue by ruanluyu** [terrylinooo/githuber-md#218]
**情況及結果。**

开发人员辛苦了！
我是MiLai网站的站长(pw.yuelili.com)
我的网站本来使用Katex来渲染公式
最近我统一通过正则表达式替换成MathJax来渲染公式
大部分文章都很完美的渲染出来了
但是有一篇文章出现了异常（无限递归增加$符号 https://pw.yuelili.com/study/math/fouriers-dream/ch1.html  ）
我不知道是不是只有在我的电脑上会这么显示
我网站上所有其他的MathJax页面都正常渲染了，唯独这篇文章产生了问题
其它数学相关的文章可以check这里：https://pw.yuelili.com/category/study/math

**如何重現**

进入这个链接：https://pw.yuelili.com/study/math/fouriers-dream/ch1.html

**預期的行為或結果**

正常渲染MathJax

**后台文档**

那篇出问题的文章的md文档 
https://drive.google.com/file/d/1gfbfGXl_IVS8x_OgLYaOxLTko48bh4SW/view?usp=sharing

**畫面截圖**

（抱歉没太搞懂怎么在这里上传图片）

**伺服器環境**

 - WordPress 版本 5.6.2
 - WP Githuber MD 版本 1.16.0
 - PHP 版本 ???

**用戶端環境**

 - 作業系統 版本	Windows 10 专业版
版本号	20H2
安装日期	‎2020/‎10/‎19
操作系统内部版本	19042.804

 - 瀏覽器 Chrome

**Comment by terrylinooo** [comment]
好的。今晚來查看
謝謝回報

**Comment by ruanluyu** [comment]
嗨，作者你好

我今天锁定到了这个问题关键的一行：

```mathjax
\exists M>0 \quad s.t. \quad |f(x)|<M\\
\Rightarrow |f(x+y)-f(x)| \leq 2M
```

如果我把第一行的“|f(x)|<M”改成“|f(x)| < M”（小于号两遍放入空格）时文章就能正确显示了。
猜测是不是<这个符号被误匹配了。希望能对后续开发有所帮助。
