### ISSUE TITLE
An issue on footnotes, and others

### ISSUE THREAD

**Issue by klmo** [terrylinooo/githuber-md#22]
Hi, I just used your great plugin on Wordpress. Thank you for developing it.
But I've found _an issue_ on footnotes. I wrote the following:

> ABCD[^1]efghijklmnopqrstuvwxyz.
> abcd[^2].
>
> [^1]: First note
> [^2]: Second note

Then, the published page gave me:
![fnts](https://user-images.githubusercontent.com/48254088/53820446-24c18600-3faf-11e9-900f-dc99ac6e8cf4.jpg)

I don't know if it's just me.

---

And these are others. Supports for the following would be nice.
1. How about adding [Bigfoot.js](http://www.bigfootjs.com/) to this plugin? I think it's simple to embed and pretty good for viewers to see the footnotes. Or, there should be another way to do it. A markdown editor (_not_ Wordpress plugin) called [Typora](https://typora.io/) provides live previews for footnotes using hover popups.
2. _Sometimes_ I'd like to use the [mhchem extension](https://github.com/KaTeX/KaTeX/tree/master/contrib/mhchem) with KaTeX. I wish there would be an option about using such extensions per page or post.

**Comment by terrylinooo** [comment]
Thanks for your feedback, I will fix it as soon as possible.

About the Bigfoot.js, I will look into it and think of the possibility of using it.

Any update I will mention you here.
