### ISSUE TITLE
3-6级标题失效

### ISSUE THREAD

**Issue by su9257** [terrylinooo/githuber-md#221]
**如果沒有提供以下詳細資訊，您開立的問題回報會被無視。**

**問題或臭蟲**

3-6级标题失效

清楚的說明問題發生的情況及結果。

```
# 标题一级
## 标题二级
### 标题三级
#### 标题四级
##### 标题五级
###### 标题六级
```
其中在预览界面可以看到3-6级标题效果，发布后3-6级标题失效。

**如何重現**

請告知重現此問題的步驟回何：

1. 编写对应的markdown语法
```
# 标题一级
## 标题二级
### 标题三级
#### 标题四级
##### 标题五级
###### 标题六级
```
2. 发布

**預期的行為或結果**

清楚的說明您預期什麼樣的結果才是正常。

**畫面截圖**

![image](https://user-images.githubusercontent.com/20715825/111110218-168fa280-8597-11eb-8201-107fd974de8c.png)

![image](https://user-images.githubusercontent.com/20715825/111110291-3b841580-8597-11eb-8433-c498060d537d.png)

1. 請提問題發生時的截圖
2. 例如按 F12，查看 Google Chome 開發人員工具的畫面有無紅色字樣錯誤訊息。

**伺服器環境**

 - WordPress 版本 5.7
 - WP Githuber MD 版本 1.16.0
 - PHP 版本 7.4

**用戶端環境**

 - 作業系統 window 10
 - 瀏覽器 谷歌浏览器

**其它說明**

如果有的話，請提供。

**Comment by terrylinooo** [comment]
您的 CSS 問題。上層肯定有 !important 語法。

**Comment by su9257** [comment]
> 您的CSS问题。上层肯定有！important语法。

新建一个全新的页面也会出现这个问题，原来是正常的。
