### ISSUE TITLE
Breaks Classic Editor for Pages if not enabled on pages

### ISSUE THREAD

**Issue by hdevilbiss** [terrylinooo/githuber-md#225]
### Breaks Classic Editor for Pages if not enabled on pages

**Describe the bug**

Enabling WP GitHuber MD on posts, but not pages, breaks the Classic Editor for pages.

**To reproduce**

1. Have both [WP GitHuber MD 1.16.0](https://wordpress.org/plugins/wp-githuber-md/) and [Classic Editor 1.6](https://wordpress.org/plugins/classic-editor/) installed and activated.
2. Under `Settings > WP GitHuber MD > Markdown > Writing`, `Pages` is not checked. However, `Posts` **is** checked.
3. Create a new post. The post is created using WP GitHuber MD, resembling Classic Editor.
4. Create a new page. It uses block editor, but it should be using Classic Editor.
5. Uncheck "Posts" in WP GitHuber MD settings.
6. Go back to edit a page. Now, Classic Editor is used.

**Expected behavior**

4. Create a new page. It uses Classic Editor.

**Screenshots**

_Create New Page uses block editor, but should be using Classic Editor._
![block-editor](https://user-images.githubusercontent.com/45151652/111932413-b9628800-8a93-11eb-8ce1-ceb1078ccbe4.jpg)

_WP GitHuber MD is enabled for posts, but not pages_
![wp-githuber-md-markdown-writing-settings](https://user-images.githubusercontent.com/45151652/111932416-ba93b500-8a93-11eb-83c0-d5301aa3336f.jpg)

Server environment

    WordPress version [ 5.7 ]
    WP Githuber MD plugin version [ 1.16.0 ]
    PHP version [ 7.4.10 ]
    Classic Editor version: [ 1.6 ]

User environment

    OS: [ Windows 10 ]
    Browser [ FireFox ]

Additional context

- See related issues [#43](https://github.com/terrylinooo/githuber-md/issues/43) and  [#84](https://github.com/terrylinooo/githuber-md/issues/84)

**Comment by shmuelios** [comment]
It would be great to see a fix for this. Thanks

**Comment by kithairon** [comment]
WP 5.8 | WP Githuber 1.16.0 | macOS 11.5.2
Like to second that request of OP.   Please fix the return to Classic editor. Thanks!
