### ISSUE TITLE
编辑器中的换行没有带<br>标签

### ISSUE THREAD

**Issue by HanryYu** [terrylinooo/githuber-md#228]
**問題或臭蟲**
使用編輯器編寫文章時，行內換行和段內換行，邏輯有點問題，段內換行需要手動添加 \<br\>， 段落換行中間需要空一行

**例如：**
編輯器：
![image](https://user-images.githubusercontent.com/20253239/115185277-19d7fa00-a112-11eb-865a-5b838fbf198c.png)
渲染後：
情況 1 把兩行內容放在了同一個 p 標簽中
![image](https://user-images.githubusercontent.com/20253239/115185361-43912100-a112-11eb-933e-b4e35909ebce.png)

**預期的行為或結果**
應該是編輯器內Markdown換行就 段內換行，Markdown中間空一行則段落換行
![image](https://user-images.githubusercontent.com/20253239/115186316-0f1e6480-a114-11eb-9386-918aa6423e07.png)

**伺服器環境**

 - WordPress 4.9.9
 - WP Githuber MD 版本 1.16.0
 - PHP 版本 5.6

**用戶端環境**

 - 經測試此問題跟系統無關
 - 瀏覽器 Chrome + Edge 90.0.818.39

**Comment by 1Gbps** [comment]
这个问题真的很影响使用
