### ISSUE TITLE
githuber-md crashed

### ISSUE THREAD

**Issue by BriFuture** [terrylinooo/githuber-md#23]
![image](https://user-images.githubusercontent.com/7582298/54011959-55700e00-41af-11e9-8b10-3da7be4a455b.png

content in log: [08-Mar-2019 06:32:55 UTC] PHP Fatal error:  Call to undefined function mb_convert_encoding() in /var/www/wordpress/wp-content/plugins/wp-githuber-md/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 468

It seems that mb_convert_encoding() is undefined, but the first time I tried it, nothing wrong with the plugin. What Can i do with this message?

**Comment by terrylinooo** [comment]
You have to install mbstring extension for your PHP.
Ask for your web hosting provider to install it.
