### ISSUE TITLE
Live Preview shows an extra space after straight single quotes 

### ISSUE THREAD

**Issue by edoreld** [terrylinooo/githuber-md#24]
First of all, thanks for this wonderful plugin.

Second, when I use straight single quotes ('), the live preview shows an extra space after the quote.

So if I type "here's" in the editor it will show "here' s" in the live preview. When I publish the post the extra space disappears. It's a minor annoyance but it would be great if it could be fixed.

Test case:
1. Create a new post on a Wordpress site with the plugin installed.
2. Type "here's" in the editor.
The Live Preview shows "here' s"

**Comment by terrylinooo** [comment]
Thanks for your feedback. I will look into it and solve it in next update (1.6.2).

**Comment by edoreld** [comment]
Without really knowing why, the problem has disappeared. The same blog post that initially showed the problem now renders the single quotes correctly. It's possible that it was just a temporary issue. 

I will reopen and keep open if the problem reappears.

**Comment by viktorix** [comment]
Not sure if it's the same issue, it does sound like it. The preview adds space after single quote, typically used as an apostrophe (ex: doesn't). If escaped with \ space is removed in preview, but \ shows up when published. So this seems to be simply a preview issue. Thought I report just in case.

![image](https://user-images.githubusercontent.com/1692600/58685044-652f6680-8348-11e9-92d6-c515c788db80.png)
