### ISSUE TITLE
Warning when Markdown Extra activated

### ISSUE THREAD

**Issue by id027102** [terrylinooo/githuber-md#242]
After upgrading PHP to PHP8.0 , I set PHP to display all_errors and then I get :
Warning: Trying to access array offset on value of type null in wordpress/wp-content/plugins/wp-githuber-md/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 241

The problem occurs when trying to save/update after edit and post is not saved

While editing , preview is ok and all seems ok

Create the post with MarkdownExtra disabled is OK , post saved an can be saved and viewed.

After reactivating MarkdownExtra , post can be edited not updated

**Comment by SorinGFS** [comment]
I confirm the same issue on php7.4. My logs are filled whit those errors, for every hit on `Update` button I get 10 errors in logs.

**Comment by SorinGFS** [comment]
> After 9+ month , first answer , they are not interested with problems . Only what they need.

It's understandable, he's just one guy, @terrylinooo , and if you look at his activity on Github he probably gave up on open source and got a job. Some things just get too big for one person, especially when there is no profit and the bills come monthly.
