### ISSUE TITLE
如何使用了WP Githuber MD后，修改写文章时候的字体大小

### ISSUE THREAD

**Issue by yangrisheng** [terrylinooo/githuber-md#247]
如何使用了WP Githuber MD后，修改写文章时候的字体大小

**Comment by zhaowe1** [comment]
<style>.editormd .CodeMirror pre { font-size: 18px;} .editormd-preview p { font-size: 17px;}</style>
可以尝试添加这段css覆盖默认字体大小


添加一个新的插件：

function xxx_resize_md_editor_font_size_css()
{
    echo '<style>.editormd .CodeMirror pre { font-size: 18px;} .editormd-preview p { font-size: 17px;}</style>';
}

add_action('admin_head', 'xxx_add_md_edit_font_size_css');
