### ISSUE TITLE
wordpress5.8.1 配合wp githuber md文章发布后代码段无法高亮

### ISSUE THREAD

**Issue by Lijunmumin** [terrylinooo/githuber-md#255]
**Any issue will be ignored if you don't provide the following detailed information.**

**Describe the bug**
在腾讯云HK的服务器上部署了wordpress博客，主题是blocksy，一直习惯markdown，所以就安装了wp githuber md，但是写完文章，发现markdown的代码段没有高亮；

具体现象：
1、wp githuber md的设置已经设好了，代码高亮已经打开
2、wp githuber md写作预览时效果正常，但是博客发布后代码段就不高亮了

**实际效果网址**
https://oiio.cyou/cplusplus_algorithm/

**Server environment**
 - WordPress version [ e.g. 5.8.1 ]
 - WP Githuber MD plugin version [ e.g. 1.61.1 ]
 - PHP version [ e.g. 7.2 ]

**Comment by KeyboardMan1996** [comment]
这个方法也许可以解决你的问题http://cppdebug.com/archives/438
