### ISSUE TITLE
Unable to set option to open link in new tab & option is lost when switching from Guttenberg editor to githuber

### ISSUE THREAD

**Issue by edoreld** [terrylinooo/githuber-md#26]
On the default Guttenberg editor, I am able to create hyperlinks that open in a new tab. On the markdown editor, this option doesn't exist. 

When I create a hyperlink that opens in a new tab on the Guttenberg editor and preview it, it works as intended. When I switch to the Markdown editor and I preview the content, the links open in the same tab (they lose their open-in-a-new-tab property).

**Comment by edoreld** [comment]
For anyone else having this issue, the plugin "Open external links in a new window" is a temporary workaround.

**Comment by terrylinooo** [comment]
I will make a option in setting page that allows users to choose their preferred method to open a hyperlink, opening on the same window or new window. 

This feature is trigged by JavaScript so no need to make change to the post content.

**Comment by terrylinooo** [comment]
This feature will be released in 1.6.3, scheduled today.
