### ISSUE TITLE
wordpress 使用 highlight 高亮，代码不显示行号

### ISSUE THREAD

**Issue by qinLess** [terrylinooo/githuber-md#262]
wordpress 使用 highlight 高亮，代码不显示行号，请问下怎么修改
本人对 php  js 不太熟悉，研究了半天源码也没啥突破，特来请教下作者

![image](https://user-images.githubusercontent.com/33449905/143478834-457fc574-140d-4c2c-b030-178ec9b7948e.png)

**Comment by KeyboardMan1996** [comment]
可以选择高亮主题，主题中有支持行号的主题，
