### ISSUE TITLE
当插件启用时，无法自动保存草稿

### ISSUE THREAD

**Issue by xuejianxianzun** [terrylinooo/githuber-md#267]
**如果沒有提供以下詳細資訊，您開立的問題回報會被無視。**

**問題或臭蟲**

当启用这个插件时，不会自动保存草稿，也无法读取 WordPress 自动保存的草稿。

**如何重現**

請告知重現此問題的步驟回何：

1. 当启用这个插件时，编辑一篇文章，在里面输入新的内容，但不点击自动保存。
2. 过几分钟后刷新页面，发现新输入的内容没有出现。（没有手动保存的内容全部丢失了）

通过开启和关闭这个插件来验证的操作：

1. 关闭这个插件，建立一个测试文章，只输入标题和第一行，然后手动保存草稿。
然后输入新的内容，但不点击“保存草稿”按钮。
![QQ截图20220110063202.png](https://s2.loli.net/2022/01/10/NfRK1Q3AlIXLikb.png)
2. 过几分钟后，刷新页面，发现新添加的内容依然存在，说明 WordPress 确实自动保存了草稿。（根据一些资料，WordPress 默认每隔 60 秒保存一次草稿）
3. 启用这个插件，然后刷新编辑文章的页面，发现此时编辑器里没有出现新添加的内容，只有手动保存草稿时的内容。
![QQ截图20220110063306.png](https://s2.loli.net/2022/01/10/eEcSvB8IziZTOtU.png)

**預期的行為或結果**

我希望启用这个插件时，能够自动保存草稿，也能正常的读取草稿。

**畫面截圖**

见上图。

**伺服器環境**

 - WordPress 版本 5.5.8
 - WP Githuber MD 版本 1.16.1 （上一个 issues 我没有更新到最新版本，现在已经更新了，问题依旧）
 - PHP 版本 php7.0-fpm

**用戶端環境**

 - 作業系統 Debian 9
 - 瀏覽器 Chrome 97

浏览器控制台只有两个关于头像加载失败的错误，没有关于此问题的错误。

**Comment by xuejianxianzun** [comment]
追加说明：
在进行这些测试之前，已经确认关闭了这个插件的 “停用自动储存” 的选项，并且也点击了设置页面底部的“保存更改”按钮。
![QQ截图20220110065611.png](https://s2.loli.net/2022/01/10/blq7H8y2dU4VheP.png)

**Comment by xuejianxianzun** [comment]
追加信息：
我更新 WordPress 到最新版本，之后进行测试，但是这个问题依然存在：
```
当启用这个插件时，编辑一篇文章，在里面输入新的内容，但不点击自动保存。
过几分钟后（最后一次测试大概是 3 分钟）刷新页面，发现新输入的内容没有出现。（没有手动保存的内容全部丢失了）
```
![QQ截图20220110070149.png](https://s2.loli.net/2022/01/10/sSdKQi5rlXFJ28f.png)

**Comment by xuejianxianzun** [comment]
追加信息：
我发现之前的设置里没有勾选 “文章”
```
启用 Markdown 编辑器的内容类型    文章
```
我勾选之后进行测试，问题依旧。

**Comment by xuejianxianzun** [comment]
我看到这个项目的 readme 里建议关闭自动保存：
>My personal suggestion is to turn off revision and auto-save, there are options in setting page.
我不太理解。这样的话岂不是很容易丢失草稿？

**Comment by xiaoouwang** [comment]
很可惜作者好像不维护了，我也有这个问题，感觉很不开心

**Comment by xuejianxianzun** [comment]
> 很可惜作者好像不维护了，我也有这个问题，感觉很不开心

前两天我新建文章时，又因为这个问题丢失了草稿，不得不重新写。发生这种情况的时候确实很令人伤心。
以后我在其他编辑器里写草稿吧，最后粘贴过来直接发布算了。
