### ISSUE TITLE
[Enhancement] Add support for image alignment

### ISSUE THREAD

**Issue by edoreld** [terrylinooo/githuber-md#27]
Sometimes we want to align an image to the right or left of the text. This can be achieved by adding an image like so:

<img align="right" src="src-of-img></img>

Right now in order to achieve this, we need to input the tag and attributes manually. It would be great if the plugin had an option for it.

**Comment by terrylinooo** [comment]
Markdown text should be as simple as possible. You can customize your needs by using HTML.

## Feature request #17 

Adding new option when using `Add media` -> `Insert to post` that allows user insert HTML into post.
This option only works when `HTML Decode` is on.

![image](https://user-images.githubusercontent.com/11989371/53787421-c3bb9300-3f59-11e9-9360-9f669d3f90fb.png)
