### ISSUE TITLE
當使用prism高亮時會導致mermaid的區塊產生錯誤

### ISSUE THREAD

**Issue by KiraiChang** [terrylinooo/githuber-md#271]
**臭蟲**

當使用 prism 語法高亮時 mermaid 會顯示錯誤的圖示。

**如何重現**

使用以下內容
```csharp
var item = 0;
```

```mermaid
graph TD
A[Hard] -->|Text| B(Round)
B --> C{Decision}
C -->|One| D[Result 1]
C -->|Two| E[Result 2]
```

**預期的行為或結果**

 1. 正常顯示語法高亮
 2. 正常顯示 mermaid
 
**畫面截圖**

<img width="557" alt="image" src="https://user-images.githubusercontent.com/11284463/154231381-9d7a934d-ff0a-4018-a5e7-4bc1fb711eec.png">

**伺服器環境**

 - 5.9
 - 1.16.1
 - 7.4

**Comment by Redstone1024** [comment]
这可能是 prism 版本过低导致的。

**Comment by intMojIBakE** [comment]
Same problem here, with version 1.16.1
