### ISSUE TITLE
使用prism.js或highlight.js无法代码高亮，也无法显示行号

### ISSUE THREAD

**Issue by 361way** [terrylinooo/githuber-md#273]
使用prism.js或highlight.js无法代码高亮，也无法显示行号 ，like this page [无法高亮页面](https://www.361way.com/docker-install-gitlab/6659.html)

**Comment by KeyboardMan1996** [comment]
这个方法也许可以解决你的问题[http://cppdebug.com/archives/438](http://cppdebug.com/archives/438)

**Comment by dabinn** [comment]
我也是沒法顯示行號
後來去抓新版Prim.js(1.29)取代githuber裏面的1.23版
https://github.com/PrismJS/prism/releases
似乎就都正常了
取代的路徑：
wp-content\plugins\wp-githuber-md\assets\vendor\prism

**Comment by 21888** [comment]
> 我也是沒法顯示行號 後來去抓新版Prim.js(1.29)取代githuber裏面的1.23版 https://github.com/PrismJS/prism/releases 似乎就都正常了 取代的路徑： wp-content\plugins\wp-githuber-md\assets\vendor\prism

这个办法貌似可以
