### ISSUE TITLE
在手机视图无法正常编辑

### ISSUE THREAD

**Issue by xhlgr** [terrylinooo/githuber-md#274]
**問題**

1. 手机输入法输入每行（除了第一个字）都会在该行之前产生一个换行。（手机外接键盘输入英文字母没有产生换行，其他键会换行。电脑Chrome F12手机视图不能复现此问题）【在手机FireFox浏览器中输入无异常】

2. 在编辑器内容与工具栏之间好像有空白，手机视图可见“关闭标签”按钮。
- 关闭按钮是"ed_toolbar"的内容。不知道具体用途，用简单粗暴的方法加`$("#ed_toolbar").hide();`隐藏，隐藏后手机视图不会看到按钮。
- 编辑器行号与工具栏之间有空白。后来发现好像是内容和预览对齐需要，只是行号的背景灰色没有与工具栏相连，可以忽略此问题。

**如何重現**

在手机浏览器使用此编辑器键入内容。

**預期的行為或結果**

在手机视图也能正常编辑。

**畫面截圖**

![Screenshot_20220325_204127_com android chrome](https://user-images.githubusercontent.com/21972886/160125572-2196a433-14ab-4804-adc0-b639158ba9ad.png)

**伺服器環境**

 - WordPress 5.9.2
 - WP Githuber MD 1.16.1
 - PHP 7.4

**用戶端環境**

 - 安卓
 - Chrome

**Comment by 66Leo66** [comment]
2022/08/86 可复现输入字符自动换行，其他未测试。

Markdown 6.0.1, WP Githuber MD 1.16.1, Kiwi Browser 101.0.4951.40 (正式版本) （64 位）
