### ISSUE TITLE
Footnotes not supported?

### ISSUE THREAD

**Issue by gnolaum** [terrylinooo/githuber-md#284]
**Any issue will be ignored if you don't provide the following detailed information.**

**Describe the bug**

Markdown style footnotes do not render correctly (or at all) as footnotes should. This plugin appears to not support markdown footnote syntax at all.

**To reproduce**

Write a markdown footnote like this[^a]. Add another footnote here[^b]. These should show up at the bottom.

[^a]: footnote details are to be numbered and listed below
[^b]: second footnote should be numbered

**Expected behavior**

This should translate to a superscript that is numbered in order. I note that when I preview this (with markdown enabled here, the footnotes work as expected, but with the wordpress plugin, they do not work for my website.

**Screenshots**

![footnote](https://user-images.githubusercontent.com/62186911/170913373-0a23aa45-e52b-4b54-9e99-2587a1d0b40f.png)

**Server environment**

 - WordPress version 6.0
 - WP Githuber MD plugin version 1.16.1
 - PHP version 7.4.28

**User environment**

- Server architecture | Linux 4.19.150-76.ELK.el6.x86_64 x86_64
- Web server | Apache
- PHP version | 7.4.28 (Supports 64bit values)

**Additional context**

I don't see footnote syntax being recognized at all even though I have the Markdown Extra support enabled.
![enabled](https://user-images.githubusercontent.com/62186911/170914166-35b3aeb3-f3a4-4505-b26f-81b0764f6327.png)

**Comment by lulalala** [comment]
According to https://github.com/terrylinooo/githuber-md/issues/22 footnote was once supported, so I think it would be great to fix or clarify footnote support.
