### ISSUE TITLE
Is it possible to parse  &lt; and  &gt; ?

### ISSUE THREAD

**Issue by johnson4932** [terrylinooo/githuber-md#29]
嗨！不好意思，冒昧請問一下。

因為目前在 Wordpress 的文章中，如果要呈現 `HTML` 等語法需要做字元轉換才能正常顯示 `<` and  `>` ，不知未來是否有可能在編輯器中新增自動轉換的功能。

謝謝

**Comment by terrylinooo** [comment]
我可以在 toolbar 新增插入HTML 的功能。有需要的話可以做進去。

**Comment by terrylinooo** [comment]
Hello. I have updated it. Please download it and try again,
