### ISSUE TITLE
Front-end markdown rendering wrong

### ISSUE THREAD

**Issue by nielspeen** [terrylinooo/githuber-md#293]
Look for this sentence:
> Place the script below in ```/mnt/data/on_boot.d``` and call it ```extraip.sh```.

My markdown and the preview in the editor are displayed correctly as expected:

![md1](https://user-images.githubusercontent.com/5564176/193447768-2e533859-5a7f-4f8d-b031-3e76ef19d092.png)

However, the final rendering on the website is wrong:

![md2](https://user-images.githubusercontent.com/5564176/193447780-23577c2a-01a7-4f53-a6fd-ec00c6867cf7.png)

This happens with every theme I tried, including **Mynote** theme and **Twenty Twenty-two**.

**Comment by derawi** [comment]
I have the same issue with twenty twenty-one theme. Codeblocks and notes are not rendering
