### ISSUE TITLE
代码块标记为 Latex 语法时，在文章中并没有渲染出代码块。同时部分高亮主题会出现没有代码块 但是仅有高亮的情况

### ISSUE THREAD

**Issue by SauberQAQ** [terrylinooo/githuber-md#299]
插件版本：1.16.1 开启 Highlight.js 高亮
Wordpress版本：6.1.1 
主题 Argon主题 关闭主题中的代码块高亮模块

![1673249532782.png](https://img1.imgtp.com/2023/01/09/Ic5x7rWQ.png)

**Comment by KKK114514** [comment]
我也遇到了这个问题，请问您解决了吗？
