### ISSUE TITLE
截至 1.16.2 代码高亮模组使用 prism.js 仍然存在的问题

### ISSUE THREAD

**Issue by ConnersHua** [terrylinooo/githuber-md#304]
**如果沒有提供以下詳細資訊，您開立的問題回報會被無視。**

**問題或臭蟲**

首先非常高兴看到项目的维护有了新的进展，也感谢作者长期以来的开发工作。

主要是想反馈在使用代码高亮模组 (prism.js) 时，一些语言代码块的高亮和行号存在不工作的问题

通过编辑器界面添加代码块时，对可选语言的测试（如存在列表以外的语言则未进行测试），出现问题的语言有：
1. asp: 高亮及行号
2. css: 行号
3. delphi: 高亮及行号
4. html: 行号
5. javascript: 行号
6. objective-c: 高亮及行号
7. rst (reStructuredText): 高亮及行号
8. xml: 行号

注：如 asp、objective-c 这样高亮失效的语言，通过控制台可以看到 404 错误，如：`http://example/wp-content/plugins/wp-githuber-md/assets/vendor/prism/components/prism-objective-c.min.js`

**如何重現**

請告知重現此問題的步驟回何：

1. 
2. 
3. 
4. 

**預期的行為或結果**

清楚的說明您預期什麼樣的結果才是正常。

**畫面截圖**

1. 請提問題發生時的截圖
2. 例如按 F12，查看 Google Chome 開發人員工具的畫面有無紅色字樣錯誤訊息。

**伺服器環境**

 - WordPress 版本 6.2.2
 - WP Githuber MD 版本 1.16.2
 - PHP 版本 7.4

**用戶端環境**

 - 作業系統 Windows 11
 - 瀏覽器 Firefox

**其它說明**

如果有的話，請提供。

**Comment by yzhpxd** [comment]
代码复制在其它主题也没用，但在作者的mynote主题是可以的

**Comment by ConnersHua** [comment]
纠正一下之前汇报的错误，在之前的汇报中我以为在 Console 中出现 404 的 js 错误提示是造成高亮失效的原因，但其实不是，关于行号失效主要有几个问题：
1. 如 asp、objective-c 这样的与实际 js 文件名 (即 `wp-githuber-md/assets/vendor/prism/components` 下的文件名) 不符合导致调用 404
以 asp 为例，实际存在的文件名为 `prism-aspnet.min.js` 及 `prism-aspnet.min.js`，而调用的是 `prism-asp.min.js` 所以失效，同样的  objective-c 调用的是 `objective-c.min.js` 而实际存在的文件名为 `prism-objectivec.min.js`
**在将 `wp-githuber-md/assets/vendor/prism/components` 目录下的文件名改成与调用文件名一致后行号功能正常**；
2. 如 delphi 和 rst (reStructuredText) 是压根没有对应的 js 文件，所以调用 `prism-delphi .min.js`、`prism-rst.min.js` 出现 404；
3. 如 javascript 这样存在实际文件名，但是没有相关请求；

目前不会 php 所以没办法更进一步，烦请作者有时间修复一下，谢谢

**Comment by terrylinooo** [comment]
謝謝回報，我再查看

**Comment by Nyx1197** [comment]
xml 行号问题我已经解决, 可以参考这个提交本地测试一下
https://github.com/terrylinooo/githuber-md/pull/320/commits/b75e6eef25b1a9fe0c15822b45cbff24a197a86d

其他语言我稍后测试一下

**Comment by Nyx1197** [comment]
我本地测试, 关掉 prism-autoloader 加载优化之后测试结果如下:

asp: 高亮及行号                             不行, 改为html后html部分有着色, 行号正常
css: 行号                                        正常
delphi: 高亮及行号                         报错, 找不到js, 搜索Prismjs源代码没有找到 `language-delphi` 相关的内容, 疑似不支持delphi
html: 行号                                      正常
javascript: 行号                               正常
objective-c: 高亮及行号                  正常
rst (reStructuredText): 高亮及行号   没使用过该语言 搜索Prismjs源代码没有找到 `language-rst` 相关的内容, 疑似不支持rst
xml: 行号                                        正常
