### ISSUE TITLE
代码高亮和复制，只能在mynote主题下才可，其它主题如何才可有效？

### ISSUE THREAD

**Issue by yzhpxd** [terrylinooo/githuber-md#305]
照片复制粘贴在其它主题没有问题，但代码高亮加复制其它主题没用，能告知下如何做才可以？

**Comment by ConnersHua** [comment]
代码复制我个人在第三方主题没有遇到过问题，代码高亮除了我在 #304 中汇报的问题在第三方主题也是可用的，你需要在三个反引号后指定语言，如：
```
```bash
```

如果只是留空的反引号则不会有高亮

如果加上了还是不正常，就需要查看 Console 是否有报错了
