### ISSUE TITLE
工具栏消失

### ISSUE THREAD

**Issue by bookzhan** [terrylinooo/githuber-md#306]
**如果沒有提供以下詳細資訊，您開立的問題回報會被無視。**

**問題或臭蟲**

清楚的說明問題發生的情況及結果。

**如何重現**

請告知重現此問題的步驟回何：

1. 在编辑的过程中，内容大概有1页多，按Enter键后，工具栏消失了一半，刷新整个页面才能出来
2. 
3. 
4. 

**預期的行為或結果**

清楚的說明您預期什麼樣的結果才是正常。

**畫面截圖**

<img width="1466" alt="image" src="https://github.com/terrylinooo/githuber-md/assets/11169519/959700d6-05dc-4c3d-a579-40dd6eb1e841">

1. 請提問題發生時的截圖
2. 例如按 F12，查看 Google Chome 開發人員工具的畫面有無紅色字樣錯誤訊息。

**伺服器環境**

 - WordPress 版本 6.2.2
 - WP Githuber MD 版本 1.16.1 和1.16.2都试过，都有这样的问题
 - PHP 版本 7.4.3-4ubuntu2.17 

**用戶端環境**

 - 作業系統 Linux 5.4.0-137-generic x86_64
 - 瀏覽器 Chrome

**其它說明**

如果有的話，請提供。

**Comment by terrylinooo** [comment]
您好，按 F12，查看 Google Chome 開發人員工具的畫面有無紅色字樣錯誤訊息，這邊有 JavaScript 的錯誤嗎?
看到您用 Linux 的 Chrome，目前我手上沒有裝 Linux 桌面環境的電腦，您可以用 Window 的環境登入試試，讓我參考。

**Comment by bookzhan** [comment]
我的wordpress是运行在Linux，的我是在MAC上用Chrome访问，Chrome版本：114.0.5735.198
<img width="913" alt="image" src="https://github.com/terrylinooo/githuber-md/assets/11169519/2fa5e055-93ea-4dc0-80dc-fa3e0665d25c">

**Comment by terrylinooo** [comment]
謝謝你的截圖，大概知道那邊出了問題。WordPress 是預載 jQuery 的，這邊是 jQuery 沒定義，我再調查一下。稍候有結果再回覆您
