### ISSUE TITLE
偏好设定- 链结开启方式设置无效

### ISSUE THREAD

**Issue by jssolo** [terrylinooo/githuber-md#307]
偏好设定- 链结开启方式里设置为 在新视窗中开启 无效，链接还是会在当前页面打开
wordpress版本为6.2.2
PHP版本是8.1

**Comment by terrylinooo** [comment]
您好，請用，瀏覽器的 debug console  有紅色的 JavaScript 錯誤訊息嗎?

**Comment by jssolo** [comment]
> 您好，請用，瀏覽器的 debug console 有紅色的 JavaScript 錯誤訊息嗎?

![12222](https://github.com/terrylinooo/githuber-md/assets/40593549/f1990e37-bace-43d6-923d-0894f6122d4f)
打开文章时，控制台只有这个错误

**Comment by jssolo** [comment]
第二个报错解问题解决了，但是链接还是无法使用新的标签页打开，我看文章的源码没有target="_blank"属性，个人感觉是markdown语法转存html代码时出现的问题
