### ISSUE TITLE
关于链结开启方式的问题

### ISSUE THREAD

**Issue by cnlancehu** [terrylinooo/githuber-md#308]
#### 问题如下

把链接开启方式设置为**在新视窗中开启**后，wordpress中的所有链接(不仅局限于文章)都在新窗口开启

#### 预期的行为

在选择**在新视窗中开启**后，仅文章中的链接在新视窗开启
![image](https://github.com/terrylinooo/githuber-md/assets/106385654/3c389295-f8e8-425a-8b0b-5ef1ae8c9571)

#### 截图

页面中的其余元素都被设置为在新窗口开启

开启前
![image](https://github.com/terrylinooo/githuber-md/assets/106385654/50322224-91e3-461b-bc4c-beae1d42b500)

开启后
![image](https://github.com/terrylinooo/githuber-md/assets/106385654/d5cc3c68-5c30-43a8-9667-7e240f3438c4)

#### 运行环境

 - WordPress 版本 6.2.2
 - WP Githuber MD 版本 1.16.2
 - PHP 版本 8.0
 - 主题 [Theme Argon](https://github.com/solstice23/argon-theme)

#### 客户端环境
 - 系统 Windows 11
 - 浏览器 MS Edge 114.0.1823.82

**Comment by terrylinooo** [comment]
謝謝，右上角有一個紅色 x ，那邊我我點過去看一下訊息。

**Comment by cnlancehu** [comment]
是关于主题的，和插件无关
![image](https://github.com/terrylinooo/githuber-md/assets/106385654/d19617a5-07ed-42e3-8b65-41bf15d3db7b)

**Comment by terrylinooo** [comment]
喔，我看懂你的問題的意思了。這個問題，我再更新修正。謝謝你的回報

**Comment by jssolo** [comment]
我有遇到关于链接打开方式的问题，不过我的和你相反，我的是设置的新标签打开链接不生效

**Comment by IYATT-yx** [comment]
> 我有遇到关于链接打开方式的问题，不过我的和你相反，我的是设置的新标签打开链接不生效

我也是遇到了，这个可能和主题有关，我换了其它主题又可以了

**Comment by jssolo** [comment]
> > 我有遇到关于链接打开方式的问题，不过我的和你相反，我的是设置的新标签打开链接不生效
> 
> 我也是遇到了，这个可能和主题有关，我换了其它主题又可以了

我使用的是CorePress Pro 主题
