### ISSUE TITLE
请问我使用的主题为何某些地方会出现代码格式不正确问题

### ISSUE THREAD

**Issue by hausen1012** [terrylinooo/githuber-md#309]
正常应该是显示这样。
![image](https://github.com/terrylinooo/githuber-md/assets/50026605/459f6062-4261-45b2-aae0-e8c6fba1b2ff)
在我的主题显示这样
![image](https://github.com/terrylinooo/githuber-md/assets/50026605/f798cabe-7322-41fd-88d5-da503c7bdb30)
我的博客地址：https://www.amjun.com/1988.html

万分感谢！！！！

**Comment by devcui** [comment]
如何解决的?

**Comment by hausen1012** [comment]
我这是因为开启主题提供的中文智能摘要
