### ISSUE TITLE
Escape < and > on markdown code 

### ISSUE THREAD

**Issue by ntorgagd** [terrylinooo/githuber-md#31]
Setup: LiteSpeed Web Server, PHP 7.2, WordPress 5.1.1, GithuberMD 1.7.2, theme "Underscores.me".

---

Hello there,

First, thanks for your contribution to WordPress community. Your plugin is rock solid and the best editor I have ever used.

On the website I'm working on, we use tons of < html > tags and on the live preview, it's fine:
http://i.imgur.com/hD2cBVE.png

However, on the post_content, it's being saved as plain "<" instead of "&alt;"
http://i.imgur.com/Dm4PP4U.png

I do see some Issues report mentioning < and >, but none seem to be related to how the content is displayed on the page or saved on the database.

In my case, the theme does not filter the content of post_content, so the code is embedded on the page as a real html code:
http://i.imgur.com/HP24Pdv.png

I'm not sure if this is expected or if the theme is suppose to filter the html tags inside < code >. If these are the cases, please apologize for reporting incorrectly.

I tried with and without code syntax highlight module enable, tried to update the articles after the changes and the result is the same.

Any feedback would be appreciate. Again, I'm sorry if this is not plugin related and thanks for your time.

Have a nice day.

Regards,
Northon

**Comment by terrylinooo** [comment]
Thanks for your feedback, I will fix it in next version (1.7.3) 
Any update I will mention you here.

**Comment by terrylinooo** [comment]
Hello. I have updated it. Please download it and try again,

**Comment by ntorgagd** [comment]
@terrylinooo just to let you know, this issue is back on 1.11.1 (last version), I had to rollback to 1.10.0 for now.

**Comment by terrylinooo** [comment]
Just tested. 

![image](https://user-images.githubusercontent.com/11989371/57723056-61e67a80-76ba-11e9-98d1-1668aa4856bf.png)

It works as expected. Not sure about the issue you met. Could you provide me some examples, I will check it again.

**Comment by ntorgagd** [comment]
Try this text:
https://pastebin.sucuri.net/i75vkrtdc8ns2

It will look okay on the live preview, but once saved, it'll break the post on the front-end. It does not happen on v1.10.

**Comment by terrylinooo** [comment]
已更新。謝謝回報。

**Comment by ntorgagd** [comment]
Thanks, seems to have fixed now!

**Comment by terrylinooo** [comment]
也謝謝您細心回報。幫助這個插件更好。
