### ISSUE TITLE
无法引用外部图片url进行渲染

### ISSUE THREAD

**Issue by Seekers9** [terrylinooo/githuber-md#311]
![1](https://github.com/terrylinooo/githuber-md/assets/60725069/42910c01-1ec1-4fad-8796-497c7200b975)
![2](https://github.com/terrylinooo/githuber-md/assets/60725069/6b38df67-2773-4790-adea-eb78a56de281)
![3](https://github.com/terrylinooo/githuber-md/assets/60725069/cd0f8290-a933-426a-9a7c-1f3d199e5fcd)
存在gitee上的图片无法在文章打开，
1. 通过浏览器，图片链接可以直接打开
2. 使用插件写作时实时渲染错误
3. 已尝试图片复制模块，无法成功
4. 无法达成引用外部url进行渲染在文章中查看

#### 客户端：
- win10
- edge版本：115.0.1901.188
  
#### 环境：
- wordpress：6.2.2
- 主题：mynote
- wp githuber md版本：1.16.2
- PHP 7.4.33

**Comment by Seekers9** [comment]
已解决，是gitee访问问题

**Comment by Seekers9** [comment]
已解决，是gitee访问问题

**Comment by hutao01-miku** [comment]
咋解决的，我的也是gitee中图床放到wordpress中就不行了

**Comment by hutao01-miku** [comment]
> 咋解决的，我的也是gitee中图床放到wordpress中就不行了

是因为gitee有防盗链么，麻了

**Comment by Seekers9** [comment]
> > 咋解决的，我的也是gitee中图床放到WordPress中就不行了
> 
> 是因为gitee有防盗链么，麻了
你可以尝试在图片链接后加上斜杠/
参考：https://www.seeker-blogs.cn/markdown%e6%97%a0%e6%b3%95%e5%bc%95%e7%94%a8%e5%92%8c%e8%ae%bf%e9%97%aegitee%e5%9b%be%e7%89%87%e5%8e%9f%e5%9b%a0%e5%88%86%e6%9e%90/
