### ISSUE TITLE
希望能支持直接粘贴图片

### ISSUE THREAD

**Issue by magicdmer** [terrylinooo/githuber-md#314]
感谢开发这么好用的编辑器， 希望能支持复制图片后，直接粘贴到编辑器，自动上传生成图片链接

**Comment by terrylinooo** [comment]
這個功能已經有喔。

**Comment by magicdmer** [comment]
> 這個功能已經有喔。
我网上复制图片后，粘贴没反应😂，我后面再试试

**Comment by magicdmer** [comment]
还是不行，下面是我的录像测试：

https://github.com/terrylinooo/githuber-md/assets/5556368/e4083e66-7185-45ef-8bc0-ada2eaaba712

**Comment by IYATT-yx** [comment]
插件设置-模组-图片粘粘，是不是没打开

**Comment by magicdmer** [comment]
> 插件设置-模组-图片粘粘，是不是没打开

的确。。，有两个选项都要勾选，之前不知道为啥我傻逼了一直没注意，可能我当时以为这个是图床功能
