### ISSUE TITLE
Bulk HTML to Markdown Converter

### ISSUE THREAD

**Issue by ntorgagd** [terrylinooo/githuber-md#32]
Hello there,

This is a suggestion, not an issue, but I don't see a better place to add. Currently I'm working with 1k articles imported via CSV and they were originally written with HTML tags, so I'm using the HTML -> MD converter in order to adjust the articles.

Would it be possible to add in the future a feature to allow converting older posts into MD format in bulk?

By the way, thanks for the help on #31, it's working as expected now.

Have a nice day!

Regards,
Northon

**Comment by terrylinooo** [comment]
@ntorgagd

It is easy to do this but not guarantee that all converted results work as expected, if your posts contain complex HTML structure. Users use auto-save mostly, once they convert all posts and edit post, auto-save may save the converted content they don't want, so it is at risk for users.
