### ISSUE TITLE
SQL syntax highlighting

### ISSUE THREAD

**Issue by klspstck** [terrylinooo/githuber-md#328]
**Any issue will be ignored if you don't provide the following detailed information.**

**Describe the bug**

*A clear and concise description of what the bug is.*

When using code blocks with highlight.js or prism.js for SQL only lowercase keywords are highlighted.
ANSI specifies SQL keywords should be in UPPERCASE.

At least both cases should be highlighted.

It is not an issue with highlight.js, because on their github issue page both cases are highlighted properly.
I raised an issue there, too.

**To reproduce**

*Steps to reproduce the behavior:*

1. install and activate the plugin
2. Go to Settings -> Wp Githuber MD -> Modules
3. Choose "highlight.js" to be enabled
4. Create a new page and paste in  the following code:

```sql
SELECT
  *
FROM table
;
```

```sql
select
  *
from table
;
```

**Expected behavior**

For me as an instructor only the first version is correct,
but there are some "SQL cracks" writing everything in lower case. ;-))

**Screenshots**

*If applicable, add screenshots to help explain your problem.*
![grafik](https://github.com/terrylinooo/githuber-md/assets/103197271/049af92a-5934-4a46-b691-1aaff3849e22)

**Server environment**
- Ubuntu 22.04.3 LTS
- Wordpress version 6.3.1
- Theme TwentyTwentyThree
- Plugin Version 1.16.2
-  PHP Version 8.1.2-1ubuntu2.14

**User environment**

 - Ubuntu 22.04.3 LTS
 - Browser Firefox 

**Additional context**

./.

**Comment by Nyx1197** [comment]
Try to clone least version code.

![图片](https://github.com/terrylinooo/githuber-md/assets/70554853/f705cbaf-e9a5-4799-ace4-3fe3672c446d)
I test it work ok.

I use prism.js, highlight.js not tested.

**Comment by klspstck** [comment]
html,body{background-color:#fff;color:#333;line-height:1.4;font-family:sans-serif,Arial,Verdana,Trebuchet MS;}I will give it a try, too.
Kind regards
Klaus P. StockStock & PartnerAdvanced Education GmbH-----------------------
Nyx1197 schrieb am 15.09.2023 09:12 (GMT +02:00):

Try to clone least version code.
 I test it work ok.
I use prism.js, highlight.js not tested.

**Comment by klspstck** [comment]
html,body{background-color:#fff;color:#333;line-height:1.4;font-family:sans-serif,Arial,Verdana,Trebuchet MS;}OK.
I tested it and the preview is showing the appropriate syntax highlighting with prism.
What is confuding is, the previes in  the editor is not showing capitalized keywords highlighted.
 
"highlight.js" is not working at all, not in the editor nor bthe page preview.
 
I will use "prism".
 
Thank you and kind regards
Klaus P. StockStock & PartnerAdvanced Education GmbH-----------------------
Nyx1197 schrieb am 15.09.2023 09:12 (GMT +02:00):

Try to clone least version code.
 I test it work ok.
I use prism.js, highlight.js not tested.
