### ISSUE TITLE
Trick to enable compatibility with Yoast SEO analysis

### ISSUE THREAD

**Issue by bridgeport** [terrylinooo/githuber-md#33]
Thanks for this great plugin.

By default the Yoast SEO plugin's ( https://github.com/Yoast/wordpress-seo ) readability analysis and focus keyword analysis doesn't work with your markdown plugin. But Yoast does work with Jetpack's markdown plugin.

Here's a technique to make Yoast SEO's analysis work with your plugin. Just place the following in a must-use plugin to trick Yoast into thinking Jetpack Markdown is installed:

```php
// Save the contents of the the following here: /wp-content/mu-plugins/fake-jetpack-markdown-existence.php
if (!class_exists('Jetpack')) { // Skip if Jetpack is really installed and activated.
    // Create a dummy Jetpack class.
    class Jetpack
    {
        public static function get_active_modules()
        {
            // Make the following happy:
            // /plugins/wordpress-seo/admin/formatter/class-metabox-formatter.php, WPSEO_Metabox_Formatter::is_markdown_enabled()
            return ['markdown'];
        }
    }
}
```

Of course, you can incorporate this into your own plugin so that it's compatible with Yoast.

You can probably go about this in a more surgical way, by checking if Jetpack is installed **and** if its markdown functionality is enabled. This'll allow your plugin, Yoast SEO, and Jetpack to coexist peacefully.

Thanks.

**Comment by terrylinooo** [comment]
Thanks for your feedback. I will make it in next update.

**Comment by terrylinooo** [comment]
The way you provided only works when users don't install Jetpack, but it causes another problem when users activate Jetpack. I will try to ask for Yoast's SEO to add a filter, so we can safely overwrite it.

![image](https://user-images.githubusercontent.com/11989371/55533432-d5709180-56e3-11e9-97f5-8783dc6f5e88.png)

![image](https://user-images.githubusercontent.com/11989371/55533725-d1913f00-56e4-11e9-921e-ba212bd99a92.png)
