### ISSUE TITLE
Page is not rendered as previewed

### ISSUE THREAD

**Issue by protoys-webdev** [terrylinooo/githuber-md#330]
I have just installed WP and Githuber MD WordPress Plugin (both latest versions). After enabling the Mermaid module and configuring GitHub MD to work on posts, I created a new post containing Mermaid Syntax. 

Example:
```mermaid
sequenceDiagram
    Alice ->> Bob: Hello Bob, how are you?
    Bob-->>John: How about you John?
    Bob--x Alice: I am good thanks!
    Bob-x John: I am good thanks!
    Note right of John: Bob thinks a long<br/>long time, so long<br/>that the text does<br/>not fit on a row.

    Bob-->Alice: Checking with John...
    Alice->John: Yes... John, how are you?
```

The live preview renders this just fine as a sequence diagram. However, page preview and published page only render a code block containing the mermaid code.

I guess this is a newbie mistake since I just started using both. Any suggestions for me?

**Comment by sbonaime** [comment]
I have the same problem with twenty-two and twenty-three theme. It is working with twenty-twenty. Any idea ? 
Thanks

**Comment by Nyx1197** [comment]
I fix it on my [repo](https://github.com/Nyx1197/githuber-md). You can clone it in your plugins dir, and enable local version.
plugins dir is `\wp-content\plugins`

Fix code can find in [https://github.com/Nyx1197/githuber-md/commit/0267f0ae2026811c479832a788b5dd301f8ea243](https://github.com/Nyx1197/githuber-md/commit/0267f0ae2026811c479832a788b5dd301f8ea243) and [https://github.com/Nyx1197/githuber-md/commit/cb341b652b506c68a2417e2b8776877e1218bad0](https://github.com/Nyx1197/githuber-md/commit/cb341b652b506c68a2417e2b8776877e1218bad0)

**Comment by Nyx1197** [comment]
I already create a pull request, and wait for merge.
