### ISSUE TITLE
MD Disappearing on save

### ISSUE THREAD

**Issue by DuckyDisciple** [terrylinooo/githuber-md#331]
**Any issue will be ignored if you don't provide the following detailed information.**

**Describe the bug**

After saving the post, the MD content no longer shows, but is converted to html. I have to manually click the Convert button each time I visit the page.

**To reproduce**

1. Save a post with MD
2. When the page refreshes, the content is back to html instead of MD

**Expected behavior**

It used to be that when the content saved it would stay as MD. I'm not sure what has changed, but I expect that the content automatically changes back to MD when the page loads.

**Screenshots**

<img width="938" alt="image" src="https://github.com/terrylinooo/githuber-md/assets/14015584/f3e70292-0f2e-4db9-8c34-149293cf325d">

**Server environment**

 - WordPress version 6.3
 - WP Githuber MD plugin version 1.16.1
 - PHP version 7.4

**User environment**

 - OS: Mac
 - Browser: Arc

**Additional context**

I have tried copying the data to a local setup as well and the same thing happens. I updated that plugin to the latest version and have the same issue.

**Comment by DuckyDisciple** [comment]
Update on this - it seems like this is only happening with custom post types. I can take the exact same content and paste it into a Post or into a custom post (which is enabled in the settings) and everything saves perfectly fine in the database. (Both have the MD in post_content_filtered and the html in post_content).

The problem is when I open a saved post, that content on the page is in MD format. When I open a custom post type, that content is in html format. I'm guessing there is a function somewhere that is hooked into a post loading and is supposed to swap the post_content and post_content_filtered, but is only doing it for the Post type instead of all supported CPTs.

**Comment by mac2net** [comment]
I had the same problem with a regular post type
