### ISSUE TITLE
\assets\vendor\prism\prism.min.js文件导致存在404请求

### ISSUE THREAD

**Issue by jssolo** [terrylinooo/githuber-md#336]
\assets\vendor\prism\prism.min.js文件最后有一行注释掉的sourceMappingURL参数，但是此参数会请求网站后台，但是没有对应的文件导致大量404
请求地址为/sm/7aef6e5e59a9e695905cadda29c0e64c2d4c6387cb155c84941baf4d0c06b74d.map

**Comment by Nyx1197** [comment]
方便发下域名看看吗?
我这边没有遇到相同的问题

**Comment by Nyx1197** [comment]
或者截图看下开发者工具, 看看是那边请求的

**Comment by jssolo** [comment]
我把对应文件里的注释代码删掉，就没有这个请求了，等等看其他人有没有遇到这个问题吧
