### ISSUE TITLE
Plugin doesn't properly install using composer and WordPress Packagist

### ISSUE THREAD

**Issue by bridgeport** [terrylinooo/githuber-md#34]
I opened an issue on the wpackagist github page before I realized your plugin had a github page. You can see it here:
https://github.com/outlandishideas/wpackagist/issues/294

In summary, I tried installing your plugin using composer and WordPress Packagist
```
"wpackagist-plugin/wp-githuber-md":"1.7.3"
```

It downloaded and appeared to install, but the list of plugins in the admin area didn't show your plugin, therefore I couldn't activate it. Here's the output of running `composer update`

```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing wpackagist-plugin/wp-githuber-md (1.7.3): Downloading (100%)
Writing lock file
Generating autoload files
```

Thanks.

**Comment by terrylinooo** [comment]
Thanks for your feedback, I will take a look for this issue.

**Comment by bridgeport** [comment]
I forgot to mention that I'm using this with Roots Bedrock:
https://roots.io/bedrock/
https://github.com/roots/bedrock

**Comment by terrylinooo** [comment]
I have no plan to support WordPress Packagist.
