### ISSUE TITLE
WP Githuber MD and bbpress tinymce bug

### ISSUE THREAD

**Issue by oubayun** [terrylinooo/githuber-md#343]
After the plug-in WP Githuber MD is enabled, "Disable the visual editor when writing" is checked by default, causing the front-end page bbpress tinymce to be abnormal. Is it possible based on "
Enable content type for Markdown editor" is a control?

**Comment by Zacksly** [comment]
I am also having this issue. This makes Icegram Express email unusable for me when Githuber MD is enabled. It throws an error that TinyMCE does not exist.
