### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by suifengpiaoyang** [terrylinooo/githuber-md#35]
你好，自动保存功能对我来说比较重要。当我把插件中的 Disable Auto-save 和 HTML-to-Markdown都关掉后，如果此时将 Sync Scrolling 关掉，我发现 Live Preview 好像有点问题还有此时的自动保存貌似失效了。

**Comment by terrylinooo** [comment]
Sync Scrolling  關掉，兩邊的下拉捲軸不會同步。

自動保存我還在檢查中。有任何更新我會在這裡告知。

**Comment by terrylinooo** [comment]
测试之后发现自动保存功能还是有的。不大确定您的问题点在那里。不过预览介面没有即时更新的问题已修复。在1.7.5版更新。

**Comment by terrylinooo** [comment]
WP Githuber MD [markdown 編輯器](https://wordpress.org/plugins/wp-githuber-md/) 1.80 已更新。
