### ISSUE TITLE
Markdown Editor Switcher not appearing in new post

### ISSUE THREAD

**Issue by picorealm** [terrylinooo/githuber-md#353]
The Markdown Editor Switcher button stopped appearing in new posts.  In Githuber MD settings Enable is set for Posts and Pages and Markdown Editor Switcher is enabled, but when I create a new post there is no editor switcher button.

**Comment by Flamenco** [comment]
This was happening to me, and I eventually realized there was a Wordpress (not plugin) setting that somehow was disabled.

<img width="1574" alt="Screenshot 2024-03-26 at 10 04 10 AM" src="https://github.com/terrylinooo/githuber-md/assets/819940/dc871b25-a6b2-4bbd-b3fb-7b6193304615">
