### ISSUE TITLE
希望加上對SM.MS圖床支持

### ISSUE THREAD

**Issue by quartz010** [terrylinooo/githuber-md#36]
你好，
在圖床的方面，希望加上對SM.MS 的支持，因爲不想登陸社交媒體，多謝

**Comment by terrylinooo** [comment]
@quartz010 Ok。在下一版加入。

**Comment by terrylinooo** [comment]
我已完成這個功能選項，請等待 1.7.5 版下載使用。

**Comment by terrylinooo** [comment]
已更新 WP Githuber MD [markdown 編輯器](https://wordpress.org/plugins/wp-githuber-md/) 為 1.8.0 版。

**Comment by quartz010** [comment]
謝謝作者的快速支持與響應XD 👍
