### ISSUE TITLE
能不能加上右侧抽屉 title 导航?

### ISSUE THREAD

**Issue by wyrover** [terrylinooo/githuber-md#37]
能不能加上右侧抽屉 title 导航 ?

**Comment by terrylinooo** [comment]
意思是小工具放在文章側邊欄?

**Comment by wyrover** [comment]
是 markdown 的 一级 二级 三级 标题 放在右侧当导航

# title1

## title 2

### titlte3

**Comment by terrylinooo** [comment]
Ok。 我會把它做成一個小工具 (widget) 讓用戶自行決定要出現的地方。

**Comment by terrylinooo** [comment]
預計在 1.9.0 版加入。

**Comment by terrylinooo** [comment]
已無成。有提示更新 1.9.0 版，更新後即可使用。

![image](https://user-images.githubusercontent.com/11989371/56504557-7b792400-654b-11e9-9535-536d8f4de43f.png)

要在模組打開。

假如對我設計的 TOC 的樣式，有修改的需求，

md-widget-toc 是在小工具區域
md-post-toc 是在文章區域

再自行在 theme 自定義 CSS 加入喜歡的樣式。

以下是範本。

```
.md-widget-toc, .md-post-toc {
	ul, ol {
		padding-left: 15px;
		margin: 0;

		ul, ol {
			padding-left: 2em;
		}
	}

	ul {
	
		ol {
			list-style-type: lower-roman;
		}
		ul ol, ol ol {
			list-style-type: lower-alpha;
		}
	}
	ol {
		ul, ol {
			padding-left: 2em;
		}

		ol {
			list-style-type: lower-roman;
		}

		ul ol, ol ol {
			list-style-type: lower-alpha;
		}
	}
}
```
