### ISSUE TITLE
HTML 標籤被轉譯

### ISSUE THREAD

**Issue by nczz** [terrylinooo/githuber-md#38]
Hello
無論有無開啟設定的「HTML 解碼」功能都會出現下列問題

後台：
![image](https://user-images.githubusercontent.com/5238961/55790080-3803cc00-5aee-11e9-8e79-f5ef48b757ce.png)
前端：
![image](https://user-images.githubusercontent.com/5238961/55790132-54a00400-5aee-11e9-9572-3b8172b49d49.png)

這問題在麻煩協助確認～

**Comment by terrylinooo** [comment]
已修正待版本更新
