### ISSUE TITLE
能否支持下简体中文

### ISSUE THREAD

**Issue by fyxt** [terrylinooo/githuber-md#39]
Can simplified Chinese be supported
能否支持下简体中文

**Comment by terrylinooo** [comment]
我再連絡簡體中文的翻譯管理員給我權限

fyxt <notifications@github.com> 於 2019年4月14日 週日 上午9:34 寫道：

**Comment by terrylinooo** [comment]
我有放一版簡體中文語言包在這個版。您試試。

**Comment by fyxt** [comment]
Thank  感谢
