### ISSUE TITLE
可以添加再转变成html自定义设置class 或 id 吗，方便个性化自定义展示效果样式

### ISSUE THREAD

**Issue by qq781548819** [terrylinooo/githuber-md#40]

**Comment by qq781548819** [comment]
例如 h1标签带上custom_h1
<h1> Test </h1>

**Comment by terrylinooo** [comment]
您只有打開 Markdown extra 的 extension 就可使用類似的語法來轉換

![image](https://user-images.githubusercontent.com/11989371/56119529-e9977700-5f9e-11e9-9004-e564d7b26c81.png)

![image](https://user-images.githubusercontent.com/11989371/56119579-003dce00-5f9f-11e9-8387-a463fd923d94.png)

或者您可以開始 HTML 解碼直接用 HTML

![image](https://user-images.githubusercontent.com/11989371/56119693-311e0300-5f9f-11e9-8c92-98297cc4cd47.png)

**Comment by terrylinooo** [comment]
如果沒特別的問題過幾小時候關閉此 issue。

**Comment by qq781548819** [comment]
感谢作者大大，您太客气了，开源软件还对提issue的拿来主义的家伙用敬词，这样会惶恐的！感谢

**Comment by qq781548819** [comment]
我还有一个问题，如果是使用上面的两种处理方案的话，那是不是说从数据源文章上面去破坏了文章的完整性，如果移植到别的markdown环境下，部分语义没法得到兼容处理而排版错误，我看过vuepress 是在转义的同时给固定的标签带上文章的标识，如
```
# Test
```
转换成：
```
独立出来属于文章的标签，方便开发者对自身文章样式定制化，而且也不会影响到文章的可移植性。这个是我的个人想法，也不知道对不对，再麻烦下作者指点下，拜托
<h1 class="md_h1_extra" id="md_h1_extra">Test</h1>
```

**Comment by terrylinooo** [comment]
Markdown extra 目前蠻受歡迎但支援還不普及。
但編寫 Markdown 還是越簡單越好。否則就失去 Markdown 原本便利易讀的優點了。

您的建議很好。我再想看看實作的方式。另一個角度想，WordPress 的文章都有定義 .post 這個 CSS class，假如需要客製樣式，例如 h2，可以試試 `.post h2 {}` 這樣的方式比較不影響文件本文的簡潔性。

**Comment by qq781548819** [comment]
好的，谢谢作者，没问题了，我关了。
