### ISSUE TITLE
Markdown 編輯區塊中有 HTML 標籤 code 會反解回一組閉合標籤

### ISSUE THREAD

**Issue by nczz** [terrylinooo/githuber-md#41]
Hello
如下附圖。

![image](https://user-images.githubusercontent.com/5238961/56119797-66c2ec00-5f9f-11e9-8649-af01d5cbdc33.png)

只要使用 inline code 的方式加入 HTML 標籤，就會在重新編輯的該篇文末被反解回一組 HTML 標籤。如果沒注意去更新文章就會導致那頁面結構出現異常。

再麻煩查看，謝謝

BTW, 很高興你拿回帳號了ＸＤ

**Comment by terrylinooo** [comment]
![image](https://user-images.githubusercontent.com/11989371/56120633-1ea4c900-5fa1-11e9-88e1-cdee04b406a3.png)

我測試可以喔。是不是有開 jetpack 的 Markdown @@?

**Comment by nczz** [comment]
@terrylinooo 很神奇，我把外掛都全關了剩 Markdown 這個還是有。但本機把一樣的文章貼上測試又沒有出現。ＸＤ

**Comment by terrylinooo** [comment]
#42  可能和這個也有關聯，我更新一版您再試看看喔。
