### ISSUE TITLE
两个独立的行间代码块里的*会使之间的文字变斜体

### ISSUE THREAD

**Issue by pessoalzy** [terrylinooo/githuber-md#42]
Hello，感谢你开发出这么棒的 MD 插件，功能完善而稳定，我在发现它之前都放弃在 Wordpress 直接用 MD 写了。不过，我在使用时发现，如果同一行的两个行间代码块中都有一个星号「*」，那么两个星号之间的文字会变成斜体。

例如：
```
一个 `*a` 另一个 `*b`
```

这样的一行的实际效果是「a` 另一个 」会以斜体显示。而不是

一个 `*a` 另一个 `*b`

请问可以修复这个问题吗？

另外，我发现在在启用了代码高亮之后，模组 - 代码高亮 - 布景主题 中设置的主题不会影响到行间代码块的显示情况。请问这是我使用的主题（[Twenty Sixteen](https://wordpress.org/themes/twentysixteen/)）的原因吗，我有什么办法让行间代码块同样使用在插件里设定的主题吗?

多谢~

**Comment by terrylinooo** [comment]
謝謝回報。這兩天我再找時間修復。

**Comment by terrylinooo** [comment]
另外一個問題，我在我的開發環境測試找不出問題。

![image](https://user-images.githubusercontent.com/11989371/56294141-04174f00-615d-11e9-8662-9616834e4e03.png)

您可否用 Chrome 開啟該頁面，然後按 F12 看看有沒有錯誤訊息之類的。(404) 

我先更新一版修正，如有發現第二個問題再另外修正。

**Comment by pessoalzy** [comment]
斜体的问题解决了，多谢了！

按 F12 没有出现什么报错。我是根据开启插件中的”布景主题”后行间代码的样式没有变化来判断它没有起效的，不知道“布景主题”中主题正常的效果可以在哪看到？“布景主题”是会对行间 (就是以两个“ ` "围起来的代码) 起效的吗？

 另外我好像又发现了新的问题，它好像是在这次更新之前就存在的。问题用截图来说明可能比较简单：

![image](https://user-images.githubusercontent.com/26316942/56308186-38990400-6179-11e9-9825-2dd25eacabd4.png)

![image](https://user-images.githubusercontent.com/26316942/56308304-92013300-6179-11e9-91f6-cbbdce13acf3.png)

截图中的上方是页面的显示内容，下方是这些内容在编辑器内对应部分的截图。一段内某个行间代码的 ” ` " 可能会被当普通符号处理，以至于两个行间代码之间的内容被当成了行间代码。不过，截图中这些在编辑器的即时预览中是正常显示的。另外，我选择的布景主题是 “tomorrow”，如果它应该对行间代码起效的话，这样显示是正常的吗？

我确认了一遍，应该没有其他问题了。麻烦您了~

**Comment by terrylinooo** [comment]
代码高亮只對區塊代碼生效喔。行間代碼無作用。例如：

![image](https://user-images.githubusercontent.com/11989371/56334404-b6393000-61ca-11e9-99ef-529e486d90ef.png)

**Comment by terrylinooo** [comment]
新的問題已證實，今天會修正。謝謝您的回報。

**Comment by terrylinooo** [comment]
我發現蠻多開發者的寫作需求常用到鍵盤按紐。所以我在下一版加入了擴充語法。

![image](https://user-images.githubusercontent.com/11989371/56349089-6e320180-61fa-11e9-8e64-d452d3442f8a.png)

它轉譯之後會在 ‵code‵ 標籤上加上 `kb-btn` 這個 CSS 樣式，如果您有使用，但不喜歡我內建的樣式，可以自行覆寫定義。
