### ISSUE TITLE
Can Markdown and WordPress Classic Editor coexist?

### ISSUE THREAD

**Issue by fyxt** [terrylinooo/githuber-md#43]
能实现Markdown和WordPress经典编辑器共存吗？
Can Markdown and WordPress Classic Editor coexist?

**Comment by fyxt** [comment]
Thank the author

**Comment by terrylinooo** [comment]
實作上能用 metabox (自訂區塊) 載入編輯器，但目前這個 plugin 已經有固定用戶，所以不考慮有大幅修改代碼及使用介面的情況，以避免用戶困擾。
目前只會小幅度增加功能及修正 issue。不然用戶看到版號更新會害怕是否該按下更新。

**Comment by fyxt** [comment]
好吧
