### ISSUE TITLE
Unable to insert linked mini-image

### ISSUE THREAD

**Issue by trejder** [terrylinooo/githuber-md#44]
In the newest version (1.8.5) it is not possible to insert images in smaller dimensions and a link to original image. You can only insert image without any link.

This fails:

![1](https://user-images.githubusercontent.com/2903392/56429953-01376e00-62c5-11e9-88c5-100da44671c9.jpg)

This works:

![2](https://user-images.githubusercontent.com/2903392/56429955-05fc2200-62c5-11e9-850f-9e4d7e2fafc0.jpg)

Please, verify and fix this, because without ability to insert images into blog post I must disable your plugin. Thank you.

**Comment by terrylinooo** [comment]
Thanks for your feedback. I will fix within a few days.

**Comment by terrylinooo** [comment]
This issue has been fixed in 1.8.6
Thanks for reporting.
