### ISSUE TITLE
表格无法转换成markdown

### ISSUE THREAD

**Issue by hxuf** [terrylinooo/githuber-md#45]
表格转换后只剩下文字，没有表格了。错误版本是1.8.5

**Comment by terrylinooo** [comment]
```
| aaa | bbb | ccc |
| --- | --- | --- |
| o | x | nnn |
| o | x | nnn |
| o | x | `dfssf` |
```

我測試正常，您試試以上。

**Comment by hxuf** [comment]
我的意思是原来是html生成的表格。想用编辑器里的转换成markdown这个不能转。

**Comment by terrylinooo** [comment]
ok。我再試試。有問題會在下版修正。感謝回報。

**Comment by terrylinooo** [comment]
已更新 1.8.6 版。

**Comment by hxuf** [comment]
已更新，能转换表格了。还有一个问题。就是原来居中的现在不自动居中了。

**Comment by hxuf** [comment]
| aaa | bbb | ccc |
| :---: | :---: | :---: |
| o | x | nnn |
| o | x | nnn |
| o | x | `dfssf` |
少第一行的2个冒号。

**Comment by terrylinooo** [comment]
不曉得您轉換前的HTML原始碼是什麼? 應該有定義自己的 CSS。轉換換的 HTML 是乾淨無樣式的表格。假如您要居中的話，必須加上  
```
.post td, .post th {
    text-align: center; 
}
```
讓表格內容居中。

**Comment by hxuf** [comment]
<t h align="center">需要居中的文字</t h>
是这样的。这个问题没关系。我可以再用typora转换一下。

**Comment by terrylinooo** [comment]
我比較建議您用佈景主訂的自定 CSS 去加入我剛剛說的樣式，這樣以後你想取消置中也很容易，不用再另外加入HTML語法。

**Comment by hxuf** [comment]
好的。我去修改下CSS。
