### ISSUE TITLE
网址中的& 会被解析成& amp；

### ISSUE THREAD

**Issue by hxuf** [terrylinooo/githuber-md#46]
如题

**Comment by terrylinooo** [comment]
在什麼情況下會被解析。
目前我測試在代碼區塊及非代碼區塊，連結不會被轉換為HTML字符。
還沒找到能重現這個問題的情況。
假如有更多的資訊，會比較好排除這個問題。
謝謝回報。

**Comment by hxuf** [comment]
这是标题](http://www.66.cc/6&1 "这是标题")
[
这样就会变成 http://www.66.cc/6&a m p;1

**Comment by terrylinooo** [comment]
謝謝。我再檢查，謝謝回報。

**Comment by terrylinooo** [comment]
我檢查了一下，發現那是 WordPress  的轉換機制。您試試傳統編輯器和古騰堡編輯器，都會把連結的 & 轉換成 轉換成 &amp;
```
<p><a href="http://www.66.cc/6&amp;1">http://www.66.cc/6&amp;1</a></p>
```
我查了一下 WordPress 的核心原始碼:

![image](https://user-images.githubusercontent.com/11989371/56470423-a777a500-6478-11e9-9fd8-fa3ef1774825.png)

它對網址的處理都是先把 & 轉成 &#038; 再轉成 &amp; 
我想核心碼這樣寫有它的用意。
瀏覽器和搜尋引擎對於兩種網址都視為同一個網址，這方面是不影響的。
假如您有需要的話，我可以把它做成一個偏好設定讓用戶決定是否把網址的 &amp; 轉回單一個 &。

**Comment by terrylinooo** [comment]
由於這個不是 bug，我把這個偏好設定放進 1.9.0 版中。

**Comment by hxuf** [comment]
好的，非常感谢！

**Comment by hxuf** [comment]
谢谢您，问题解决了。
