### ISSUE TITLE
Support for anchored headings

### ISSUE THREAD

**Issue by bynicolas** [terrylinooo/githuber-md#47]
Would be really useful to get support for on page heading anchors (add an ID to the heading tags).

This is what I'm talking about
https://gist.github.com/asabaylus/3071099

**Comment by terrylinooo** [comment]
WP Githuber MD supports **Markdown Extra**

![image](https://user-images.githubusercontent.com/11989371/56484924-747af300-6504-11e9-9b53-50765eee26fc.png)

```
## Heading {#test}
```
The above section will be rendered to:
```
<h2 id="test">Heading</h2>
```

**Comment by herrdeh** [comment]
Thanks for this useful hint! 
But it's only about the link target, would somebody be so kind and write how to write the correct origin link to point to the target?

Thanks a lot in advance, Wolf  
And thank you so much to provide this useful plugin-

**Comment by kmann3** [comment]
I know this is an older post but if you came here, like I did, the answer is this

`[Display Test here](#link_here)` - this is what you would use in, say, your table of contents

And below you would post

`Some Normal Text here {#link_here}` - and this is where you'd put your heading such as `## Some Normal Text here {#link_here}` where you want the user to end up

And while the preview rendering will NOT show it in the editing form - if you click preview and see how the actually renders the page then it works correctly.
