### ISSUE TITLE
Images are inserted in the end of document

### ISSUE THREAD

**Issue by trejder** [terrylinooo/githuber-md#49]
The #44 was truly resolved (thank you!) and images are now correctly inserted into post's text -- both regular images and miniatures linked with actual image -- but they are inserted in the incorrect position in the editor.

Currently (1.9.1) when using _Add image_ button, Markdown code for corresponding image is always inserted **in the end of text** (after last line) instead of being inserted at the current caret / cursor position.

This causes that you cannot insert images in desired place in the text. You always have to manually cut-and-paste them from the end to the required place.

**Comment by terrylinooo** [comment]
Okay. I will improve it.

**Comment by terrylinooo** [comment]
This issue has been fixed in 1.10.1
