### ISSUE TITLE
Embedding github gists

### ISSUE THREAD

**Issue by KevinEady** [terrylinooo/githuber-md#5]
Hi @terrylinooo ,

Great plugin! It's so easy to use! However, I was wondering if there is a feature to embed github gists? Or do you know of a plugin that work would simultaneously with this plugin? New to WordPress, so hope this makes sense.

Thanks, Kevin

**Comment by terrylinooo** [comment]
@KevinEady  

I'm glad you like this plugin. 
If you turn on **HTML Decode**, then you are able to put any HTML code in your post.

![image](https://user-images.githubusercontent.com/11989371/51723773-5a607e80-2095-11e9-9818-a3bddba70899.png)

For example:

![image](https://user-images.githubusercontent.com/11989371/51723849-97c50c00-2095-11e9-84e8-b0fe12c36c9f.png)

Frontend:

![image](https://user-images.githubusercontent.com/11989371/51723873-ac090900-2095-11e9-8f41-d95767ccd072.png)

Hope this helps.

**Comment by KevinEady** [comment]
Yup! That solved it! Thanks so much.
