### ISSUE TITLE
Gitbuber incorrectly reads Jetpack's settings

### ISSUE THREAD

**Issue by trejder** [terrylinooo/githuber-md#50]
WP Gitbuber MD suggests that Jetpack's Markdown support should be disabled:

![gitbubber-1](https://user-images.githubusercontent.com/2903392/56653219-7de39700-668d-11e9-9423-a1fddffb3568.jpg)

While it is already disabled:

![gitbubber-2](https://user-images.githubusercontent.com/2903392/56653232-850aa500-668d-11e9-9dc9-e342b2fe0e8e.jpg)

I can see Gitbuber's nag screen _every time_, I login to my Wordpress even though I have disabled Jetpack's Markdown support weeks ago (when installing WP Gitbuber MD for the first time). Using WP Gitbuber 1.9.1.

**Comment by terrylinooo** [comment]
Please check out your other installed plugins which are registered Jetpack markdown to the post types.

**Comment by trejder** [comment]
There are no such plugins in my Wordpress network. I am using only Jetpack's Markdown editor and yours.

This is clearly a problem with your plugin not with some kind of interruption by other plugins. Sorry.

**Comment by trejder** [comment]
This problem is not only fixed, but also becomes more and more annoying from version to version.

Before recent update I saw this warning:

- once per session,
- only on post editing screen.

Now, after recent update I see in EVERYWHERE and ALWAYS:

- I can close the message, save post's draft (i.e. reload screen) and I see it again,
- I can see it in post editing screen, posts list etc.

The "WP Gitbuber MD suggests you to disable Jetpack Markdown (or other Markdown plugins that use Jetpack Markdown module) to prevent conflicts" message becomes so intrusive and annoying than unless you fix this very soon or me and probably many more users will have no option like uninstalling your plugin.

Once more I will underline that this is problem with your plugin only:

- Jetpack's Markdown editor / feature is 100% sure disabled,
- I have no other Markdown editors except yours and Markdown's.

So there's got to be something with the code that you use to read Jetpack settings or otherwise checks, if Jetpack's or other Markdown editor is turned on. This code is incorrect, fails and returns true while it should return false -- no other Markdown editors are enabled.
