### ISSUE TITLE
Incorrect delimiter when underlining the same words

### ISSUE THREAD

**Issue by trejder** [terrylinooo/githuber-md#52]
Gitbuber underlines the same words, it finds in each text:

![wpg-1](https://user-images.githubusercontent.com/2903392/56719178-8517ad00-6740-11e9-8033-fde79f5b16a0.png)

Which is pretty cool feature (though you could think about giving an option to disable it).

The problem is that when determining "whole words" it does not use spaces (and other white characters) only as words delimiter, but all non-Latin characters instead:

![wpg-2](https://user-images.githubusercontent.com/2903392/56719259-ad9fa700-6740-11e9-80e5-c9e5bddf7e14.png)

Which produces a bit weird results.

**Comment by terrylinooo** [comment]
I will make an option that allows the users to disable the spell checker.
It will be added in the next update.

**Comment by terrylinooo** [comment]
Please update to 1.10.0

**Comment by trejder** [comment]
Thank you.
