### ISSUE TITLE
可否添加显示语言类型和复制到剪贴板的插件设置

### ISSUE THREAD

**Issue by allenjia09** [terrylinooo/githuber-md#53]
首先，感谢您制作了这么帮的插件。
本人小白鼠，希望可以添加显示语言类型和复制到剪贴板的插件设置，或者指导一下怎么启动这些插件。

**Comment by terrylinooo** [comment]
是指 `代碼高亮` 嗎?

**Comment by allenjia09** [comment]
嗯，是的。不过我刚才试了一下，只要在prismjs官网选好相应插件js生成文件替换到prism.min.js文件中就可以实现。

**Comment by terrylinooo** [comment]
這個特色會在今天更新加入。
prism.js  的展示很醜。我設計了幾款樣式樣用戶自行選擇。希望對您有幫助。
看到下一個版號提示更新時，請放心更新。
在設定的版塊，代碼高亮的下方會新增這個特色區塊。

**Comment by terrylinooo** [comment]
done.

**Comment by allenjia09** [comment]
谢谢，太赞了。。
