### ISSUE TITLE
Ctrl+right arrow moves coursor incorrectly

### ISSUE THREAD

**Issue by trejder** [terrylinooo/githuber-md#55]
If you check most of (all of?) editors (i.e. Word, Notepad, Notepad++), you will notice that pressing <kbd>Ctrl</kbd> + <kbd>Right Arrow</kbd> in these editors causes cursor to be moved to the **beginning of next word** (i.e. _after_ delimiting space).

This allows writer to start writing a new word immediately.

In your editor, pressing <kbd>Ctrl</kbd> + <kbd>Right Arrow</kbd> causes cursor to be moved to the **end of current word** (i.e. _before_ delimiting space).

This causes that writer must always remember to hit <kbd>Space</kbd> before starting a new word.

This is very un-handy and against world standards.

**Comment by terrylinooo** [comment]
You can use `Alt` instead of `Ctrl`.

Other keyboard shortcuts, please view `help`

![image](https://user-images.githubusercontent.com/11989371/57176503-6c6b6d80-6e8b-11e9-998f-f64306cab905.png)

**Comment by trejder** [comment]
Thanks for the idea. I just wanted to say that this is counter-productive. All mentioned software is using Ctrl in the way in which you want your users to use Alt. It is wise to not invent own standards and rather follow existing ones instead. Especially, if these standards are long years old.
