### ISSUE TITLE
Plugin settings does not reflect reality

### ISSUE THREAD

**Issue by trejder** [terrylinooo/githuber-md#56]
If I go to Plugins > WP Githuber MD section in my blog I can clearly see that settings set there are incorrect. Instead of reflecting the reality they're set to plugin's default settings.

For example, I have turned off (disabled):

- live preview,
- scroll sync and
- line numbers,

because I don't use them.

But, when I go to plugin settings I can clearly see that on the first tab all of these three settings are checked (turned on).

**Comment by terrylinooo** [comment]
Hello.

It is working on my side. 
You provided too less information so it is hard to replicate your issue.

**Comment by trejder** [comment]
I don't understand what else you want to me provide you?

As I said in the original issue text -- the "Scroll Sync", "Live Preview" and "Show Line Numbers" (and many more!) items in my settings are set to "true" claiming that these features are enabled while this is not true at all -- in fact they are all disabled in my case. I don't use live preview (thus I don't use scroll sync as well) and I don't have line numbers visible in my editor.

This is not only a bogus information, but it is also hard to use. Because, when I save settings without changing these switches (i.e. without again and again disabling line numbers, scroll sync and live preview) then these options become enabled even though they were disabled when I opened settings.
