### ISSUE TITLE
css + jquery added on front ?

### ISSUE THREAD

**Issue by BertrandGouny** [terrylinooo/githuber-md#59]
Hello,
First thanks for this great plugin, very useful and easy to use.

I noticed that this plugin adds 'githuber-md.css' and jquery files on the front.
Is this required ? 

Would it be better to add this only in the admin panel ?

**Comment by terrylinooo** [comment]
Both files only work on GFM Tasklist and Clipboard.
I am considering moving them into the in-page script section.

**Comment by BertrandGouny** [comment]
Thanks for the quick reply and release !
