### ISSUE TITLE
Can't paste /display images

### ISSUE THREAD

**Issue by cbebek** [terrylinooo/githuber-md#6]
I'm unable to insert images into pages with your plugin installed. If I add an image the traditional way, then activate your plugin and edit the page, the image won't display

**Comment by cbebek** [comment]
5.0.3

**Comment by terrylinooo** [comment]
Thanks for reporting this issue, I'll fix it in two days.

**Comment by terrylinooo** [comment]
I will be fixed in next version 1.5.1

**Comment by ndrsfldl** [comment]
Hello Terry, the problem still exists with version 1.8.0 on my installation of Wordpress (5.1.1, PHP 5.6.40). I'm unable to insert images with the "add media" button. Any suggestions?

**Comment by trejder** [comment]
The problem still exists in 1.8.5 -- #44.
