### ISSUE TITLE
Enable Markdown also for custom field in Custom Fields of Toolset Types

### ISSUE THREAD

**Issue by deliverwow** [terrylinooo/githuber-md#60]
Using the Toolset Types ( https://toolset.com/ )
it is not possible to use Githuber MD on the WYSIWIG fields of custom fields.

How to reproduce

a) Install toolset types
b) Create a custom type
c) Add a custom field of type WYSIWIG 

Expected behavior

1) Feature to Enable/Disable for all Toolset Types WYSIWIG fields
2) Feature to Enable/Disable for some Toolset Type WYSIWIG fields (for legacy content)

**Comment by terrylinooo** [comment]
Githuber MD uses CodeMirror to build a Markdown editor, it is not using the WYSIWIG (TinyMCE, the most popular rich text editor) that WordPress originally uses. So, it will be having the problems on those third-party plugins which are supporting TinyMCE. 
You have to make a choice, only use Jetpack module + TinyMCE or just simply use Githuber MD.
