### ISSUE TITLE
Compatibility with WPML

### ISSUE THREAD

**Issue by deliverwow** [terrylinooo/githuber-md#61]
Using WPML for post translation the content doesn't get translated.

A post that is written in Githuber doesn't translator using WPML.

That's obviously because of the Markdown extra post field. 

Not sure how to solve that. Currently a pain and copying the resulting HTML into the translated post and working in HTML in the translation again.

**Comment by terrylinooo** [comment]
I personally not use WPML and have no experience on that plugin, I have no idea in integrating them.
I also no plan to deal with third-party plugins because I'm always busy at work, only do things I am interested in.
