### ISSUE TITLE
A question: What is the Docs type

### ISSUE THREAD

**Issue by adriatic** [terrylinooo/githuber-md#63]
![image](https://user-images.githubusercontent.com/2712405/57252673-bd5d9c00-701a-11e9-9a6d-0ecae1ae5cba.png)

It seems that both alternatives are possible: 
- githuber-md creates it's own **`doc`** special type 
- **`docs`** is an existing WP type that I am just not aware of.

My plan is to use your plugin with the **`weDocs – the documentation plugin`** - can you please help me by describing the optimal setup for writing documentation for my application using **[weDocs](https://github.com/tareq1988/wedocs-plugin/wiki)** - where all of my docs will be written in markdown
___

**A different question**: As I plan to provide you with lots of feedback (because your plugin deserves all help I can provide at the moment) and do not have too much time, I would appreciate if you allow me to use this (**`GitHub issues`**) media to write my suggestions as well as bug reports.

_The more I look into your plugin, its feature set and your attention to details, the more I like it_

**Comment by terrylinooo** [comment]
It is a custom post type created by one of the other plugins that you're using.
Githuber MD  supports custom post type so that's why you can see it is there.
If you are not planning to use Githuber MD on the post type, just ignore it.
