### ISSUE TITLE
Spell checker in browser not working anymore

### ISSUE THREAD

**Issue by christophcemper** [terrylinooo/githuber-md#65]
**Describe the bug**

it looks like the Chrome browser based spell-checker is forced disabled now in the MD field,
which is a pain as I'm very used to using it

**To reproduce**

1. Enable Browser Spell Checker
2. Type something with a typo

**Expected behavior**

Expect it to red underline in the MD field

**Screenshots**

![image](https://user-images.githubusercontent.com/12080594/57280754-ba5dbc80-70a9-11e9-99bb-62bd350d0169.png)

https://www.screencast.com/t/Kq7fHcKjf8u0

**Server environment**

 - WordPress version 4.9.10
 - WP Githuber MD plugin version 1.10.0
 - Server Settings

Operating System: Linux
PHP Version: 7.2.17-1+ubuntu18.04.1+deb.sury.org+3
Server Software: Apache

**User environment**

 - OS: Windows 
 - Browser: Chrome

**Additional context**

not aware what to add

**Comment by terrylinooo** [comment]
Thanks for your feedback. I will take a look at this issue.

**Comment by terrylinooo** [comment]
In-browser Spellcheck only works in `input` and `textarea` fields. 
Thanks for some amazing developers share their code, I can implement this feature in Githuber MD by simply modifying their code.

The Spell Check feature will come in the next version.

![image](https://user-images.githubusercontent.com/11989371/57445432-ef723680-7284-11e9-9620-f6d16b471a01.png)

I am still testing it. If everything works as expected, I will release it today.
