### ISSUE TITLE
Offset Row Numbers in Code Snippets

### ISSUE THREAD

**Issue by mredig** [terrylinooo/githuber-md#66]
**Describe the bug**
I have syntax highlighting turned on for my code snippets, but sometimes it decides to offset the row numbers.

**To reproduce**

1. Go [here](https://mikespsyche.com/typealias-shorthand-string-string-str/) to see the bug in action

**Expected behavior**

1. It works [here](https://mikespsyche.com/let-subviews-view-subviews-noimeanallsubviews/)
I'm not sure what I did (if anything) differently.

**Screenshots**
I linked

**Server environment**

 - WordPress version 5.1.1
 - WP Githuber MD plugin version - 1.10.1
 - PHP version - 7.0.33-0+deb9u3 

**User environment**

 - OS: Debian 9
 - Browser - I've test Chrome and Safari

**Additional context**

I've tried adjusting whitespace between lines, indenting, unindenting, whitespace between the backticks for starting and ending, but each section always results in the same as it was before.

**Comment by terrylinooo** [comment]
Thanks for your feedback. I will fix it as soon as possible.

**Comment by mredig** [comment]
Awesome! Great plugin, by the way. :D

**Comment by terrylinooo** [comment]
I cannot reproduce your issue on my development environment.

![image](https://user-images.githubusercontent.com/11989371/57367265-43b0e400-71bb-11e9-82e4-6ab5e7d36cea.png)

Everything works fine. 
Can you try installing another theme to see how it work?
