### ISSUE TITLE
Can not parse javascript template literals on Web

### ISSUE THREAD

**Issue by johnson4932** [terrylinooo/githuber-md#68]
**問題或臭蟲**

使用 javasciprt template literals 時，在畫面上無法顯示內容。

**如何重現**

請告知重現此問題的步驟回何：

1.文章中使用 javascript code block，內容有使用到 template literals
```
Vue.component('hello', {
    template: `
        <div class="hello">
            <h3>Hello Component</h3>
            <p>
                <!-- Slot 預留空間，可以傳入人名 -->
                Hello，<slot></slot>
            </p>
        </div>
    `
});
```
**預期的行為或結果**

文章完整顯示上述程式碼。

**畫面截圖**

<img width="749" alt="螢幕快照 2019-05-13 上午1 17 27" src="https://user-images.githubusercontent.com/672892/57585606-f1562700-751c-11e9-9496-07a8865461e4.png">

<img width="776" alt="螢幕快照 2019-05-13 上午1 18 47" src="https://user-images.githubusercontent.com/672892/57585620-1b0f4e00-751d-11e9-92e7-91ac3e9e468e.png">

**伺服器環境**

 - WordPress 版本 [ e.g. 5.0.1 ]
 - WP Githuber MD 版本 [ e.g. 1.11.0 ]
 - PHP 版本 [ e.g. 7.2.17 ]

**用戶端環境**

 - 作業系統 [ e.g. Ubuntu ]
 - 瀏覽器 [ e.g. Chrome]

**Comment by terrylinooo** [comment]
謝謝回報。已修復。
在 1.11.1 版更新。
