### ISSUE TITLE
能增加画廊功能么

### ISSUE THREAD

**Issue by 52Lau** [terrylinooo/githuber-md#69]
**如果沒有提供以下詳細資訊，您開立的問題回報會被無視。**

**問題或臭蟲**

清楚的說明問題發生的情況及結果。

**如何重現**

請告知重現此問題的步驟回何：

**預期的行為或結果**

清楚的說明您預期什麼樣的結果才是正常。

**畫面截圖**

1. 請提問題發生時的截圖
2. 例如按 F12，查看 Google Chome 開發人員工具的畫面有無紅色字樣錯誤訊息。

**伺服器環境**

 - WordPress 版本 [ e.g. 5.0.1 ]
 - WP Githuber MD 版本 [ e.g. 1.9.0 ]
 - PHP 版本 [ e.g. 5.3.6 ]

**用戶端環境**

 - 作業系統 [ e.g. Windows ]
 - 瀏覽器 [ e.g. Chrome, Safari, Firebox ]

**其它說明**

如果有的話，請提供。

**Comment by terrylinooo** [comment]
画廊功能是什麼? 能否清楚描述。
