### ISSUE TITLE
Using katex inline

### ISSUE THREAD

**Issue by ash975** [terrylinooo/githuber-md#7]
Recently I use the editor and mynote themes, it's awsome.
I have a question with build-in katex: the Code-Block Katex works fine, but how can I use it INLINE ?

Many Thanks.

**Comment by terrylinooo** [comment]
I can add it (katex inline), but currently have no idea.

Maybe `katex: \f{x} = \int_{-\infty}^\infty \hat \f\xi\,e^{2 \pi i \xi x} \,d\xi`

**Comment by terrylinooo** [comment]
@ash975 Inline KaTaX will be added in next version (1.5.1)  

How to use it:

test inline katex `$$ c = \pm\sqrt{a^2 + b^2} $$` this is an example.

Demo:

![image](https://user-images.githubusercontent.com/11989371/52116167-72af3b00-264b-11e9-9df8-6feb148913b4.png)

![image](https://user-images.githubusercontent.com/11989371/52116195-83f84780-264b-11e9-9633-f4d11f638cae.png)
