### ISSUE TITLE
Setting feature image would auto insert a annoying html scripts in editing area.

### ISSUE THREAD

**Issue by syhily** [terrylinooo/githuber-md#70]
**Describe the bug**

After setting a feature image on article editing page, a strange html scripts would be auto inserted into the editing area like the image below.

**To reproduce**

1. Go to `xxxxx/wp-admin/post-new.php`
2. Click on Feature Image -> add feature image
3. See error

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/1761698/57754255-95f48680-7720-11e9-9179-db4b42174749.png)

**Server environment**

 - WordPress version [ 5.2 ]
 - WP Githuber MD plugin version [ latest ]
 - PHP version [ 7.2 ]

**User environment**

 - OS: [ CentOS 7.2 ]
 - Browser [ Chrome ]

**Comment by terrylinooo** [comment]
Thank you very much for the feedback. I will fix it as soon as possible.

**Comment by syhily** [comment]
Tks, the latest release fixed the feature image setting issue.
