### ISSUE TITLE
The scala code snippet highlight issues

### ISSUE THREAD

**Issue by syhily** [terrylinooo/githuber-md#72]
**Describe the bug**

The scala code in article don't have a proper code highlight. The web console show a prism error.

**To reproduce**

1. Create a article.
2. Add a scala code snippet.

```scala
def fib3( n : Int) : Int = { 
  def fib_tail( n: Int, a:Int, b:Int): Int = n match {
    case 0 => a 
    case _ => fib_tail( n-1, b, a+b )
  }
  return fib_tail( n, 0, 1)
}
```

3. Save the article and view it.
4. See error in browser console, the code don't have any highlight.

**Screenshots**

![image](https://user-images.githubusercontent.com/1761698/57824239-fb9e4c80-77cc-11e9-9956-9dced9ea0b02.png)

**Server environment**

 - WordPress version [ 5.2 ]
 - WP Githuber MD plugin version [ 1.11.3 ]
 - PHP version [ 7.2 ]

**User environment**

 - OS: [ macOS 10.14.5 ]
 - Browser [ Edge ]

**Comment by terrylinooo** [comment]
It works well in my development environment.

![image](https://user-images.githubusercontent.com/11989371/57825009-9c8e0700-77cf-11e9-9681-08f736600e2b.png)

I need more information to excatly solve this issue. Could you provide the screenshot of the Chrome developer console or your web page URL? I will take a look into it.

**Comment by syhily** [comment]
https://yufan.me/rewrite-your-logic/

A article written by myself which has code highlight issue.

**Comment by terrylinooo** [comment]
The order in prism component files is incorrect.
prism-java.min.js needs to be loaded before prism-scala.min.js
It works on my side but not yours.
I'm not sure what causes this issue occurred but I will fix it as soon as possible.

**Comment by syhily** [comment]
![image](https://user-images.githubusercontent.com/1761698/57835396-feab3400-77f0-11e9-99b3-c9aee99d7f0d.png)

Remove the foreach `array_reverse` fixed my issues. But I thought this should be another feature request.
How to order the prism language scripts.

**Comment by syhily** [comment]
The prism autoloader could be a better solution for this issue.
https://prismjs.com/plugins/autoloader/
