### ISSUE TITLE
能不能像简书那样，图片自动本地化

### ISSUE THREAD

**Issue by 52Lau** [terrylinooo/githuber-md#75]
很感谢作者的一直坚持！
在使用过程中，可能我是在电脑上使用markdown工具写好文章后，直接复制到Wordpress的编辑器，里面的图片是外部链接，但是我可能不太需要图片托管，还是想把图片留在服务器上，所以能不能像那个简书一样，外部的链接，保存的时候，会把图片上传到服务器，个人认为这是一个非常不错的功能，不知道作者能否实现呢？万分感激

**Comment by terrylinooo** [comment]
嗯。這很簡單做到。不過我正在更新版本了。等下一版再放進去。

**Comment by 52Lau** [comment]
嗯，感谢作者

**Comment by jonas201711** [comment]
@terrylinooo  请教一下， Macbook， 图片复制到剪切板，但是为什么不能像你demo中的那样，直接command + v 粘贴到文章中呢

**Comment by jonas201711** [comment]
![image](https://user-images.githubusercontent.com/33820594/59735143-e5315800-9286-11e9-8e51-8153f1d37d72.png)

**Comment by terrylinooo** [comment]
我沒有使用 mac 。不大清楚。不過你的問題我會研究一下。最近比較忙。假如有進一步更新我會在此通知你。

**Comment by jonas201711** [comment]
github 这个editor 完美支持 command + v  ， anyway ,thank you very much!

**Comment by terrylinooo** [comment]
@jonas201711  經檢查，和 katax 模組衝突。如果您沒有用到數學公式模組的話，請把它關閉。

這幾天我工作忙，有空閒時我會修復它，然後把此帖要做的功能補上。

**Comment by terrylinooo** [comment]
在 1.12.0 實現。
