### ISSUE TITLE
WP Githuber MD disables Gutenberg editor for custom post types.

### ISSUE THREAD

**Issue by chop-chop-org** [terrylinooo/githuber-md#76]
Thank for the great plugin!

**Describe the bug**

I enabled gutenberg blocks for custom post type. But what see is classic editor. When I deactivate the plugin, the Gutenberg editor shows up for custom post types. When the plugin is active, it doesn't matter whether Markdown is enabled for given CPT or not. Gutenberg editor just doesn't appear.

**To reproduce**

1. Create CPT with Gutenberg editor support (show_in_rest: true)
2. Enable Gutenberg editor for all post types
3. Enable WP Githuber MD plugin
4. Go into a custom post type page and see the classic editor instead of the Gutenberg editor.

**Expected behavior**

We need what works for regular posts. When the Markdown is disabled, we need to see pretty Gutenberg editor instead of Classic Editor. 

**Screenshots**
Plugin on:

<img width="1433" alt="plugin_on" src="https://user-images.githubusercontent.com/5121413/58340273-b4a6fb80-7e4b-11e9-9056-f9244b8db8e8.png">

Plugin off:

<img width="1437" alt="plugin_off" src="https://user-images.githubusercontent.com/5121413/58340276-b7a1ec00-7e4b-11e9-9917-6c3d6680d757.png">

**Server environment**

 - WordPress version [ 5.2.1 ]
 - WP Githuber MD plugin version [ 1.11.4 ]
 - PHP version [ 7.1.22 ]

**User environment**

 - OS: [ latest MacOS ]
 - Browser [ latest Chrome ]

**Comment by dnowba** [comment]
我也有類似的問題，但是是相反的需求。
未啟用 WP Githuber MD 之前，我可以在 Pages 上使用 WPBakery Page Builder 頁面編輯器，Posts 上使用 Classic 編輯器。
啟用了 WP Githuber MD 之後，除了指定要用 MD 的 CPT 外，其它的都會被強制設定成使用 Gutenberg Editor。
這樣子會導致我沒有辦法使用 WPBakery Page Builder，因為它需要 Classic Editor。
希望除了勾選要用 WP Githuber MD 的 CPTs 以外，都可以保留原來的編輯器設定。
