### ISSUE TITLE
Allow to make custom syntax highlight themes

### ISSUE THREAD

**Issue by egordorichev** [terrylinooo/githuber-md#77]
Hey there! First of all, I wanted to say big thank you for making this editor. It is really awesome, the best one out there!

Sadly tho, the syntax highlighting extension supports only a small set of themes, and I wonder if there is any way to add new themes? (like I want my monocai really badly!)

It would be an awesome thing to add, imo!
Thanks!

**Comment by terrylinooo** [comment]
Githuber MD is using Prism.js syntax highlighter. The themes there are just simple CSS files.
You can take a look in https://github.com/PrismJS/prism/tree/master/themes
You can define your own CSS and overwrite the original one.
Hope this helps.
