### ISSUE TITLE
Bug: Bulk editing posts converts markdown to HTML in post_content_filtered

### ISSUE THREAD

**Issue by viktorix** [terrylinooo/githuber-md#78]
**Describe the bug**

We had 40 posts, all with markdown, that was created by user1. I wanted to re-assign all 40 posts to user2. So I selected 40 posts, and used "Edit" dropdown option to make bulk edits. I selected user2, and hit save. I went inside a post to make some edits, but I realized that markdown for all 40 posts was converted to HTML. 

I went into database and checked contents of post_content_filtered column, everything is HTML. There was no markdown left.

I repeated this with test posts. It happens every time. It doesn't matter what change is made to the posts. The bulk editing action converts markdown to HTML.

**To reproduce**

1. Create a post with markdown, save as draft or publish, doesn't matter.
2. Go to All Posts, select this post by ticking checkbox.
3. In the dropdown, select "Edit" and click "Apply".
4. Make a change, doesn't matter what. Assign to category, change author, etc.
5. Click Save.
6. Open your post again and check markdown textarea. It should be HTML now, no markdown.

**Expected behavior**

Performing bulk edits should not convert markdown to HTML.

**Screenshots**

![image](https://user-images.githubusercontent.com/1692600/59039857-9b3a8200-8843-11e9-919b-46720a595646.png)

**Server environment**

 - WordPress: 5.2.1
 - WP Githuber MD plugin version 1.11.4
 - PHP version 7.3.5

**User environment**

 - OS: Win 10
 - Browser: Chrome

**Additional context**

I think what might be happening, for some reason `post_content` overrides `post_content_filtered` when performing bulk edit.

**Comment by terrylinooo** [comment]
Thanks for your feedback. I will look into it.

**Comment by kuworking** [comment]
Same here, in my case what I did was to assign categories, and now I've realized everything is in html

**Comment by stuehmer** [comment]
Same here, sorry for the spam :)

**Comment by BeardScript** [comment]
This happens to me with DocPress posts in an unpredictable way. Whenever I go back to a post, sometimes it's in markdown and others in HTML. This wouldn't be such a big issue if not for #79 which augments the problem.

**Comment by fireundubh** [comment]
This is still happening.

**Comment by zszymczyk** [comment]
I have the same problem. Does someone has any solution?
