### ISSUE TITLE
Bug: HTML to Markdown converter escapes single quotes with backslash

### ISSUE THREAD

**Issue by viktorix** [terrylinooo/githuber-md#79]
**Describe the bug**

I found this minor bug while dealing with issue #78. When you use HTML to Markdown converter tool, it will escape single quotes with a backslash. It looks like in the preview, but it is left in `post_content` so all backslashes show up in the frontend.

**To reproduce**

1. Create new post with HTML and make sure your text has single quotes in the markdown editor.
2. Use HTML to Markdown converter tools to convert it.
3. You will see single quotes escaped with backslash.
4. Everything looks good in preview.
5. Save the post and look at it in the frontend, you'll see all backslashes visible.

**Expected behavior**

Using HTML to Markdown converter shouldn't escape single quotes with backslash. 

**Screenshots**

![image](https://user-images.githubusercontent.com/1692600/59040475-bd80cf80-8844-11e9-827b-62218ca3e983.png)

**Server environment**

 - WordPress: 5.2.1
 - WP Githuber MD plugin version 1.11.4
 - PHP version 7.3.5

**User environment**

 - OS: Win 10
 - Browser: Chrome

**Comment by terrylinooo** [comment]
Thanks for your feedback. I will look into it.

**Comment by BeardScript** [comment]
Hi, thanks for the great plugin @terrylinooo 

Any updates on this? I'm having the same issue with WP Githuber MD.
