### ISSUE TITLE
你好！能否将插件和 Rank Math 插件适配一下（很像Yoast SEO）

### ISSUE THREAD

**Issue by znnnnn** [terrylinooo/githuber-md#82]
我看了一下贵插件和Yoast SEO适配的很好，比心，作者棒棒的。不知道能否和Rank Math也适配一下？

开启了markdown：
![image](https://user-images.githubusercontent.com/30922257/59150759-69036d00-8a5b-11e9-8c24-d31e4f606698.png)

未开启markdown：
![image](https://user-images.githubusercontent.com/30922257/59150767-8cc6b300-8a5b-11e9-8a60-be3aef178162.png)

有关`Rank Math`插件：在WordPress后台插件库中搜`Rank Math`即可安装，是一个很像 `Yoast SEO`的免费插件，但是确实意外的好用，基本有了Yoast 所有收费的功能，所以我选择了用它。

**最后，插件很棒，希望能越来越好！**

**Comment by qiujiangkun** [comment]
我觉得这个东西工作量有点大。我建议你研究一下githuber的代码，自己添加。在这里夸一下githuber的代码，非常清晰
