### ISSUE TITLE
请问有机会支持Emoji吗

### ISSUE THREAD

**Issue by k99k5** [terrylinooo/githuber-md#86]
就是编辑器能不能直接支持插入....

**Comment by terrylinooo** [comment]
Emoji 本來有做進去，不過本地端放圖檔太大了，整個插件包很大，所以打消這個念頭。

**Comment by k99k5** [comment]
> Emoji 本來有做進去，不過本地端放圖檔太大了，整個插件包很大，所以打消這個念頭。

但是不是字体本身就支持Emoji吗。。不需要图片吧。。

**Comment by terrylinooo** [comment]
Emoji 是字體，但轉成圖片喔。例如 GitHub 的 emoji 
https://gist.github.com/roachhd/1f029bd4b50b8a524f3c

**Comment by k99k5** [comment]
> Emoji 是字體，但轉成圖片喔。例如 GitHub 的 emoji
> https://gist.github.com/roachhd/1f029bd4b50b8a524f3c

WordPress好像本身带了吧。。就像这个s.w.org
https://s.w.org/images/core/emoji/12.0.0-1/svg/1f642.svg

**Comment by BryanXu77** [comment]
嗯，大点不怕，建议加上

**Comment by canyuedao** [comment]
一直在用这个插件，希望能加上这个功能，挺实用的

**Comment by terrylinooo** [comment]
這次的更新修完 bug 我再看看。加上不難，主要是不想增加整個 plugin 的大小。優先考率 WordPress 內建的。

**Comment by terrylinooo** [comment]
Emoji module will come in the next version (1.14.0)

**Comment by terrylinooo** [comment]
1.14.0 已加入此功能。
