### ISSUE TITLE
"Home" and "End" buttons moves caret incorrectly in case of multi-line text

### ISSUE THREAD

**Issue by trejder** [terrylinooo/githuber-md#87]
**Describe the bug**

When text in a given paragraph is too long and line spans into second and more lines in the editor, then pressing <kbd>Home</kbd>  or <kbd>End</kbd> moves caret (cursor) to the beginning or end of **the whole block of text** in the multi-line block of text:

![In GitHubber MD](https://user-images.githubusercontent.com/2903392/59260354-c35b2400-8c3b-11e9-8d10-737b8a9a204c.png)

In GitHub editor (and many, many other places) pressing <kbd>Home</kbd>  or <kbd>End</kbd> in the very same situation moves caret to the beginning or end of **current line** in the multi-line block of text:

![In GitHub](https://user-images.githubusercontent.com/2903392/59262600-cd7f2180-8c3f-11e9-8fcd-17730be0659e.png)

Exactly the same problem is when pressing <kbd>Home</kbd>  or <kbd>End</kbd> while holding <kbd>Shift</kbd> button (to i.e. select some text). Only part of text from current cursor position to the beginning or end of current line should be selected. Githubber WP selects whole text, from current cursor position to the beginning or end of the whole block of text instead.

**To reproduce**

1. Open any post in Wordpress with GitHubber WP editor enabled.
2. Provide enough text to create at least a 2-3 lines block of text.
3. Place cursor (caret) in the middle of the middle of line.
4. Press <kbd>Home</kbd>  or <kbd>End</kbd> and observe the results.

Compare results with above screenshots.

**Expected behavior**

Pressing <kbd>Home</kbd>  or <kbd>End</kbd> in a multi-line block of text must move cursor to the beginning or end current line, not the beginning or end of whole block of text.

**Server environment**

 - WordPress version: **5.2.1**
 - WP Githuber MD plugin version: **1.11.4**
 - PHP version: **7.1**

**User environment**

 - OS: **Windows 10**
 - Browser: **Chrome**

**Comment by terrylinooo** [comment]
Thanks for your feedback. I'll take a look at this issue.

**Comment by fduniho** [comment]
I came here about this same issue. It is most frustrating, and even though this post was originally made three years ago, nothing has been done yet. I will add details on my own environment. I am currently using Firefox 104.0 with Windows 10, and my server environment is WordPress 5.6.8, PHP 7.3.33, Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_fcgid/2.3.9 PHP/7.3.33, and MySQL 5.5.68-MariaDB.

**Comment by trejder** [comment]
I cannot confirm, if the bug still exists, because I have stopped using this plugin in favor of Gutenberg block editor.
