### ISSUE TITLE
代码段中的字符被显示为转义字符

### ISSUE THREAD

**Issue by SkiTiSu** [terrylinooo/githuber-md#89]
首先感谢作者一直维护这款优秀的插件~

**問題或臭蟲**

代码段中的字符被显示为转义字符。
查看数据库发现，代码块中的`<`存入post_content_filtered时转义为`&lt;`，然而存入post_content时，再次被转义为了`&amp;lt;`。我同时测试了另一款插件WP Editor.md，并没有这样的问题。
debug时发现，在 #30 中，/Controllers/Markdown.php中的`decode_code_blocks`处理被禁用了。将其启用（修改false为true）后问题解决。不清楚 #30 中为何会有这样的问题，是否是WordPress不同版本处理方式不同呢。

**如何重現**

1. 新建文章
2. 插入带有`<`、`>`、`"`等会被转义的代码块，如
<pre>
```cpp
#include &lt;stdio.h&gt;
```
</pre>
3. 预览或发布文章
4. 发现实际变成
```
#include &lt;stdio.h&gt;
```

**預期的行為或結果**

应显示为与预览一致

**畫面截圖**

![image](https://user-images.githubusercontent.com/8959735/59553242-d74cb000-8fc4-11e9-9b44-bd85089a99de.png)
![image](https://user-images.githubusercontent.com/8959735/59553248-f4817e80-8fc4-11e9-92ac-d82852f814a3.png)

主题内使用了自定义代码高亮样式，经测试与本问题无关

**伺服器環境**

 - WordPress 版本 5.2.1
 - WP Githuber MD 版本 1.11.4
 - PHP 版本 7.2与7.3均测试过

**用戶端環境**

 - 作業系統 Windows 10
 - 瀏覽器 Chrome 75

**其它說明**

无

**Comment by llht** [comment]
同样是该问题，请问已经解决了吗？已经困扰一段时间了

**Comment by SkiTiSu** [comment]
@llht 我自己修改代码解决了，问题描述中写了如何修改，再详细一点的话，/Controllers/Markdown.php中第1041行的
```php
			'decode_code_blocks' => false, // Fix: issue #30
```
修改为
```php
			'decode_code_blocks' => true, // Fix: issue #30
```

**Comment by llht** [comment]
@SkiTiSu 你好，非常感谢，完美解决！

**Comment by llht** [comment]
@SkiTiSu 你好，我发现更改这行代码之后，只有写文章进行预览时转义字符可以正常显示，但是正式进入网站依然无法显示，`<`依然显示为`&lt`，截图如下：
## 预览时：
![GSDS@XTF9EM`J3~`{}H 0@G](https://user-images.githubusercontent.com/36131080/60332890-49ac8f80-99ca-11e9-9b94-e97609a55cdf.png)
## 正常查看网页
![WOWEPU3U322H%$8Q9_47}54](https://user-images.githubusercontent.com/36131080/60332884-487b6280-99ca-11e9-83b7-31c97470b317.png)
我从未接触过web编程，找不出问题所在，是否是我的wordpress版本（5.2.2）问题呢？希望可以得到你的解答，不胜感激

**Comment by terrylinooo** [comment]
不確定是什麼原因。我的開發環境和正式網站上的測試都正常。
因為每個人安裝的 plugin 都不同，比較難除錯。
所以我在設定偏號的頁籤那邊新增一個設定值，`Issue #89` 給有這種情況的朋友們免修改源碼，暫時解決這個問題。

這個設定在 1.11.5 版更新 (預計今晚更新)
