### ISSUE TITLE
Per Post Enable/Disable of Markdown

### ISSUE THREAD

**Issue by christophcemper** [terrylinooo/githuber-md#9]
I love Githuber-MD but I have a large existing website.

I would like to get started writing and converting to MD, 
but that will take weeks or months, so I need a way to keep the editor switchable
between the Githuber and the default visual/text editor

That'd be awesome.

thanks so much

**Comment by terrylinooo** [comment]
@christophcemper  

I will take your suggestion, and will make it in version 1.6.0
However, you can turn on `HTML decode` to support your old posts.

![image](https://user-images.githubusercontent.com/11989371/52161384-5076f500-26ff-11e9-9601-29c3dfb528d3.png)

Any update about your suggestions I will mention you here. Thanks for using WP Githuber MD.

**Comment by terrylinooo** [comment]
![image](https://user-images.githubusercontent.com/11989371/52909235-6ae4cd00-32c0-11e9-8367-5cd0c5c471d2.png)

I have done this feature that you request for.
The version 1.6.0 will be released soon.

**Comment by christophcemper** [comment]
Oh lovely – I cannot wait to see this
