### ISSUE TITLE
编辑器中光标后面有"6="

### ISSUE THREAD

**Issue by zhudabai** [terrylinooo/githuber-md#90]
打开编辑器后光标后有6=字符
![2019-06-16_111458](https://user-images.githubusercontent.com/38370142/59558601-8e2e4780-9028-11e9-8978-a51b606942d3.png)

![2019-06-16_112016](https://user-images.githubusercontent.com/38370142/59558619-c46bc700-9028-11e9-9186-e2ebe26991e0.png)

WordPress版本 4.9
php版本7.2

**Comment by terrylinooo** [comment]
能否貼上開發人員除錯面版 (Chrome 按 F12 ) 選 console 看是否有錯誤訊息。
還有您在 Githuber MD 裡開啟的功能選項是否抓個圖列表給我看看。
因為我無法重現你的問題，要試著用和你一樣的配置來測試。

**Comment by zhudabai** [comment]
问题已经得到解决,是我的nginx的字符集配置的有问题,谢谢您的回复
