### ISSUE TITLE
`$xxx` will prevent page from rendering

### ISSUE THREAD

**Issue by uzabon** [terrylinooo/githuber-md#92]
I am using wordpress 5.1.1 and plugin version 4.11.4. And i enable the syntax highlight , katex and mermaid modules with other setting default.

every time i add something like \`$xxx\`, the preview in editor will display the wanted effect but the preview in post will display nothing but an empty page. But when i change to \`\\$xxx\` or \`\\\\$xxx\`, the preview will recover.

I am writing php so the dollar sign will always appear in the front of word. I think it will be better if this bug can be fixed.

**Screenshots**

![Screenshot from 2019-06-18 10-10-49](https://user-images.githubusercontent.com/25972051/59648380-86e67580-91b1-11e9-8c59-ce5c24a6ac93.png)

the exact problem above and the simple resolution below

![Screenshot from 2019-06-18 10-13-01](https://user-images.githubusercontent.com/25972051/59648539-fd837300-91b1-11e9-91d4-70bd35aa7700.png)

**Comment by terrylinooo** [comment]
您可以貼一段您的內文在這裡。我用你的文字測試。

**Comment by uzabon** [comment]
here are two example

> 这样就很容易得出，\`$assign\`将会指向这个实例，而\`$reference\`将会指向空。

> 如下图所示，\`$bar\`是没有任何影响的，变化的只是\`$var\`的值。

I have found that as long as the first char is not dollar sign in quote syntax, the page will show normally.

**Comment by terrylinooo** [comment]
這個 bug 已證實。我修復後會在此回文通知。
謝謝回報~

**Comment by terrylinooo** [comment]
經檢查，和 katax 模組衝突。如果您沒有用到數學公式模組的話，請把它關閉。

這幾天我工作忙，有空閒時我會修復它，然後把此帖要做的功能補上。
