### ISSUE TITLE
请问有没有可能支持tocbot？

### ISSUE THREAD

**Issue by momo296859251** [terrylinooo/githuber-md#93]
很喜欢作者的markdown插件，我之前使用的markdown插件有个tocbot生成文章目录的功能，这个功能也很实用，不知道能否加入这个功能？

**Comment by terrylinooo** [comment]
相同性質的功能已經有了，所以我沒有興趣去做類似的且和 Markdown 本身沒有關聯的東西。這個插件主要專注在 Markdown 功能。
