### ISSUE TITLE
Wrong SVN directory structure causing old version download to fail

### ISSUE THREAD

**Issue by ericwong3** [terrylinooo/githuber-md#94]
**Describe the bug**

The plugin is not directly usable when user choose to download an old version from  https://wordpress.org/plugins/wp-githuber-md/advanced/ due to wrong folder structure (wrong in SVN causing wrong in the generated zip)

**To reproduce**

1. Go to https://wordpress.org/plugins/wp-githuber-md/advanced/
2. Scroll to bottom, in Previous Versions section, select any old version (e.g. 1.11.4)
3. Download and unpack.

**Expected behavior**

The zip should contain wp-githuber-md/ directory at level one, and wp-githuber-md/githuber-md.php at level 2.
What actually is there in second level is 4 folders: assets, branches, tags, trunks.

**Server environment**

N/A

**User environment**

Not relevant

**Screenshot**

![image](https://user-images.githubusercontent.com/1881669/60154111-f34c1f00-9818-11e9-8679-a7320bb220a5.png)

**Additional context**

I am no expert in Wordpress plugin development, but as warned [here](https://developer.wordpress.org/plugins/wordpress-org/how-to-use-subversion/):
> Do not put your main plugin file in a subfolder of trunk, like /trunk/my-plugin/my-plugin.php as that will break downloads. You may use subfolders for included files.

This issue is especially bad because when installing Wordpress plugins through composer (via wpackagist), that zip file is downloaded and unzipped, this causes the extracted folder to have wrong directory structure, and results in this plugin not being detected by WP.

**Comment by terrylinooo** [comment]
I didn't notice that. Thanks for your feedback.

**Comment by terrylinooo** [comment]
fixed
