### ISSUE TITLE
只使用Katex inline时，Katex script无法被加载

### ISSUE THREAD

**Issue by lizhihao6** [terrylinooo/githuber-md#96]
**如果沒有提供以下詳細資訊，您開立的問題回報會被無視。**

**問題或臭蟲**

如果一篇文章中只有\`$$ this is a LaTex inline code $$\` 这样的 inline latex，而从未使用
> \`\`\` katex
> this is a Latex paragraphy
> \`\`\`

的时候，会无法加载 katex 的 script

在文章中加入
> \`\`\` katex
> this is a Latex paragraphy
> \`\`\`

就会正常加载katex script

**如何重現**

1. 指定 katex script cdn (方便查看是否加载)
2. 文章中只使用 inline katex
3. 发布文章后无法正常加载 katex script 

**預期的行為或結果**

**畫面截圖**

![](https://test-1253607195.cos.ap-shanghai.myqcloud.com/2019-7-3/20190706043318.png)

文章中添加
> \`\`\` katex
> \`\`\`

后可正常加载
![](https://test-1253607195.cos.ap-shanghai.myqcloud.com/2019-7-3/20190706043752.png)

**伺服器環境**

 - WordPress 版本 5.0
 - WP Githuber MD 版本 1.11.5
 - PHP 版本 7.3.6

**用戶端環境**

 - 作業系統 Windows 10
 - 瀏覽器 Chrome

**其它說明**

如果有的話，請提供。

**Comment by terrylinooo** [comment]
在星期一更新修正此問題。

**Comment by lizhihao6** [comment]
辛苦了～
