### ISSUE TITLE
A 'disabled by default' setting

### ISSUE THREAD

**Issue by LostInBrittany** [terrylinooo/githuber-md#98]
**Describe the issue**

I would need an option in Settings, near the option to activate the plugin for different content types, to set if the MD editor should be active by default or not for new posts.

I want to propose to some of my tech-savvy users to write the posts in Markdown, but I need the *by default* editor for new posts to be Gutenberg, not Githuber MD.

I.e., I would want that when a user adds a posts, it opens in the standard WP editor, and they can *Enable Markdown*  checkbox unchecked.

**Comment by terrylinooo** [comment]
ok. I will make it in next version.

**Comment by LostInBrittany** [comment]
Oooh, that's WONDERFUL!!!! THANKS!!!!
