### ISSUE TITLE
启用插件后，wordpress后台“外观——>菜单”这个页面会错位。

### ISSUE THREAD

**Issue by uxcoffee** [terrylinooo/githuber-md#99]
我的wordpress版本是5.1.1，使用的插件是最新版本。启用插件后，发现wordpress设置菜单的页面会发生错位，“Add menu items”和“Menu structure”两个板块整体向右边偏移了几十个像素。导致这两个板块错位。本来是左右布局的，变成了上下布局。建议测试一下是不是bug。谢谢！

**Comment by terrylinooo** [comment]
請關閉 WP Githuber MD 再開啟 Menu 頁面確認是否為插件問題。
